export interface ExpedientRequest {
  id: string;
  recordId: string;
  applicationDate: string;
  receptionDate: string;
  nameOfOwner: string | null;
  holderCharge: string | null;
  phoneOfOwner: string | null;
  emailOfOwner: string | null;
  transferenceId: string;
  stationId: string;
  authorityId: string;
  regionalDelegationId: string;
  sender: string | null;
  observations: string | null;
  targetUser: string;
  urgentPriority: string;
  indicatedTaxpayer: string;
  transferenceFile: string | null;
  transferEntNotes: string | null;
  idAddress: string | null;
  originInfo: string | null;
  circumstantialRecord: string | null;
  previousInquiry: string | null;
  lawsuit: string | null;
  protectNumber: string | null;
  tocaPenal: string | null;
  paperNumber: string;
  paperDate: string;
  indicated: string | null;
  publicMinistry: string;
  court: string | null;
  crime: string | null;
  receiptRoute: string;
  destinationManagement: string | null;
  affair: string;
  satDeterminant: string | null;
  satDirectory: string | null;
  satZoneCoordinator: string | null;
  userCreated: string | null;
  creationDate: string | null;
  userModification: string | null;
  modificationDate: string | null;
  typeOfTransfer: string;
  domainExtinction: string | null;
  version: string | null;
  targetUserType: string;
  trialType: string | null;
  typeRecord: string;
  requestStatus: string;
  fileLeagueType: string | null;
  fileLeagueDate: string | null;
  rejectionComment: string | null;
  authorityOrdering: string | null;
  instanceBpm: string | null;
  trial: string | null;
  compensationType: string | null;
  stateRequestId: string | null;
  searchSiab: string | null;
  priorityDate: string | null;
  rejectionNumber: string | null;
  rulingDocumentId: string | null;
  reportSheet: string | null;
  nameRecipientRuling: string | null;
  postRecipientRuling: string | null;
  paragraphOneRuling: string | null;
  paragraphTwoRuling: string | null;
  nameSignatoryRuling: string | null;
  postSignatoryRuling: string | null;
  ccpRuling: string | null;
  rulingCreatorName: string | null;
  rulingSheetNumber: string | null;
  registrationCoordinatorSae: string | null;
  emailNotification: string | null;
  keyStateOfRepublic: string;
  instanceBpel: string | null;
  verificationDateCump: string | null;
  recordTmpId: string | null;
  coordregsae_ktl: string | null;
}
