export const recordsData = [
  {
    no_expediente: 497938,
    fec_acuerdo_aseg: 'NULL',
    prevision: 'NULL',
    fec_prevision: 'NULL',
    articulo_validado: 'NULL',
    fec_fe_ministerial: 'NULL',
    acta_fe_ministerial: 'NULL',
    fec_dictamina: 'NULL',
    no_bateria: 'NULL',
    no_casillero: 'NULL',
    no_estante: 'NULL',
    no_juzgado: 'NULL',
    observaciones_prevision: 'NULL',
    insertado_por: 'DBAEZ',
    observaciones: 'NULL',
    metodo_insercion: 'CARGA MASIVA VOLANTES',
    fec_insercion: '2010-05-06',
    fec_recepcion_sera: 'NULL',
    causa_penal: 'NULL',
    averiguacion_previa: 'NULL',
    cve_amparo: 'NULL',
    cve_delito: 'NULL',
    acta_circunstanciada: 'NULL',
    cve_toca_penal: 'NULL',
    nombre_institucion: 'NUEVO CATALOGO',
    nombre_juzgado: 'NULL',
    nombre_mp: 'NULL',
    cve_guardavalor: 'NULL',
    nombre_indiciado: 'NO SE  INDICA',
    autoridad_ordena_dictamen: 'NULL',
    fec_notificacion: 'NULL',
    notificado_a: 'NULL',
    lugar_notificacion: 'NULL',
    fec_decomiso_dictaminacion: 'NULL',
    fec_devolucion_dictaminacion: 'NULL',
    fec_enajenacion: 'NULL',
    cve_entfed: 9,
    fec_recrev_dictaminacion: 'NULL',
    no_registro: 75104544,
    fec_destruccion: 'NULL',
    fec_donacion: 'NULL',
    fec_acuerdo_inicial: 'NULL',
    acuerdo_inicial: 'NULL',
    estatus_expediente: 'NULL',
    identificador: 'TRANS',
    es_delit: 'NULL',
    no_transferente: 120,
    no_exp_transferentes: 'CVM1100009/09   C',
    tipo_expediente: 'T',
    no_emisora: 115,
    no_autoridad: 38,
    fec_insercion_hc: '2010-05-06',
  },
  {
    no_expediente: 5676,
    fec_acuerdo_aseg: 'NULL',
    prevision: 'NULL',
    fec_prevision: 'NULL',
    articulo_validado: 'NULL',
    fec_fe_ministerial: 'NULL',
    acta_fe_ministerial: 'NULL',
    fec_dictamina: 'NULL',
    no_bateria: 'NULL',
    no_casillero: 'NULL',
    no_estante: 'NULL',
    no_juzgado: 266,
    observaciones_prevision: 'NULL',
    insertado_por: 'NULL',
    observaciones: 'NULL',
    metodo_insercion: 'MIGRACION DE DATOS',
    fec_insercion: '2000-09-03',
    fec_recepcion_sera: '2099-12-20',
    causa_penal: '193/99',
    averiguacion_previa: 'NULL',
    cve_amparo: 'NULL',
    cve_delito: 11,
    acta_circunstanciada: 'NULL',
    cve_toca_penal: 'NULL',
    nombre_institucion: 'JUZGADO DE DISTRITO',
    nombre_juzgado: 'JUZGADO DE DISTRITO',
    nombre_mp: 'N/A',
    cve_guardavalor: 'NULL',
    nombre_indiciado: 'AGUSTIN FRANCISCO SANCHEZ DE LA VEGA H.',
    autoridad_ordena_dictamen: 'NULL',
    fec_notificacion: 'NULL',
    notificado_a: 'NULL',
    lugar_notificacion: 'NULL',
    fec_decomiso_dictaminacion: 'NULL',
    fec_devolucion_dictaminacion: 'NULL',
    fec_enajenacion: 'NULL',
    cve_entfed: 9,
    fec_recrev_dictaminacion: 'NULL',
    no_registro: 72502,
    fec_destruccion: 'NULL',
    fec_donacion: 'NULL',
    fec_acuerdo_inicial: 'NULL',
    acuerdo_inicial: 'NULL',
    estatus_expediente: 'NULL',
    identificador: 'ASEG',
    es_delit: 'NULL',
    no_transferente: 3,
    no_exp_transferentes: 'NULL',
    tipo_expediente: 'A',
    no_emisora: 83,
    no_autoridad: 255,
    fec_insercion_hc: 'NULL',
  },
  {
    no_expediente: 5677,
    fec_acuerdo_aseg: 'NULL',
    prevision: 'NULL',
    fec_prevision: 'NULL',
    articulo_validado: 'NULL',
    fec_fe_ministerial: 'NULL',
    acta_fe_ministerial: 'NULL',
    fec_dictamina: 'NULL',
    no_bateria: 'NULL',
    no_casillero: 'NULL',
    no_estante: 'NULL',
    no_juzgado: 478,
    observaciones_prevision: 'NULL',
    insertado_por: 'NULL',
    observaciones: 'NULL',
    metodo_insercion: 'MIGRACION DE DATOS',
    fec_insercion: '2000-08-31',
    fec_recepcion_sera: '2099-12-13',
    causa_penal: '64/99',
    averiguacion_previa: 'NULL',
    cve_amparo: 'NULL',
    cve_delito: 'NULL',
    acta_circunstanciada: 'NULL',
    cve_toca_penal: 'NULL',
    nombre_institucion: 'PODER JUDICIAL DE LA FEDERACION',
    nombre_juzgado: '3? DE DTTO EN ACAPULCO, GRO',
    nombre_mp: 'NULL',
    cve_guardavalor: 'NULL',
    nombre_indiciado: 'MARIO GALEANA TEXTA',
    autoridad_ordena_dictamen: 'NULL',
    fec_notificacion: 'NULL',
    notificado_a: 'NULL',
    lugar_notificacion: 'NULL',
    fec_decomiso_dictaminacion: 'NULL',
    fec_devolucion_dictaminacion: 'NULL',
    fec_enajenacion: 'NULL',
    cve_entfed: 13,
    fec_recrev_dictaminacion: 'NULL',
    no_registro: 72503,
    fec_destruccion: 'NULL',
    fec_donacion: 'NULL',
    fec_acuerdo_inicial: 'NULL',
    acuerdo_inicial: 'NULL',
    estatus_expediente: 'NULL',
    identificador: 'ASEG',
    es_delit: 'NULL',
    no_transferente: 3,
    no_exp_transferentes: 'NULL',
    tipo_expediente: 'A',
    no_emisora: 83,
    no_autoridad: 7,
    fec_insercion_hc: 'NULL',
  },
  {
    no_expediente: 5678,
    fec_acuerdo_aseg: 'NULL',
    prevision: 'NULL',
    fec_prevision: 'NULL',
    articulo_validado: 4,
    fec_fe_ministerial: 'NULL',
    acta_fe_ministerial: 'NULL',
    fec_dictamina: 'NULL',
    no_bateria: 'NULL',
    no_casillero: 'NULL',
    no_estante: 'NULL',
    no_juzgado: 79,
    observaciones_prevision: 'NULL',
    insertado_por: 'NULL',
    observaciones: 'NULL',
    metodo_insercion: 'MIGRACION DE DATOS',
    fec_insercion: '2000-08-15',
    fec_recepcion_sera: '2000-03-14',
    causa_penal: '86/97',
    averiguacion_previa: '207/MPFEADS/97',
    cve_amparo: 'NULL',
    cve_delito: 554,
    acta_circunstanciada: 'NULL',
    cve_toca_penal: 'NULL',
    nombre_institucion: 'JUZGADO DE DISTRITO',
    nombre_juzgado: '11? DE DTO. M.P. DEL D.F.',
    nombre_mp:
      'DIR. GRAL. DE CONTROL Y REGISTRO DE ASEGURAMIENTOS MINISTERIALES',
    cve_guardavalor: 'NULL',
    nombre_indiciado: 'JESUS DANIEL NOVO',
    autoridad_ordena_dictamen: 'NULL',
    fec_notificacion: 'NULL',
    notificado_a: 'NULL',
    lugar_notificacion: 'NULL',
    fec_decomiso_dictaminacion: '1999-05-31',
    fec_devolucion_dictaminacion: 'NULL',
    fec_enajenacion: 'NULL',
    cve_entfed: 9,
    fec_recrev_dictaminacion: 'NULL',
    no_registro: 72504,
    fec_destruccion: 'NULL',
    fec_donacion: 'NULL',
    fec_acuerdo_inicial: 'NULL',
    acuerdo_inicial: 'NULL',
    estatus_expediente: 'NULL',
    identificador: 'ASEG',
    es_delit: 'NULL',
    no_transferente: 1,
    no_exp_transferentes: 'NULL',
    tipo_expediente: 'P',
    no_emisora: 37,
    no_autoridad: 24,
    fec_insercion_hc: 'NULL',
  },
  {
    no_expediente: 544772,
    fec_acuerdo_aseg: 'NULL',
    prevision: 'NULL',
    fec_prevision: 'NULL',
    articulo_validado: 'NULL',
    fec_fe_ministerial: 'NULL',
    acta_fe_ministerial: 'NULL',
    fec_dictamina: 'NULL',
    no_bateria: 'NULL',
    no_casillero: 'NULL',
    no_estante: 'NULL',
    no_juzgado: 'NULL',
    observaciones_prevision: 'NULL',
    insertado_por: 'NULL',
    observaciones: 'SE TRANSFIERE VEHICULO PARA VENTA, DONACION O DESTRUCCION.',
    metodo_insercion: 'NULL',
    fec_insercion: '2011-03-08',
    fec_recepcion_sera: 'NULL',
    causa_penal: 'NULL',
    averiguacion_previa: 'NULL',
    cve_amparo: 'NULL',
    cve_delito: 'NULL',
    acta_circunstanciada: 'NULL',
    cve_toca_penal: 'NULL',
    nombre_institucion: 'NUEVO CATALOGO',
    nombre_juzgado: 'NULL',
    nombre_mp: 'NULL',
    cve_guardavalor: 'NULL',
    nombre_indiciado: 'ERIK ARTURO LOPEZ MEZA',
    autoridad_ordena_dictamen: 'NULL',
    fec_notificacion: 'NULL',
    notificado_a: 'NULL',
    lugar_notificacion: 'NULL',
    fec_decomiso_dictaminacion: 'NULL',
    fec_devolucion_dictaminacion: 'NULL',
    fec_enajenacion: 'NULL',
    cve_entfed: 26,
    fec_recrev_dictaminacion: 'NULL',
    no_registro: 172748605,
    fec_destruccion: 'NULL',
    fec_donacion: 'NULL',
    fec_acuerdo_inicial: 'NULL',
    acuerdo_inicial: 'NULL',
    estatus_expediente: 'NULL',
    identificador: 'TRANS',
    es_delit: 'NULL',
    no_transferente: 120,
    no_exp_transferentes: 'AOCE501100187',
    tipo_expediente: 'T',
    no_emisora: 114,
    no_autoridad: 40,
    fec_insercion_hc: '2011-03-08',
  },
  {
    no_expediente: 5680,
    fec_acuerdo_aseg: 'NULL',
    prevision: 'NULL',
    fec_prevision: 'NULL',
    articulo_validado: 'NULL',
    fec_fe_ministerial: 'NULL',
    acta_fe_ministerial: 'NULL',
    fec_dictamina: 'NULL',
    no_bateria: 'NULL',
    no_casillero: 'NULL',
    no_estante: 'NULL',
    no_juzgado: 246,
    observaciones_prevision: 'NULL',
    insertado_por: 'NULL',
    observaciones: 'NULL',
    metodo_insercion: 'MIGRACION DE DATOS',
    fec_insercion: '2000-08-15',
    fec_recepcion_sera: '2000-03-15',
    causa_penal: '76/91',
    averiguacion_previa: 'NULL',
    cve_amparo: 'NULL',
    cve_delito: 1,
    acta_circunstanciada: 'NULL',
    cve_toca_penal: 'NULL',
    nombre_institucion: 'PODER JUDICIAL DE LA FEDERACION',
    nombre_juzgado: '6? DE DTTO. EN MICHOACAN',
    nombre_mp: 'NULL',
    cve_guardavalor: 'NULL',
    nombre_indiciado: 'JESUS CHAPA HERNANDEZ',
    autoridad_ordena_dictamen: 'NULL',
    fec_notificacion: 'NULL',
    notificado_a: 'NULL',
    lugar_notificacion: 'NULL',
    fec_decomiso_dictaminacion: 'NULL',
    fec_devolucion_dictaminacion: 'NULL',
    fec_enajenacion: 'NULL',
    cve_entfed: 16,
    fec_recrev_dictaminacion: 'NULL',
    no_registro: 72506,
    fec_destruccion: 'NULL',
    fec_donacion: 'NULL',
    fec_acuerdo_inicial: 'NULL',
    acuerdo_inicial: 'NULL',
    estatus_expediente: 'NULL',
    identificador: 'ASEG',
    es_delit: 'NULL',
    no_transferente: 3,
    no_exp_transferentes: 'NULL',
    tipo_expediente: 'A',
    no_emisora: 83,
    no_autoridad: 410,
    fec_insercion_hc: 'NULL',
  },
  {
    no_expediente: 544778,
    fec_acuerdo_aseg: 'NULL',
    prevision: 'NULL',
    fec_prevision: 'NULL',
    articulo_validado: 'NULL',
    fec_fe_ministerial: 'NULL',
    acta_fe_ministerial: 'NULL',
    fec_dictamina: 'NULL',
    no_bateria: 'NULL',
    no_casillero: 'NULL',
    no_estante: 'NULL',
    no_juzgado: 'NULL',
    observaciones_prevision: 'NULL',
    insertado_por: 'NULL',
    observaciones: 'SE TRANSFIERE VEHICULO PARA VENTA, DONACION O DESTRUCCION.',
    metodo_insercion: 'NULL',
    fec_insercion: '2011-03-08',
    fec_recepcion_sera: 'NULL',
    causa_penal: 'NULL',
    averiguacion_previa: 'NULL',
    cve_amparo: 'NULL',
    cve_delito: 'NULL',
    acta_circunstanciada: 'NULL',
    cve_toca_penal: 'NULL',
    nombre_institucion: 'NUEVO CATALOGO',
    nombre_juzgado: 'NULL',
    nombre_mp: 'NULL',
    cve_guardavalor: 'NULL',
    nombre_indiciado: 'APOLINAR JIMENEZ HERNANDEZ',
    autoridad_ordena_dictamen: 'NULL',
    fec_notificacion: 'NULL',
    notificado_a: 'NULL',
    lugar_notificacion: 'NULL',
    fec_decomiso_dictaminacion: 'NULL',
    fec_devolucion_dictaminacion: 'NULL',
    fec_enajenacion: 'NULL',
    cve_entfed: 26,
    fec_recrev_dictaminacion: 'NULL',
    no_registro: 172748666,
    fec_destruccion: 'NULL',
    fec_donacion: 'NULL',
    fec_acuerdo_inicial: 'NULL',
    acuerdo_inicial: 'NULL',
    estatus_expediente: 'NULL',
    identificador: 'TRANS',
    es_delit: 'NULL',
    no_transferente: 120,
    no_exp_transferentes: 'AOCE501100188',
    tipo_expediente: 'T',
    no_emisora: 114,
    no_autoridad: 40,
    fec_insercion_hc: '2011-03-08',
  },
  {
    no_expediente: 497939,
    fec_acuerdo_aseg: 'NULL',
    prevision: 'NULL',
    fec_prevision: 'NULL',
    articulo_validado: 'NULL',
    fec_fe_ministerial: 'NULL',
    acta_fe_ministerial: 'NULL',
    fec_dictamina: 'NULL',
    no_bateria: 'NULL',
    no_casillero: 'NULL',
    no_estante: 'NULL',
    no_juzgado: 'NULL',
    observaciones_prevision: 'NULL',
    insertado_por: 'DBAEZ',
    observaciones: 'NULL',
    metodo_insercion: 'CARGA MASIVA VOLANTES',
    fec_insercion: '2010-05-06',
    fec_recepcion_sera: 'NULL',
    causa_penal: 'NULL',
    averiguacion_previa: 'NULL',
    cve_amparo: 'NULL',
    cve_delito: 'NULL',
    acta_circunstanciada: 'NULL',
    cve_toca_penal: 'NULL',
    nombre_institucion: 'NUEVO CATALOGO',
    nombre_juzgado: 'NULL',
    nombre_mp: 'NULL',
    cve_guardavalor: 'NULL',
    nombre_indiciado: 'NO SE  INDICA',
    autoridad_ordena_dictamen: 'NULL',
    fec_notificacion: 'NULL',
    notificado_a: 'NULL',
    lugar_notificacion: 'NULL',
    fec_decomiso_dictaminacion: 'NULL',
    fec_devolucion_dictaminacion: 'NULL',
    fec_enajenacion: 'NULL',
    cve_entfed: 9,
    fec_recrev_dictaminacion: 'NULL',
    no_registro: 75104553,
    fec_destruccion: 'NULL',
    fec_donacion: 'NULL',
    fec_acuerdo_inicial: 'NULL',
    acuerdo_inicial: 'NULL',
    estatus_expediente: 'NULL',
    identificador: 'TRANS',
    es_delit: 'NULL',
    no_transferente: 120,
    no_exp_transferentes: 'CCP1100014/02   C',
    tipo_expediente: 'T',
    no_emisora: 115,
    no_autoridad: 38,
    fec_insercion_hc: '2010-05-06',
  },
  {
    no_expediente: 497940,
    fec_acuerdo_aseg: 'NULL',
    prevision: 'NULL',
    fec_prevision: 'NULL',
    articulo_validado: 'NULL',
    fec_fe_ministerial: 'NULL',
    acta_fe_ministerial: 'NULL',
    fec_dictamina: 'NULL',
    no_bateria: 'NULL',
    no_casillero: 'NULL',
    no_estante: 'NULL',
    no_juzgado: 'NULL',
    observaciones_prevision: 'NULL',
    insertado_por: 'DBAEZ',
    observaciones: 'NULL',
    metodo_insercion: 'CARGA MASIVA VOLANTES',
    fec_insercion: '2010-05-06',
    fec_recepcion_sera: 'NULL',
    causa_penal: 'NULL',
    averiguacion_previa: 'NULL',
    cve_amparo: 'NULL',
    cve_delito: 'NULL',
    acta_circunstanciada: 'NULL',
    cve_toca_penal: 'NULL',
    nombre_institucion: 'NUEVO CATALOGO',
    nombre_juzgado: 'NULL',
    nombre_mp: 'NULL',
    cve_guardavalor: 'NULL',
    nombre_indiciado: 'NO SE  INDICA',
    autoridad_ordena_dictamen: 'NULL',
    fec_notificacion: 'NULL',
    notificado_a: 'NULL',
    lugar_notificacion: 'NULL',
    fec_decomiso_dictaminacion: 'NULL',
    fec_devolucion_dictaminacion: 'NULL',
    fec_enajenacion: 'NULL',
    cve_entfed: 9,
    fec_recrev_dictaminacion: 'NULL',
    no_registro: 75104562,
    fec_destruccion: 'NULL',
    fec_donacion: 'NULL',
    fec_acuerdo_inicial: 'NULL',
    acuerdo_inicial: 'NULL',
    estatus_expediente: 'NULL',
    identificador: 'TRANS',
    es_delit: 'NULL',
    no_transferente: 120,
    no_exp_transferentes: 'CVM1100001/09   C',
    tipo_expediente: 'T',
    no_emisora: 115,
    no_autoridad: 38,
    fec_insercion_hc: '2010-05-06',
  },
  {
    no_expediente: 497941,
    fec_acuerdo_aseg: 'NULL',
    prevision: 'NULL',
    fec_prevision: 'NULL',
    articulo_validado: 'NULL',
    fec_fe_ministerial: 'NULL',
    acta_fe_ministerial: 'NULL',
    fec_dictamina: 'NULL',
    no_bateria: 'NULL',
    no_casillero: 'NULL',
    no_estante: 'NULL',
    no_juzgado: 'NULL',
    observaciones_prevision: 'NULL',
    insertado_por: 'DBAEZ',
    observaciones: 'NULL',
    metodo_insercion: 'CARGA MASIVA VOLANTES',
    fec_insercion: '2010-05-06',
    fec_recepcion_sera: 'NULL',
    causa_penal: 'NULL',
    averiguacion_previa: 'NULL',
    cve_amparo: 'NULL',
    cve_delito: 'NULL',
    acta_circunstanciada: 'NULL',
    cve_toca_penal: 'NULL',
    nombre_institucion: 'NUEVO CATALOGO',
    nombre_juzgado: 'NULL',
    nombre_mp: 'NULL',
    cve_guardavalor: 'NULL',
    nombre_indiciado: 'NO SE  INDICA',
    autoridad_ordena_dictamen: 'NULL',
    fec_notificacion: 'NULL',
    notificado_a: 'NULL',
    lugar_notificacion: 'NULL',
    fec_decomiso_dictaminacion: 'NULL',
    fec_devolucion_dictaminacion: 'NULL',
    fec_enajenacion: 'NULL',
    cve_entfed: 9,
    fec_recrev_dictaminacion: 'NULL',
    no_registro: 75104571,
    fec_destruccion: 'NULL',
    fec_donacion: 'NULL',
    fec_acuerdo_inicial: 'NULL',
    acuerdo_inicial: 'NULL',
    estatus_expediente: 'NULL',
    identificador: 'TRANS',
    es_delit: 'NULL',
    no_transferente: 120,
    no_exp_transferentes: '10/2000   C',
    tipo_expediente: 'T',
    no_emisora: 115,
    no_autoridad: 38,
    fec_insercion_hc: '2010-05-06',
  },
];
