export const EventStadisticsDefaultValue = {
  des_bienes: 0,
  des_cant: 0,
  des_salida: 0,
  des_total: 0,
  lotes_des: 0,
  lotes_pag: 0,
  lotes_penal: 0,
  num_bienes: 0,
  num_lotes: 0,
  pag_bienes: 0,
  pag_cant: 0,
  pag_salida: 0,
  pag_total: 0,
  pen_bienes: 0,
  pen_cant: 0,
  pen_salida: 0,
  pen_total: 0,
  tot_base: 0,
  tot_cant: 0,
};
