import { IDictation } from 'src/app/core/models/ms-dictation/dictation-model';
import { IDictationXGood1 } from 'src/app/core/models/ms-dictation/dictation-x-good1.model';
import { IOfficialDictation2 } from 'src/app/core/models/ms-dictation/official-dictation.model';
import { IMJobManagement } from 'src/app/core/models/ms-officemanagement/m-job-management.model';

export const IDictationTemp: IDictation = {
  id: null,
  passOfficeArmy: null,
  expedientNumber: null,
  typeDict: null,
  statusDict: null,
  dictDate: null,
  userDict: null,
  observations: null,
  delegationDictNumber: null,
  areaDict: null,
  instructorDate: null,
  registerNumber: null,
  esDelit: null,
  wheelNumber: null,
  keyArmyNumber: null,
  notifyAssuranceDate: null,
  resolutionDate: null,
  notifyResolutionDate: null,
  folioUniversal: null,
  entryDate: null,
  dictHcDAte: null,
  entryHcDate: null,
};

export const IOficialDictationTemp: IOfficialDictation2 = {
  officialNumber: null,
  typeDict: null,
  sender: null,
  city: null,
  text1: null,
  text2: null,
  recipient: null,
  registerNumber: null,
  delegacionRecipientNumber: null,
  recipientDepartmentNumber: null,
  statusOf: null,
  recipientEsxt: null,
  desSenderPa: null,
  text3: null,
  text2To: null,
  notaryNumber: null,
  cveChargeRem: null,
};

export const IDictationXGood1Temp: IDictationXGood1 = {
  ofDictNumber: null,
  proceedingsNumber: null,
  id: null,
  descriptionDict: null,
  amountDict: null,
  registerNumber: null,
  typeDict: null,
  proceedings: null,
  good: null,
  dictation: null,
};

export const IMJobManagementTemp: IMJobManagement = {
  flyerNumber: null,
  proceedingsNumber: null,
  cveManagement: null,
  managementNumber: null,
  sender: null,
  delRemNumber: null,
  depRemNumber: null,
  addressee: null,
  city: null,
  text1: null,
  text2: null,
  statusOf: null,
  insertUser: null,
  areaUser: null,
  deleUser: null,
  insertDate: null,
  jobType: null,
  nomPersExt: null,
  refersTo: null,
  jobBy: null,
  recordNumber: null,
  armedKeyNumber: null,
  desSenderpa: null,
  text3: null,
  insertHcDate: null,
  projectDate: null,
  description: null,
  problematiclegal: null,
  cveChargeRem: null,
  justification: null,
};

export const Documents: any = [
  {
    key: '28',
    description: 'Fecha de Resolucion',
    typeDictum: 'ABANDONO',
    numRegister: '8871642',
    nbOrigin: null,
  },
  {
    key: '27',
    description: 'Fecha Notificacion',
    typeDictum: 'ABANDONO',
    numRegister: '8871641',
    nbOrigin: null,
  },
  {
    key: '26',
    description: 'Notificacion Acuerdo Aseguramiento',
    typeDictum: 'ABANDONO',
    numRegister: '8871640',
    nbOrigin: null,
  },
  {
    key: '25',
    description: 'Fecha Acuerdo de Aseguramiento',
    typeDictum: 'ABANDONO',
    numRegister: '8871639',
    nbOrigin: null,
  },
];
