  brayan-develop[m
  develop[m
  digitalizacion-23-03[m
  documents-corrections[m
  documents-reception[m
  feat/goods-capture-integration[m
  feat/jasper-reports-preview[m
  feat/marketing-records[m
  feat/pgr-documents[m
* [32mfeat/sat-documents[m
  feat/system-log[m
  feat/valid-statuses[m
  feature/clasification-good-expedient[m
  feature/show-images-from-base64[m
  goods-capture-no-volante[m
  indicators-history[m
  scan-documents[m
  tiff-images[m
  turnar-replicar[m
  work-mailbox-historicals[m
