export interface IComerProvider {
  providerId?: number;
  nameReason: string;
  rfc: string;
  street: string;
  clkedo: string;
  colony: string;
  clkmun: string;
  cityDesc: string;
  clkCountry: number;
  stateDesc: string;
  delegation?: string;
  fax?: string;
  commission?: number;
  phone?: string;
  curp: string;
  typePerson?: string;
  preponderantAct?: string;
  cp?: string | number;
  contractNo?: string;
  esCustomer?: string;
  bank?: string;
  branch?: string;
  checkingCta?: string;
  key?: string;
  userCreation?: string;
  formPayment?: string;
  webMail?: string;
  customerId?: number;
  references?: string;
  customer?: string;
}
