export const ASSIGNMENT = [
  {
    id: 1,
    title: 'Nuevo Registro de asignacion',
    noRequest: 45009,
    numTask: 260301,
    noInstance: 820169,
    created: 'tester_nsbxt',
    process: 'nuevo asignacion',
  },
  {
    id: 2,
    title: 'Elaborar Solicitud a responsable del estudio',
    noRequest: 45239,
    numTask: 261131,
    noInstance: 82411,
    created: 'tester_nsbxt',
    process: 'ElaborarSolicitud',
  },
  {
    id: 3,
    title: 'Guardar respuesta de la responsable del estudio',
    noRequest: 45539,
    numTask: 261221,
    noInstance: 82781,
    created: 'tester_nsbxt',
    process: 'GuardarRespuesta',
  },
  {
    id: 4,
    title: 'Estudio pendiente de la programacion',
    noRequest: 45539,
    numTask: 261221,
    noInstance: 82781,
    created: 'tester_nsbxt',
    process: 'ProgramarEntrega',
  },
  {
    id: 4,
    title: 'Programación pendiente de autorización',
    noRequest: 45539,
    numTask: 261221,
    noInstance: 82781,
    created: 'tester_nsbxt',
    process: 'DictaminarBienes',
  },
];
