DECLARE
	TOT NUMBER;	
	FCAMBIO DATE;
BEGIN
	-- CUENTA LAS VECES QUE HA SIDO CONVERTIDO A NUMERARIO
	SELECT COUNT(0)INTO TOT
	  FROM BIENES
	 WHERE NO_BIEN_REFERENCIA = :BIENES.NO_BIEN;
	 
	-- OBTEN LA FECHA EN QUE CAMBIO A NUMERARIO
  BEGIN 
	  --LIP_MENSAJE('D1: '||:BIENES1.NO_BIEN,'A');
	  SELECT FEC_CAMBIO INTO :BLK_CTR.FEC_CAMBIO
	    FROM CAMBIO_NUMERARIO
     WHERE NO_BIEN_ORIGINAL  = :BIENES.NO_BIEN
       AND NO_BIEN_NUMERARIO = :BIENES1.NO_BIEN;
	EXCEPTION
		WHEN NO_DATA_FOUND THEN
		  -- EN CASO DE QUE NO SE INDIQUE EN LA TABLA, BUSCA EN EL HISTORICO
	    BEGIN
		    --LIP_MENSAJE('D2 '||:BIENES1.NO_BIEN,'A');
	      SELECT FECHA_CAMBIO INTO :BLK_CTR.FEC_CAMBIO
	        FROM HISTORICO_NUMERARIOS
         WHERE BIEN_ORIGINAL     = :BIENES.NO_BIEN
           AND NO_BIEN_NUMERARIO = :BIENES1.NO_BIEN;
		  EXCEPTION 
		  	WHEN NO_DATA_FOUND THEN
		  	    --LIP_MENSAJE('D3 '||:BIENES1.NO_BIEN,'A');
		  	   :BLK_CTR.FEC_CAMBIO := NULL;
		  END;
	END;
	
	-- RAZON DEL CAMBIO A NUMERARIO
	BEGIN 
    SELECT MOTIVO 
      INTO :BLK_CTR.MOTIVO
      FROM HISTORICO_NUMERARIOS
     WHERE BIEN_ORIGINAL = :BIENES.NO_BIEN
       AND NO_BIEN_NUMERARIO = :BIENES1.NO_BIEN;
    SET_ITEM_PROPERTY('BLK_CTR.MOTIVO',VISIBLE,PROPERTY_TRUE);
	EXCEPTION 
		WHEN OTHERS THEN 
		  SET_ITEM_PROPERTY('BLK_CTR.MOTIVO',VISIBLE,PROPERTY_FALSE);
	END;
	
	
	 --lip_mensaje(tot,'a');
	 
	 :BIENES1.CONT_CONV := TOT;
	 :BLK_CTR.T_TOTAL  := :BIENES1.VAL2  - :BIENES1.VAL13 - NVL(:BIENES1.VAL10,0);
	 IF TOT = 0 THEN
	 	 SET_ITEM_PROPERTY('BIENES1.CONT_CONV',VISIBLE,PROPERTY_FALSE);
	 ELSE 
	 	 SET_ITEM_PROPERTY('BIENES1.CONT_CONV',VISIBLE,PROPERTY_TRUE);
	 END IF;
	 
	 
	 
	 IF NVL(:BIENES1.VAL15,0) = 0 THEN
	 	 SET_ITEM_PROPERTY('BIENES1.VAL15',VISIBLE,PROPERTY_FALSE);
	 	 SET_ITEM_PROPERTY('BIENES1.VAL15',ENABLED,PROPERTY_FALSE);
	 	 SET_ITEM_PROPERTY('BLK_CTR.T_TOTAL',POSITION,361,260);
	 	 SET_ITEM_PROPERTY('BLK_CTR.PB_ALIF',ENABLED,PROPERTY_TRUE);
	 	 SET_ITEM_PROPERTY('BLK_CTR.PB_RVLIF',ENABLED,PROPERTY_FALSE);
	 ELSE
	 	 SET_ITEM_PROPERTY('BIENES1.VAL15',VISIBLE,PROPERTY_TRUE);
	 	 SET_ITEM_PROPERTY('BIENES1.VAL15',ENABLED,PROPERTY_TRUE);
	 	 SET_ITEM_PROPERTY('BLK_CTR.PB_ALIF',ENABLED,PROPERTY_FALSE);
	   SET_ITEM_PROPERTY('BLK_CTR.PB_RVLIF',ENABLED,PROPERTY_TRUE);
	   SET_ITEM_PROPERTY('BLK_CTR.T_TOTAL',POSITION,361,279);
	 END IF;	 
	 EXCEPTION 
	 	WHEN OTHERS THEN
	 	  LIP_MENSAJE('Err. PQ: '||SQLERRM,'S');	 	
END;