import { Injectable } from '@angular/core';
import { FileUpdateCommunicationService } from 'src/app/pages/juridical-processes/file-data-update/services/file-update-communication.service';

@Injectable({
  providedIn: 'root',
})
export class RelatedDocumentsService {
  constructor(
    private svFileUpdateCommunicationService: FileUpdateCommunicationService
  ) {}

  getParams(opcion: string): any {
    if (opcion == '1') {
      return this.svFileUpdateCommunicationService
        .juridicalDocumentManagementParams;
    } else if (opcion == '2') {
      return this.svFileUpdateCommunicationService
        .juridicalRelatedDocumentManagementParams;
    } else {
      return false;
    }
  }

  changeTextType(textType: string, cve_oficio_externo: string) {
    let text1: string = '';
    let text2: string = '';
    if (textType == 'UNO') {
      text1 = `Me refiero a su oficio ${cve_oficio_externo}, dirigido al Servicio de Administración de Bienes Asegurados, mediante el cual informa que __ de la causa penal citada al rubro. Al respecto, le informo que con fecha 17 de junio del año en curso entraron en vigor diversas adiciones al Código Federal de Procedimientos Penales, así como la Ley Federal para la Administración y Enajenación de Bienes del Sector Público, misma que abrogó la Ley federal para la Administración de Bienes Asegurados, Decomisados y Abandonados.`;
      text2 = `Al respecto, este Servicio de Administración de Bienes acusa de recibo el oficio de referencia, quedando enterados de su contenido, e informando que dichos bienes no fueron recibidos ni son administrados por este Servicio de Administración.`;
    } else if (textType == 'DOS') {
      text1 = `Me refiero a su oficio número ${cve_oficio_externo}, mediante el cual ordena al Servicio de Administración de Bienes Asegurados, la devolución del numerario__________, a favor de ___________. Al respecto, hacemos de su conocimiento que como consecuencia de la abrogación de la Ley Federal para la Administración de Bienes Asegurados, Decomisados y Abandonados; y la consecuente entrada en vigor el día 17 de junio del año en curso de la Ley Federal para la Administración y Enajenación de Bienes del Sector Público, así como de las adiciones efectuadas al Código Federal de Procedimientos Penales, le solicito sea remitida copia certificada de la siguiente documentación:`;
      text2 = `Lo anterior, de conformidad con lo establecido por los artículos 6 y 24 de La Ley Federal para la Administración y Enajenación de Bienes del Sector Público; artículos 28 último párrafo, 182-A y 182-Ñ del Código Federal de Procedimientos Penales. Adicionalmente le solicito se sirva remitir en el momento oportuno la constancia antes aludida; no omitiendo manifestarle que esta área jurídica dictaminó como procedente la recepción del numerario afecto mediante el diverso OFICINAS CENTRALES DEJDF/DEJDF/_______/2003.`;
    } else if (textType == 'TRES') {
      text1 = `Me refiero a su oficio número ${cve_oficio_externo}, dirigido al Director General del Servicio de Administración de Bienes Asegurados, mediante el cual pone a disposición el _________________________________, afecto a la averiguación previa citada al rubro. Al respecto, hacemos de su conocimiento que como consecuencia de la abrogación de la Ley Federal para la Administración de Bienes Asegurados, Decomisados y Abandonados; y la consecuente entrada en vigor el día 17 de junio del año en curso de la Ley Federal para la Administración y Enajenación de Bienes del Sector Público, así como de las adiciones efectuadas al Código Federal de Procedimientos Penales, le solicito sea remitida copia certificada de la siguiente documentación:`;
      text2 = `Lo anterior, de conformidad con lo establecido por los artículos 6, 182 y 182-A de La Ley Federal para la Administración y Enajenación de Bienes del Sector Público y del Código Federal de Procedimientos Penales, respectivamente.`;
    } else if (textType == 'CUATRO') {
      text1 = `Me refiero a su oficio número ${cve_oficio_externo}, mediante el cual informa al Servicio de Administración de Bienes Asegurados el aseguramiento del numerario consistente en_____________________, afectos a la causa penal citada al rubro. Al respecto, hacemos de su conocimiento que como consecuencia de la abrogación de la Ley Federal para la Administración de Bienes Asegurados, Decomisados y Abandonados; y la consecuente entrada en vigor el día 17 de junio del año en curso de la Ley Federal para la Administración y Enajenación de Bienes del Sector Público, así como de las adiciones efectuadas al Código Federal de Procedimientos Penales, le solicito sea remitida copia certificada de la siguiente documentación:`;
      text2 = `Lo anterior, de conformidad con  lo establecido por los artículos 6, 182-A y 182-G de la Ley Federal para la Administración y Enajenación de Bienes del Sector Público y del Código Federal de Procedmientos Penales, respectivamente.`;
    } else if (textType == 'CINCO') {
      text1 = `Me refiero al oficio número ${cve_oficio_externo} mediante el cual pone a disposición de este Servicio de Administración y Enajenación de Bienes la mercancía que a continuación se detalla, la cual señala ha pasado a propiedad del Fisco Federal por abandono tácito en términos de lo dispuesto por el artículo 29, fracción II y 32 de la Ley Aduanera.`;
      text2 = `Al respecto, le informo que para que este Servicio de Administración esté en posibilidad de proceder de acuerdo a sus atribuciones, es necesario aclare la descripción de los bienes objeto de la transferencia, toda vez que el oficio de puesta a disposición indica _________ lo anterior, a efecto de que este Servicio de Administración esté en posibilidad proceder de acuerdo a sus atribuciones. Por las atenciones que se sirva dar al presente, le reitero mi más atenta consideración.`;
    } else if (textType == 'SEIS') {
      text1 = `Me refiero al oficio número ${cve_oficio_externo} mediante los cuales transfiere para su _______ por parte de este Organismo Descentralizado los bienes que "se encuentran en el domicilio del contribuyente ____________________ los cuales indica fueron puestos a disposición de esa Autoridad Recaudadora como resultado de un Procedimiento Administrativo de Ejecución. Al respecto, le informo que para que este Servicio de Administración esté en posibilidad de proceder de acuerdo a sus atribuciones, es necesario remita copia certificada la siguiente documentación:`;
      text2 = `Lo anterior, a efecto de integrar debidamente el expediente administrativo que se lleva en este Organismo Descentralizado. Por las atenciones que se sirva dar al presente, le reitero mi más atenta consideración.`;
    } else if (textType == 'SIETE') {
      text1 = `Me refiero a sus oficios 326-SAT-01-711-1.2.1 0 453, 455, 458, 460, 461, 463 y 464 dirigidos al Director General de este Servicio de Administración  y Enajenación de Bienes, mediante los cuales informa que con fundamento en los artículos 1 fracción VI, 3, 6 bis, 6 ter y 6 quarter de la Ley Federal para la Administración y Enajenación de Bienes del Sector Público y de conformidad con el Acuerdo publicado el 23 de febrero de 2005 en el Diario Oficial de la Federación, transfiere diversos bienes que pasaron a propiedad del Fisco Federal por medio de la figura del abandono tácito. Por lo que concierne a cada uno de los bienes señalados en dichos oficios, se manifiesta que si esa área considera que los mismos se encuentran dentro de las hipótesis previstas en los artículos 2, fracción III, y 5, de la Ley Federal para la Administración y Enajenación de Bienes del Sector Público, así como 17, de su Reglamento, entonces, este Organismo Descentralizado sugiere, atentamente, la aplicación de los señalados preceptos jurídicos. En consecuencia, este Servicio de Administración no sería competente para llevar a cabo la administración de los bienes en cuestión, toda vez que, tomando en cuenta su cuantía intrínseca, se estima que cada uno tiene un valor inferior al de referencia. Aunado al razonamiento anterior, también se consideran los costos que se generarían por concepto de su traslado, así como por la ejecución del destino que se determine. Ahora bien, en caso de que esa Administración considere que los bienes en cuestión no se encuentran dentro de las hipótesis previstas en los citados artículos, se informa, con base en el precepto jurídico 6 bis y el artículo tercero transitorio, de la mencionada Ley Federal, que la transferencia de los mismos deberá cumplir con los lineamientos que emita la Junta de Gobierno de este Organismo, en virtud de que a la fecha de entrada en vigor del artículo 6 bis y del tercero transitorio (24 de febrero de 2005), los referidos bienes se encontraban y se encuentran bajo administración y custodia de esa Aduana, a su cargo.`;
      text2 = null;
    } else if (textType == 'OCHO') {
      text1 = `En estricto cumplimiento al artículo 182-A del Código Federal de Procedimientos Penales, así como a los preceptos legales 5 y 6 del Reglamento de la Ley Federal para la Administración y Enajenación de Bienes del Sector Público y toda vez que por auto de fecha __________________________________dictado por ese H. Juzgado de Distrito se ordenó notificar al indiciado el acuerdo de aseguramiento en los términos establecidos en el precepto legal aludido, en tal sentido empezó a transcurrir el término legal para reclamar el referido numerario el cual corrió a partir _________________razón por la cual la ____________), al día de hoy se encuentra abandonada. /n/n A mayor abundamiento, se advierte que mediante proveído de fecha () ese H. Juzgado de Distrito acordó que el numerario queda a su disposición hasta el momento de resolver sobre su destino final; sin embargo el artículo 182-A del Código Adjetivo de la Materia y Fuero otorga un término perentorio al interesado o a su representante legal para reclamar el bien asegurado y una vez que haya transcurrido dicho plazo y en el supuesto de que no haya existido reclamación alguna, el bien por efectos jurídicos de Ley causa abandono a favor del Gobierno Federal, restando emitir la declaración de abandono por esta Autoridad Administrativa competente para ello.`;
      text2 = `En esas condiciones, le solicitamos nos informe si el interesado o su representante legal han hecho manifestación alguna respecto de las cantidades en mención; además nos indique si dicho numerario se considera necesario para la substanciación del procedimiento penal federal. /n/n Finalmente y una vez que ese H. Juzgado de Distrito se pronuncie sobre el presente oficio, el Servicio de Administración y Enajenación de Bienes procederá conforme a sus atribuciones a emitir la declaración de abandono, para que corra agregada en el proceso penal federal y se actualice el supuesto normativo del artículo 182-Q del Código Adjetivo de la Materia y Fuero.`;
    }
    return { text1: text1, text2: text2 };
  }
}
