export class IRegionalDelegation {
  // id: number | null;
  // description: string;
  // registerNumber: number | null;
  // idEntity: number | null;
  // creationUser: string;
  // creationDate: Date;
  // editionUser: string;
  // modificationDate: Date;
  // idGeographicZona: number | null;
  // version: number | null;
  // regionalDelegate: string;
  // officeAddress: string;
  // status: number | null;
  // keyZone: string;
  // iva: number | null;
  // city: string;
  // keyState: string;
  id: number | null;
  description: string;
  registerNumber: number | null;
  idGeographicZona: number | null;
  version: number | null;
  regionalDelegate: string;
  officeAddress: string;
  status: number | null;
  keyZone: string;
  iva: number | null;
  city: string;
  keyState: string;
}
