export interface ITempExpedient {
  id: number;
  courtNumber: number | null;
  observations: string;
  insertionDate: Date | string;
  // criminalCase: string;
  causePenal: string;
  // preliminaryInquiry: string;
  ascertainmentPrevious: string;
  // protectionKey: string;
  cveProtection: string;
  // crimeKey: string;
  cveCrime: string;
  // circumstantialRecord: string;
  recordCircumstanced: string;
  // keyPenalty: string;
  cvetouchPenal: string;
  // indicatedName: string;
  nameIndexed: string;
  // federalEntityKey: string;
  cveEntfed: string;
  identifier: string;
  // transferNumber: number;
  // expTransferNumber: string;
  transfereeNumber: number;
  expTransferorsNumber: string;
  // expedientType: string;
  proceedingsType: string;
  stationNumber: number | null;
  authorityNumber: number | null;
  // subject: string;
  affair: string;
  // noSubjectSij: number | null;
  affairSijNumber: number;
  // typeTranssact: number | null;
  procedureType: number;
  // noOffice: string | null;
  jobNumber: string;
  //
  agreementSecureDate?: Date;
  forecast?: string;
  forecastDate?: Date;
  articleValidated?: string;
  faithMinisterialDate?: Date;
  recordFaithMinisterial?: string;
  dictamineDate?: Date;
  batteryNumber?: number;
  lockerNumber?: number;
  shelfNumber?: number;
  observationsForecast?: string;
  insertedBy?: string;
  methodInsertion?: string;
  receptionSeraDate?: Date;
  institutionName?: string;
  courtName?: string;
  nameMp?: string;
  cveguardavalor?: string;
  authorityOrderOpinion?: string;
  notificationDate?: Date;
  notifiedTo?: string;
  placeNotification?: string;
  forfeitureRulingDate?: Date;
  returnRulingDate?: Date;
  alienationDate?: Date;
  recrevRulingDate?: Date;
  recordNumber?: number;
  destructionDate?: Date;
  donationDate?: Date;
  agreementInitialDate?: Date;
  agreementInitial?: string;
  statusProceedings?: string;
  isCrime?: string;
  insertionHcDate?: Date;
}
