export const NOTIFICATION_ASSOCIATION_COLUMNS = {
  noVolante: {
    title: 'No. Volante',
    sort: false,
  },
  identifica: {
    title: 'Identifica',
    sort: false,
  },
  tipoVolante: {
    title: 'Tipo Volante',
    sort: false,
  },
  asunto: {
    title: 'Asunto',
    sort: false,
  },
  fecCaptura: {
    title: 'Fec. Captura',
    sort: false,
  },
  cveAmparo: {
    title: 'CVE Amparo',
    sort: false,
  },
  averPrevia: {
    title: 'Averiguación Previa',
    sort: false,
  },
  causaPenal: {
    title: 'Causa Penal',
    sort: false,
  },
  noExpediente: {
    title: 'No. Expediente',
    sort: false,
  },
};

export const NOTIFICATION_ASSOCIATION_EXAMPLE_DATA = [
  {
    noVolante: 123456,
    identifica: 'ASEG',
    tipoVolante: 'P',
    asunto: 'Lorem ipsum dolor sit amet consectetur adipisicing elit',
    fecCaptura: new Date().toISOString(),
    cveAmparo: '',
    averPrevia: 'ASFD/DFAD',
    causaPenal: 'DFS',
    noExpediente: '123',
  },
  {
    noVolante: 123456,
    identifica: 'ASEG',
    tipoVolante: 'P',
    asunto: 'Lorem ipsum dolor sit amet consectetur adipisicing elit',
    fecCaptura: new Date().toISOString(),
    cveAmparo: '',
    averPrevia: 'ASFD/DFAD',
    causaPenal: 'DFS',
    noExpediente: '123',
  },
  {
    noVolante: 123456,
    identifica: 'ASEG',
    tipoVolante: 'P',
    asunto: 'Lorem ipsum dolor sit amet consectetur adipisicing elit',
    fecCaptura: new Date().toISOString(),
    cveAmparo: '',
    averPrevia: 'ASFD/DFAD',
    causaPenal: 'DFS',
    noExpediente: '123',
  },
  {
    noVolante: 123456,
    identifica: 'ASEG',
    tipoVolante: 'P',
    asunto: 'Lorem ipsum dolor sit amet consectetur adipisicing elit',
    fecCaptura: new Date().toISOString(),
    cveAmparo: '',
    averPrevia: 'ASFD/DFAD',
    causaPenal: 'DFS',
    noExpediente: '123',
  },
  {
    noVolante: 123456,
    identifica: 'ASEG',
    tipoVolante: 'P',
    asunto: 'Lorem ipsum dolor sit amet consectetur adipisicing elit',
    fecCaptura: new Date().toISOString(),
    cveAmparo: '',
    averPrevia: 'ASFD/DFAD',
    causaPenal: 'DFS',
    noExpediente: '123',
  },
  {
    noVolante: 123456,
    identifica: 'ASEG',
    tipoVolante: 'P',
    asunto: 'Lorem ipsum dolor sit amet consectetur adipisicing elit',
    fecCaptura: new Date().toISOString(),
    cveAmparo: '',
    averPrevia: 'ASFD/DFAD',
    causaPenal: 'DFS',
    noExpediente: '123',
  },
];
