export const goodsData = [
  {
    goodId: 2225,
    stock: 'NULL',
    description:
      'DISCOS COMPACTOS DIFERENTES TITULOS Y AUTORES DE LOS DENOMINADOS PIRATAS',
    amount: 123,
    inputdate: 'NULL',
    outputdate: 'NULL',
    expirydate: 'NULL',
    locationtype: 'A',
    status: 'ADE',
    classification: 'No_Class_Bien',
    satUniqueKey: 'NO REGISTRADO',
  },
  {
    goodId: 2226,
    stock: 'NULL',
    description:
      'PEDAZOS DE TUBOS DE PVC COLOR BLANCO DE APROX. 60 CM DE LARGO',
    amount: 8,
    inputdate: '2000-07-04 00:00:00',
    outputdate: 'NULL',
    expirydate: 'NULL',
    locationtype: 'A',
    status: 'ADM',
    classification: 'No_Class_Bien',
    satUniqueKey: 'NO REGISTRADO',
  },
  {
    goodId: 2227,
    stock: 'NULL',
    description: 'DISCOS COMPACTOS PIRATAS DIFERENTES ARTISTAS',
    amount: 267,
    inputdate: '2000-07-04 00:00:00',
    outputdate: 'NULL',
    expirydate: 'NULL',
    locationtype: 'A',
    status: 'ADM',
    classification: 'No_Class_Bien',
    satUniqueKey: 'NO REGISTRADO',
  },
  {
    goodId: 2228,
    stock: 'NULL',
    description:
      'GRABADORAS MARCA GENERAL SOUND MODELO 711 CON RADIO CASETERA Y RECEPTOR DE RADIO AM/FM DIGITAL ANTANA TELESCOPICA ROTATIVA',
    amount: 8,
    inputdate: '2000-07-04 00:00:00',
    outputdate: 'NULL',
    expirydate: 'NULL',
    locationtype: 'A',
    status: 'ADM',
    classification: 'No_Class_Bien',
    satUniqueKey: 'NO REGISTRADO',
  },
  {
    goodId: 2229,
    stock: 'NULL',
    description: 'CABLE COAXIAL SE RECIBIO POR KILOS',
    amount: 60,
    inputdate: '2000-07-04 00:00:00',
    outputdate: 'NULL',
    expirydate: 'NULL',
    locationtype: 'A',
    status: 'ADM',
    classification: 'No_Class_Bien',
    satUniqueKey: 'NO REGISTRADO',
  },
  {
    goodId: 2230,
    stock: 'NULL',
    description:
      'TRAMOS DE FIERRO FORMA CILINDRICA DE APROX. 60 CM DE LARGO Y EN CADA UNO DE SUS EXTREMOS SE APRECIA UNA PIEZA DE FIERRO DE FORMA REDONDA Y CON ROSCA',
    amount: 8,
    inputdate: '2000-07-04 00:00:00',
    outputdate: 'NULL',
    expirydate: 'NULL',
    locationtype: 'A',
    status: 'ADM',
    classification: 'No_Class_Bien',
    satUniqueKey: 'NO REGISTRADO',
  },
  {
    goodId: 2231,
    stock: 'NULL',
    description:
      'GRABADORA MARCA GENERAL SOUND MODELO 405 CON RADIOCASSETERA AM/FM CASETERA DIGITAL',
    amount: 1,
    inputdate: '2000-07-04 00:00:00',
    outputdate: 'NULL',
    expirydate: 'NULL',
    locationtype: 'A',
    status: 'ADM',
    classification: 'No_Class_Bien',
    satUniqueKey: 'NO REGISTRADO',
  },
  {
    goodId: 160825,
    stock: '000480000000014',
    description: 'MESA HECHIZA DE LAMINA',
    amount: 1,
    inputdate: '1995-12-31 00:00:00',
    outputdate: '2005-01-25 00:00:00',
    expirydate: 'NULL',
    locationtype: 'A',
    status: 'ENT',
    classification: 'No_Class_Bien',
    satUniqueKey: 'NO REGISTRADO',
  },
  {
    goodId: 3291,
    stock: 'NULL',
    description:
      'MINICOMPONENTE MARCA AIWA, MODELO NSX-V700, SIN NUMERO DE SERIE',
    amount: 1,
    inputdate: '2000-09-12 00:00:00',
    outputdate: 'NULL',
    expirydate: 'NULL',
    locationtype: 'A',
    status: 'ADE',
    classification: 'No_Class_Bien',
    satUniqueKey: 'NO REGISTRADO',
  },
  {
    goodId: 3292,
    stock: 'NULL',
    description: 'VIDEOCASETTES EN FORMATO VHS Y BETA',
    amount: 3640,
    inputdate: '2000-09-12 00:00:00',
    outputdate: 'NULL',
    expirydate: 'NULL',
    locationtype: 'A',
    status: 'ADM',
    classification: 'No_Class_Bien',
    satUniqueKey: 'NO REGISTRADO',
  },
];
