export const goodsStatuData = [
  {
    id: '1',
    status: 'VPP',
    description: 'Bien Vendido, Pago parcial',
    no_registro: '2707999',
    no_gestion: '7',
    no_rencuen: '12',
    no_juntgob: '4',
    no_inmalm: '4',
    no_cop: '9',
    cod_rencuen: 'AD/VE',
    cod_juntgob: 'AD',
    cod_inmalm: 'AD',
    cod_cop: 'PD',
    trial622: 'T',
  },
  {
    id: '1',
    status: 'PEA',
    description: 'Parcializado en Administración',
    no_registro: '27681103',
    no_gestion: 'NULL',
    no_rencuen: '13',
    no_juntgob: '11',
    no_inmalm: 'NULL',
    no_cop: 'NULL',
    cod_rencuen: 'PA',
    cod_juntgob: 'CNG',
    cod_inmalm: 'CNG',
    cod_cop: 'DT',
    trial622: 'T',
  },
  {
    id: '2',
    status: 'VSR',
    description: 'Bien Vendido Suspendido para la Entrega',
    no_registro: '52398081',
    no_gestion: '7',
    no_rencuen: '12',
    no_juntgob: '11',
    no_inmalm: '4',
    no_cop: '4',
    cod_rencuen: 'AD/VE',
    cod_juntgob: 'VE',
    cod_inmalm: 'AD',
    cod_cop: 'PD',
    trial622: 'T',
  },
  {
    id: '3',
    status: 'PRP',
    description: 'PROCESO DE RECUPERACIÓN',
    no_registro: '37810776',
    no_gestion: 'NULL',
    no_rencuen: '4',
    no_juntgob: 'NULL',
    no_inmalm: 'NULL',
    no_cop: 'NULL',
    cod_rencuen: 'AD',
    cod_juntgob: 'NULL',
    cod_inmalm: 'NULL',
    cod_cop: 'PD',
    trial622: 'T',
  },
  {
    id: '4',
    status: 'VPT',
    description: 'Bien Vendido, pago total',
    no_registro: '2708003',
    no_gestion: '7',
    no_rencuen: '4',
    no_juntgob: 'NULL',
    no_inmalm: '4',
    no_cop: '9',
    cod_rencuen: 'AD/VE',
    cod_juntgob: 'VE',
    cod_inmalm: 'AD',
    cod_cop: 'PD',
    trial622: 'T',
  },
  {
    id: '5',
    status: 'ABT',
    description: 'Abandonado ENTERADO A TESOFE',
    no_registro: '56863373',
    no_gestion: '9',
    no_rencuen: '4',
    no_juntgob: '4',
    no_inmalm: '4',
    no_cop: '4',
    cod_rencuen: 'AD',
    cod_juntgob: 'AD',
    cod_inmalm: 'AD',
    cod_cop: 'ADC',
    trial622: 'T',
  },
];
