export const dataRequest = [
  {
    task: 'Registro de solicitud (Captura de Solicitud) con folio 45009',
    requestNumber: 45009,
    taskNumber: 260301,
    instanceNumber: 820169,
    created: 'tester_nsbxt',
    process: 'SolicitudeTransferencia',
  },
  {
    task: 'Registo de solicitud (programar solicitud) con folio 45010',
    requestNumber: 45010,
    taskNumber: 260302,
    instanceNumber: 820170,
    created: 'tester_nsbxt',
    process: 'SolicitudProgramacion',
  },
  {
    task: 'BIENES SIMILARES: Registro de Documentación Complementaria, No. Solicitud: 1851',
    requestNumber: 45010,
    taskNumber: 260302,
    instanceNumber: 820170,
    created: 'tester_nsbxt',
    process: 'RegistroSolicitudes',
  },
  {
    task: 'RESARCIMIENTO NUMERARIO: Registro de Documentación Complementaria, No. Solicitud: 1896',
    requestNumber: 1896,
    taskNumber: 212028,
    instanceNumber: 450060,
    created: 'tester_nsbxt',
    process: 'RE_RegistrarDocumentacion',
  },
  {
    task: 'Solicitar Recursos Económicos, No. Solicitud: 1896, Contribuyente CARLOS G. PALMA',
    requestNumber: 1896,
    taskNumber: 212097,
    instanceNumber: 450060,
    created: 'tester_nsbxt',
    process: 'RE_SolicitarRecursos',
  },
  {
    task: 'Revisión de Lineamientos de Resarcimiento (Especie), No. Solicitud: 1896, Contribuyente CARLOS G. PALMA',
    requestNumber: 1897,
    taskNumber: 212097,
    instanceNumber: 450060,
    created: 'tester_nsbxt',
    process: 'RE_RevisarLineamientos',
  },
];
