export interface Iprogramming {
  acuseEvent: number;
  address: string;
  autorityId: number | string;
  chargeSignatore: string;
  city: string;
  concurrentMsg: string;
  concurrentNumber: number;
  contentId: string;
  creationDate: string;
  creationUser: string;
  delregAttentionId: number;
  emailTransfer: string;
  endDate: string;
  eventId: number;
  folio: string;
  formalizationEndDate: string;
  id: number;
  indFulfillTime: string;
  instanceBpel: string;
  instanceBpm: number;
  instanceSise: number;
  modificationDate: string;
  modificationUser: string;
  msgSise: string;
  nameSignatore: string;
  nameTe: string;
  observation: string;
  programmingLee: string;
  regSendSat: number;
  regionalDelegationNumber: number | string;
  startDate: string;
  stateKey: number;
  stationId: string | number;
  status?: string;
  statusEbs: string;
  storeId: number | string;
  subTypeGoodId: number;
  termEjecutionDate: string;
  tranferId: number | string;
  typeGoodId: number;
  typeRelevantId: number | string;
  typeSignature: string;
  typeUser: string;
  validateGood: string;
  version: number;
}
