export interface ITrackedGood {
  id: number;
  fileNumber: string;
  goodNumber: string;
  inventorySiabiId: string | number;
  propertyCisiId: string | number;
  invactualSiabiId: string | number;
  referenceGoodNumber: string;
  parentGoodPartialNumber: string | number;
  parentGoodMenajeNumber: string | number;
  keyReceptionMinutes: string | number;
  keyCancelationMinutes: string | number;
  keyDestructionMinutes: string | number;
  keyDonationContract: string | number;
  keyDestMinutes: string | number;
  keyConvMinutes: string | number;
  keyDevolutionMinutes: string | number;
  keyForfeitureMinutes: string | number;
  quantity: string;
  appraisalValue: string | number;
  keyAppraisalCurrency: string;
  apraisalDateVig: string | number;
  labelNumber: string;
  destiny: string;
  goodStatus: string;
  status: string;
  statusDescription: string;
  situation: string | number;
  situationDesc: string | number;
  goodDescription: string;
  clasif: string;
  goodType: string;
  goodStype: string;
  goodSsType: string;
  goodSssType: string;
  entryDate: string | number;
  outputDate: string | number;
  expirationDate: string | number;
  dateReceptionPhisical: string | number;
  drawerNumber: string | number;
  vaultNumber: string | number;
  asociateExpNumber: string;
  warehouseNumber: string | number;
  warehouseType: string | number;
  delegationRes: string | number;
  warehouseUbication: string | number;
  warehosueState: string | number;
  warehouseCityNumber: string | number;
  warehouseCity: string | number;
  val1: string | number;
  val2: string | number;
  val3: string | number;
  val4: string | number;
  val5: string | number;
  val6: string | number;
  val7: string | number;
  val8: string | number;
  val9: string | number;
  val10: string | number;
  val11: string | number;
  val12: string | number;
  val13: string | number;
  val14: string | number;
  val15: string | number;
  val16: string | number;
  val17: string | number;
  val18: string | number;
  val19: string | number;
  val20: string | number;
  val21: string | number;
  val22: string | number;
  val23: string | number;
  val24: string | number;
  val25: string | number;
  val26: string | number;
  val27: string | number;
  val28: string | number;
  val29: string | number;
  val30: string | number;
  val31: string | number;
  val32: string | number;
  val33: string | number;
  val34: string | number;
  val35: string | number;
  val36: string | number;
  val37: string | number;
  val38: string | number;
  val39: string | number;
  val40: string | number;
  val41: string | number;
  val42: string | number;
  val43: string | number;
  val44: string | number;
  val45: string | number;
  val46: string | number;
  val47: string | number;
  val48: string | number;
  val49: string | number;
  val50: string | number;
  nameIndicated: string | number;
  identificator: string;
  keyOpinionOrigin: string | number;
  dictDevolution: string | number;
  dictDestruction: string | number;
  forfeitureDict: string | number;
  donationDict: string | number;
  destinyDict: string | number;
  compensationDict: string | number;
  abandonmentDict: string | number;
  transfereeDesc: string | number;
  emisorAuthority: string;
  measurementUnit: string;
  photography: string | number;
  keyEvent: string | number;
  lotEvent: string | number;
  evelotStatus: string | number;
  invoiceNumber: string | number;
  transfereeD: string | number;
  emitter: string | number;
  authority: string | number;
  dateOriginOpinion: string | number;
  dateDictDev: string | number;
  dateElaborateMinuteDevolu: string | number;
  dateElaborationMinuteDonation: string | number;
  dateDictaResar: string | number;
  compensationMinute: string | number;
  dateMinuteResar: string | number;
  adminCoord: string | number;
  penalizeCause: string | number;
  avPrev: string | number;
  crimeDescr: string | number;
  crime: string | number;
  evictionDayDay: string | number;
  transfereeExp: string | number;
  keyPositionRelief: string | number;
  dateDestructionPhysical: string | number;
  vaultDesc: string | number;
  vaultLocation: string | number;
  positionExt: string | number;
  programmingConstentKey: string | number;
  programmingConstentStatus: string | number;
  programmingDestDateEnd: string | number;
  programmingDestDateStart: string | number;
  eventDate: string | number;
  extDomProcess: string;
  stageState: string | number;
  photoDate: string | number;
  stateStage: string | number;
  goodObservations: string | number;
  transfereeMinuteNumber: string | number;
  transfereeMinute: string | number;
  extDomIniProcess: string | number;
  concilitate: number;
  numberPhotos: string | number;
  comerAppraisalActive: string | number;
  respRepuve: string | number;
  motiveJustify: string | number;
  satUbicationWarehouse: string | number;
  adminCoordNumber: string | number;
  satDescription: string | number;
  fractionSat: string | number;
  inventoryNumber: string | number;
  managementNumber: string | number;
  numeraryNoEnt: string | number;
  transfereeNumber: string;
  socialCabite: string | number;
  goodId: string | number;
  select?: boolean;
}

export interface ITrackerGoodF {
  id: number;
  fileNumber: string;
  goodNumber: string;
  destiny: string;
  goodStatus: string;
  statusDescription: string;
  goodDescription: string;
  goodType: string;
  goodStype: string;
  goodSsType: string;
  goodSssType: string;
}

export interface ITrackerGoodSocialCabinetObject extends ITrackerGoodF {
  socialCabinet: SocialCabinet;
}

export interface ITrackerGoodSocialCabinet extends ITrackerGoodF {
  socialCabinet: string;
}

interface SocialCabinet {
  cabinetType: string;
}
