export const COLUMNS = {
  paymentId: {
    title: 'Id.Pago',
    width: '15%',
    type: 'string',
    sort: false,
  },
  reference: {
    title: 'Ref.',
    width: '15%',
    type: 'string',
    sort: false,
  },
  moveNumber: {
    title: 'No.Movto.',
    width: '15%',
    type: 'string',
    sort: false,
  },
  move: {
    title: 'Movimiento',
    width: '15%',
    type: 'string',
    sort: false,
  },
  date: {
    title: 'Fecha',
    width: '15%',
    type: 'string',
    sort: false,
  },
  amount: {
    title: 'Monto',
    width: '15%',
    type: 'string',
    sort: false,
  },
  bank: {
    title: 'Banco',
    width: '15%',
    type: 'string',
    sort: false,
  },
  oi: {
    title: 'OI',
    width: '15%',
    type: 'string',
    sort: false,
  },
  dateOi: {
    title: 'Fecha OI',
    width: '15%',
    type: 'string',
    sort: false,
  },
  customerId: {
    title: 'Id.Cliente',
    width: '15%',
    type: 'string',
    sort: false,
  },
  taxId: {
    title: 'R.F.C',
    width: '15%',
    type: 'string',
    sort: false,
  },
  name: {
    title: 'Nombre',
    width: '15%',
    type: 'string',
    sort: false,
  },
  devPena: {
    title: 'Dev/Pena',
    width: '15%',
    type: 'string',
    sort: false,
  },
  event: {
    title: 'Evento',
    width: '15%',
    type: 'string',
    sort: false,
  },
  batch: {
    title: 'Lote',
    width: '15%',
    type: 'string',
    sort: false,
  },
};
