export const COLUMNS = {
  paymentId: {
    title: 'ID Pago',
    // width: '15%',
    type: 'string',
    sort: false,
  },
  reference: {
    title: 'Referencia',
    // width: '15%',
    type: 'string',
    sort: false,
  },
  movementNumber: {
    title: 'No. Movto.',
    // width: '15%',
    type: 'string',
    sort: false,
  },
  move: {
    title: 'Movimiento',
    // width: '15%',
    type: 'string',
    sort: false,
  },
  date: {
    title: 'Fecha',
    // width: '15%',
    type: 'string',
    sort: false,
  },
  amount: {
    title: 'Monto',
    // width: '15%',
    type: 'string',
    sort: false,
  },
  bankKey: {
    title: 'Banco',
    // width: '15%',
    type: 'string',
    sort: false,
  },
  entryOrderId: {
    title: 'OI',
    // width: '15%',
    type: 'string',
    sort: false,
  },
  lotPub: {
    title: 'Lote Pub.',
    // width: '15%',
    type: 'string',
    sort: false,
  },
  event: {
    title: 'Evento',
    // width: '15%',
    type: 'string',
    sort: false,
  },
  // dateOi: {
  //   title: 'Fecha OI',
  //   width: '15%',
  //   type: 'string',
  //   sort: false,
  // },
  clientId: {
    title: 'ID Cliente',
    // width: '15%',
    type: 'string',
    sort: false,
  },
  taxId: {
    title: 'R.F.C',
    // width: '15%',
    type: 'string',
    sort: false,
  },
  name: {
    title: 'Nombre',
    // width: '15%',
    type: 'string',
    sort: false,
  },
  appliedTo: {
    title: 'Dev/Pena',
    // width: '15%',
    type: 'string',
    sort: false,
  },
};
