export const packagesData = [
  {
    id: 40,
    description: 'FOLIO: 00023, DELEGACION: DELEGACIÓN REGIONAL NORESTE',
    packageType: 2,
    amount: 295.2,
    elaborationDate: '2012-11-01',
    captureDate: '2012-11-01',
    capturehcDate: '2012-11-01',
    packageStatus: 'C',
    classificationNumber: 778,
    targetNumber: 2,
    unit: 'PIEZA',
    warehouseNumber: 9651,
    registryNumber: 308160016,
    status: 'ADM',
    tranEmiAutNumber: 120,
    validationDate: '2012-11-01',
    authorizationDate: '2012-11-01',
    closingDate: '2012-11-01',
    applicationDate: 'NULL',
    packageCVE: 'CONV/RT/SAT/DRNE/DRNE/00023/12/11',
    cancellationDate: 'NULL',
    universalFolio: 1237582,
    paragraph1:
      '- - - En la Ciudad de Apodaca, siendo las 13:00 horas, del día 29 de Octubre de 2012, se encuentran presentes en la Bodega ubicada en la calle de Jose Lopez Portillo No. 2000 de esta Ciudad, el C. Carlos Andrés Gómez-Danés Mejía con cargo de Gerente Regional Monterrey de la, empresa TDR Transportes S.A de C.V. y el C. Rolando Arciniega Fuantos adscrito a la Delegación regional Noreste del Servicio de Administración y Enajenación de Bienes (SAE), Organismo Descentralizado de la Administración Pública Federal; ambos con el fin de llevar a cabo la validación y conversión de los bienes transferidos al SAE.- - - - - - - - - - - - - - - - - - - - - - - - - - - -\n- - -Interviene como testigo de asistencia el C.Julio Hernandez García - - - - - - - -  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\n-------------------------------------------------- A N T E C E D E N T E S --------------------------------------------------- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\n- - - l. Los bienes fueron transferidos al SAE por el Servicio de Administración Tributaria, con fundamento en los artículos 3 de la LFAEBSP, 12 y 13 del Reglamento de la ley en comento. - - \n- - - II.- Los bienes sujetos ha validación y conversión de unidad, se encuentran en administración del SAE y bajo la custodia de TDR Transportes S.A de C.V. los cuales se incorporan a este procedimiento a efecto de facilitar la ejecución de su destino.- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\n----------------------------------------------------- DECLARACIONES ------------------------------------------------------\n- - - PRIMERA.- El C. Rolando Arciniega Fuantos manifiesta que los bienes que fueron transferidos al SAE se encuentran bajo su custodia y con el fin de dar cumplimento al destino final sugerido por la Entidad Transferente se sujetaran a un procedimiento de validación y conversión en virtud de que fueron puestos a disposición con un tipo de unidad diferente al de kilogramos.- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - \n- - - SEGUNDA.- Que para realizar el proceso de validación y conversión se verifican las amountes físicas, contra las amountes señaladas en los documentos y registros oficiales para posteriormente determinar el valor de conversión a kilogramos. - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - \n- - - TERCERA.- La conversión integra un paquete de bienes, que puede estar conformado por uno o varios registros y que son consistentes en las siguientes características: a) Autoridad SAT - COMERCIO EXTERIOR, b) Clasificador del bien ROPA DIVERSA, c) Estatus del bien ADM, d) Etiqueta de destino DONACION, e) La custodia se encuentra a cargo del almacén TDR ALMACEN MONTERREY, y f) La administración de los bienes esta a cargo de la  la Delegación Regional Noreste.- - - - - - - -',
    paragraph2:
      '- - - CUARTA.- Una vez validada la existencia física de los bienes descritos en la declaratoria anterior, se determinó que su valor de conversión a kilogramos corresponde a 295.2',
    paragraph3:
      '-- - - QUINTA.- El valor de conversión a kilogramos determinado en la Cláusula Cuarta es una referencia para ejecutar el destino de Donación de los bienes  que conforman en paquete, por lo que cada registro conserva la referencia de amount y unidad recibidas del transferente - - - - - - - - - - -  -- - - - - - - - - - - - - - - - - - - - - - - - -  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -  - - - - - - - - - - - - - - \n- - - - - - - - - -  - - - - - - - - - - - - -  CIERRE DEL ACTA - - - -  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -  ------Se da por concluida la presente acta, siendo las 13:30 horas del día 29 de Octubre de 2012, firmando  al margen y al calce por las personas que en ella intervienen, para todos los efectos a que haya lugar. - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\nCUSTODIA, VALIDA Y EJECUTA CONVERSIÓN\n\t\t\t\n         POR EL S.A.E.                                        POR EL ALMACEN TDR MONTERREY\n\nC. Rolando Arciniega Fuantos                 C. Carlos Andres Gomez-Danes Mejia\n\nUltima página del Acta Administrativa de Validación y Conversión de Bienes con Clave CONV/RT/SAT/DRNE/DRNE/00023/12/11 de fecha  29 de  octubre de 2012, constante de 3 fojas. - - - - - - - - - - - -',
    delegationNumber: 4,
    elaborationUSU: 'RARCINIEGA',
    validationUSU: 'RARCINIEGA',
    authorizationUSU: 'RARCINIEGA',
    closingUSU: 'RARCINIEGA',
    applicationUSU: 'NULL',
    cancellationUSU: 'NULL',
    goodNumberF: 1946807,
    trial785: 'T',
  },
  {
    id: 29,
    description: 'FOLIO: 00019, DELEGACION: DELEGACIÓN REGIONAL NORESTE',
    packageType: 2,
    amount: 173.4,
    elaborationDate: '2012-10-31',
    captureDate: '2012-10-31',
    capturehcDate: '2012-10-31',
    packageStatus: 'C',
    classificationNumber: 781,
    targetNumber: 2,
    unit: 'PAR',
    warehouseNumber: 9651,
    registryNumber: 307640144,
    status: 'ADM',
    tranEmiAutNumber: 120,
    validationDate: '2012-10-31',
    authorizationDate: '2012-10-31',
    closingDate: '2012-10-31',
    applicationDate: 'NULL',
    packageCVE: 'CONV/RT/SAT/DRNE/DRNE/00019/12/10',
    cancellationDate: 'NULL',
    universalFolio: 1237061,
    paragraph1:
      '- - - En la Ciudad de Apodaca, siendo las 15:00 horas, del día 31 de Octubre de 2012, se encuentran presentes en la Bodega ubicada en la calle de Jose Lopez Portillo No. 2000 de esta Ciudad, el C. Carlos Andrés Gómez-Danés Mejía con cargo de Gerente Regional Monterrey de la, empresa TDR Transportes S.A de C.V. y el C. Rolando Arciniega Fuantos adscrito a la Delegación regional Noreste del Servicio de Administración y Enajenación de Bienes (SAE), Organismo Descentralizado de la Administración Pública Federal; ambos con el fin de llevar a cabo la validación y conversión de los bienes transferidos al SAE.- - - - - - - - - - - - - - - - - - - - - - - - - - - -\n- - -Interviene como testigo de asistencia el C.Julio Hernandez García - - - - - - - -  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\n-------------------------------------------------- A N T E C E D E N T E S --------------------------------------------------- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\n- - - l. Los bienes fueron transferidos al SAE por el Servicio de Administración Tributaria, con fundamento en los artículos 3 de la LFAEBSP, 12 y 13 del Reglamento de la ley en comento. - - \n- - - II.- Los bienes sujetos ha validación y conversión de unidad, se encuentran en administración del SAE y bajo la custodia de TDR Transportes S.A de C.V. los cuales se incorporan a este procedimiento a efecto de facilitar la ejecución de su destino.- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\n----------------------------------------------------- DECLARACIONES ------------------------------------------------------\n- - - PRIMERA.- El C. Rolando Arciniega Fuantos manifiesta que los bienes que fueron transferidos al SAE se encuentran bajo su custodia y con el fin de dar cumplimento al destino final sugerido por la Entidad Transferente se sujetaran a un procedimiento de validación y conversión en virtud de que fueron puestos a disposición con un tipo de unidad diferente al de kilogramos.- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - \n- - - SEGUNDA.- Que para realizar el proceso de validación y conversión se verifican las amountes físicas, contra las amountes señaladas en los documentos y registros oficiales para posteriormente determinar el valor de conversión a kilogramos. - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - \n- - - TERCERA.- La conversión integra un paquete de bienes, que puede estar conformado por uno o varios registros y que son consistentes en las siguientes características: a) Autoridad SAT - COMERCIO EXTERIOR, b) Clasificador del bien CALZADO DIVERSO, c) Estatus del bien ADM, d) Etiqueta de destino DONACION, e) La custodia se encuentra a cargo del almacén TDR ALMACEN MONTERREY, y f) La administración de los bienes esta a cargo de la Delegacion Regional Noreste.- - - - - - - - - - - - -',
    paragraph2:
      '- - - CUARTA.- Una vez validada la existencia física de los bienes descritos en la declaratoria anterior, se determinó que su valor de conversión a kilogramos corresponde a 173.4',
    paragraph3:
      '- - - QUINTA.- El valor de conversión a kilogramos determinado en la Cláusula Cuarta es una referencia para ejecutar el destino de Donación de los bienes  que conforman en paquete, por lo que cada registro conserva la referencia de amount y unidad recibidas del transferente - - - - - - - - - - -  -- - - - - - - - - - - - - - - - - - - - - - - - -  - - - - - - - - - - - - - - - - - - - - - -\n- - - - - - - - - - - - - - - - - - - - - - - - - - -  CIERRE DEL ACTA -------------------------------------------------\nSe da por concluida la presente acta, siendo las 15:30 horas del día 31 de Octubre de 2012, firmando  al margen y al calce por las personas que en ella intervienen, para todos los efectos a que haya lugar. - - - - - - - - - - - - - - - -\nCUSTODIA, VALIDA Y EJECUTA CONVERSIÓN\n\t\t\t\n         POR EL S.A.E.                                        POR EL ALMACEN TDR MONTERREY\n\nC. Rolando Arciniega Fuantos                 C. Carlos Andrés Gomez-Danes Mejia\n\nÚltima página del Acta Administrativa de Validación y Conversión de Bienes con Clave CONV/RT/SAT/DRNE/DRNE/00019/12/10 de fecha 31 de  Octubre de 2012, constante de 2 fojas. - - - - - - - - - - - -',
    delegationNumber: 4,
    elaborationUSU: 'RARCINIEGA',
    validationUSU: 'RARCINIEGA',
    authorizationUSU: 'RARCINIEGA',
    closingUSU: 'RARCINIEGA',
    applicationUSU: 'NULL',
    cancellationUSU: 'NULL',
    goodNumberF: 1946659,
    trial785: 'T',
  },
  {
    id: 15,
    description: 'FOLIO: 00005, DELEGACION: DELEGACIÓN REGIONAL NORESTE',
    packageType: 2,
    amount: 'NULL',
    elaborationDate: '2012-10-30',
    captureDate: '2012-10-30',
    capturehcDate: '2012-10-30',
    packageStatus: 'P',
    classificationNumber: 785,
    targetNumber: 2,
    unit: 'PAR',
    warehouseNumber: 9651,
    registryNumber: 306207972,
    status: 'ADM',
    tranEmiAutNumber: 120,
    validationDate: 'NULL',
    authorizationDate: 'NULL',
    closingDate: 'NULL',
    applicationDate: 'NULL',
    packageCVE: 'CONV/RT/SAT/DRNE/DRNE/00005/12/10',
    cancellationDate: 'NULL',
    universalFolio: 'NULL',
    paragraph1:
      '- - - En la Ciudad de ______________, siendo las _____ horas, del día ____de ________ de 200__, se encuentran presentes en la Bodega ubicada en la calle de ________________________ de esta Ciudad, el C. _____________________ con cargo de ___________________, de la empresa ______________ y el C. ________________ adscrito a _______________ del Servicio de Administración y Enajenación de Bienes (SAE), Organismo Descentralizado de la Administración Pública Federal; ambos con el fin de llevar a cabo la validación y conversión de los bienes transferidos al SAE.- - - - - - - - - - - - - - - - - - - - - - - - - - - -\n- - -Intervienen como testigos de asistencia los CC. _______________________, y ___________________________, - - - - - - - -  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\n-------------------------------------------------- A N T E C E D E N T E S ------------------------------------------\n- - - l. Los bienes fueron transferidos al SAE por [_____________________________], con fundamento en los artículos 3 de la LFAEBSP, 12 y 13 del Reglamento de la ley en comento. - - \n- - - II.- Los bienes sujetos ha validación y conversión de unidad, se encuentran en administración del SAE y bajo la custodia de _____________________ los cuales se incorporan a este procedimiento a efecto de facilitar la ejecución de su destino.- - - - - - - - - - - - \n----------------------------------------------------- DECLARACIONES ---------------------------------------------\n- - - PRIMERA.- El C. _________________ manifiesta que los bienes que fueron transferidos al SAE se encuentran bajo su custodia y con el fin de dar cumplimento al destino final sugerido por la Entidad Transferente se sujetaran a un procedimiento de validación y conversión en virtud de que fueron puestos a disposición con un tipo de unidad diferente al de kilogramos.- - - \n- - - SEGUNDA.- Que para realizar el proceso de validación y conversión se verifican las amountes físicas, contra las amountes señaladas en los documentos y registros oficiales para posteriormente determinar el valor de conversión a kilogramos. - - - - - - - - - - - - - - - - - - - - - - -\n- - - TERCERA.- La conversión integra un paquete de bienes, que puede estar conformado por uno o varios registros y que son consistentes en las siguientes características: a) Autoridad SAT - COMERCIO EXTERIOR, b) Clasificador del bien TENIS, c) Estatus del bien ADM, d) Etiqueta de destino DONACION, e) La custodia se encuentra a cargo del almacén TDR ALMACEN MONTERREY, y f) La administración de los bienes esta a cargo de la Coordinación (s) Regional (es)_________________________________.- - - - - - - - - - - - -',
    paragraph2:
      '- - - CUARTA.- Una vez validada la existencia física de los bienes descritos en la declaratoria anterior, se determinó que su valor de conversión a kilogramos corresponde a:',
    paragraph3:
      '- - - QUINTA.- El valor de conversión a kilogramos determinado en la Cláusula Cuarta es una referencia para ejecutar el destino de Donación de los bienes  que conforman en paquete, por lo que cada registro conserva la referencia de amount y unidad recibidas del transferente - - - - - - - - - - -  -- - - - - - - - - - - - - - - - - - - - - - - - -  - - - - - - - - - - - - - - - - - - - - - -\n- - - - - - - - - - - - - - - - - - - - - - - - - - -  CIERRE DEL ACTA -------------------------------------------------\nSe da por concluida la presente acta, siendo las ____ horas del día ____ de __________ de 200__, firmando  al margen y al calce por las personas que en ella intervienen, para todos los efectos a que haya lugar. - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\n\n\n\n\t\t\tCUSTODIA, VALIDA Y EJECUTA CONVERSIÓN\t\t\tPOR EL S.A.E.\n\n\n\n\n\n\t\t\tC. _____________________\t\t\t\t\tC. _____________________\n\n\nUltima página del Acta Administrativa de Validación y Conversión de Bienes con Clave CONV/RT/SAT/DRNE/DRNE/00005/12/10 de fecha ___ de  _________ de 2008, constante de ____ fojas. - - - - - - - - - - - -',
    delegationNumber: 4,
    elaborationUSU: 'RARCINIEGA',
    validationUSU: 'NULL',
    authorizationUSU: 'NULL',
    closingUSU: 'NULL',
    applicationUSU: 'NULL',
    cancellationUSU: 'NULL',
    goodNumberF: 'NULL',
    trial785: 'T',
  },
  {
    id: 60,
    description: 'FOLIO: 00040, DELEGACION: DELEGACIÓN REGIONAL NORESTE',
    packageType: 2,
    amount: 132.4,
    elaborationDate: '2012-11-27',
    captureDate: '2012-11-27',
    capturehcDate: '2012-11-27',
    packageStatus: 'C',
    classificationNumber: 781,
    targetNumber: 2,
    unit: 'PAR',
    warehouseNumber: 9651,
    registryNumber: 317528774,
    status: 'ADM',
    tranEmiAutNumber: 120,
    validationDate: '2012-11-29',
    authorizationDate: '2012-11-29',
    closingDate: '2012-11-29',
    applicationDate: 'NULL',
    packageCVE: 'CONV/RT/SAT/DRNE/DRNE/00040/12/11',
    cancellationDate: 'NULL',
    universalFolio: 1246083,
    paragraph1:
      '- - - En la Ciudad de Apodaca, siendo las 09:20 horas, del día 27 de Noviembre de 2012, se encuentran presentes en la Bodega ubicada en la calle de Jose Lopez Portillo No. 2000 de esta Ciudad, el C. Roberto Javier Gonzalez Gonzalez  con cargo de Gerente Corporativo de la empresa TDR Transportes S.A de C.V. y el C. Rolando Arciniega Fuantos adscrito a la Delegación regional Noreste del Servicio de Administración y Enajenación de Bienes (SAE), Organismo Descentralizado de la Administración Pública Federal; ambos con el fin de llevar a cabo la validación y conversión de los bienes transferidos al SAE.- - - - - - - - - - - - - - - - - - - - - - - - - - - -\n- - -Interviene como testigo de asistencia el C. Julio Hernandez García - - - - - - - -  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\n-------------------------------------------------- A N T E C E D E N T E S --------------------------------------------------- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\n- - - l. Los bienes fueron transferidos al SAE por el Servicio de Administración Tributaria, con fundamento en los artículos 3 de la LFAEBSP, 12 y 13 del Reglamento de la ley en comento. - - \n- - - II.- Los bienes sujetos ha validación y conversión de unidad, se encuentran en administración del SAE y bajo la custodia de TDR Transportes S.A de C.V. los cuales se incorporan a este procedimiento a efecto de facilitar la ejecución de su destino.- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\n----------------------------------------------------- DECLARACIONES ------------------------------------------------------\n- - - PRIMERA.- El C. Rolando Arciniega Fuantos manifiesta que los bienes que fueron transferidos al SAE se encuentran bajo su custodia y con el fin de dar cumplimento al destino final sugerido por la Entidad Transferente se sujetaran a un procedimiento de validación y conversión en virtud de que fueron puestos a disposición con un tipo de unidad diferente al de kilogramos.- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - \n- - - SEGUNDA.- Que para realizar el proceso de validación y conversión se verifican las amountes físicas, contra las amountes señaladas en los documentos y registros oficiales para posteriormente determinar el valor de conversión a kilogramos. - - - - - - - - - - - - - - - - - - - - - - - - - - \n- - - TERCERA.- La conversión integra un paquete de bienes, que puede estar conformado por uno o varios registros y que son consistentes en las siguientes características: a) Autoridad SAT - COMERCIO EXTERIOR, b) Clasificador del bien CALZADO DIVERSO, c) Estatus del bien ADM, d) Etiqueta de destino DONACION, e) La custodia se encuentra a cargo del almacén TDR ALMACEN MONTERREY, y f) La administración de los bienes esta a cargo de la Delegacion Regional Noreste.- - - - - - - - - - - - -',
    paragraph2:
      '- - - CUARTA.- Una vez validada la existencia física de los bienes descritos en la declaratoria anterior, se determinó que su valor de conversión a kilogramos corresponde a 132.4',
    paragraph3:
      '- - - QUINTA.- El valor de conversión a kilogramos determinado en la Cláusula Cuarta es una referencia para ejecutar el destino de Donación de los bienes  que conforman en paquete, por lo que cada registro conserva la referencia de amount y unidad recibidas del transferente - - - - - - - - - - -  -- - - - - - - - - - - - - - - - - - - - - - - - -  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -  - - - - - - - - - - - - - - \n- - - - - - - - - -  - - - - - - - - - - - - -  CIERRE DEL ACTA - - - -  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -  ------Se da por concluida la presente acta, siendo las 09:35 horas del día 27 de Noviembre de 2012, firmando  al margen y al calce por las personas que en ella intervienen, para todos los efectos a que haya lugar. - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\nCUSTODIA, VALIDA Y EJECUTA CONVERSIÓN\n\t\t\t\n         POR EL S.A.E.                                        POR EL ALMACEN TDR MONTERREY\n\n\nC. Rolando Arciniega Fuantos                 C. Roberto Javier Gonzalez Gonzalez  \n\n\nTESTIGO DE ASISTENCIA\n\nC. Julio Hernandez García\n\n\nÚltima página del Acta Administrativa de Validación y Conversión de Bienes con Clave CONV/RT/SAT/DRNE/DRNE/00040/12/11 de fecha 27 de  Noviembre de 2012, constante de 3 fojas. - - - - - - - - - - - -',
    delegationNumber: 4,
    elaborationUSU: 'RARCINIEGA',
    validationUSU: 'RARCINIEGA',
    authorizationUSU: 'RARCINIEGA',
    closingUSU: 'RARCINIEGA',
    applicationUSU: 'NULL',
    cancellationUSU: 'NULL',
    goodNumberF: 1959651,
    trial785: 'T',
  },
  {
    id: 69,
    description: 'FOLIO: 00049, DELEGACION: DELEGACIÓN REGIONAL NORESTE',
    packageType: 2,
    amount: 248,
    elaborationDate: '2012-11-28',
    captureDate: '2012-11-28',
    capturehcDate: '2012-11-28',
    packageStatus: 'C',
    classificationNumber: 778,
    targetNumber: 2,
    unit: 'PIEZA',
    warehouseNumber: 9651,
    registryNumber: 318371864,
    status: 'ADM',
    tranEmiAutNumber: 120,
    validationDate: '2012-11-29',
    authorizationDate: '2012-11-29',
    closingDate: '2012-11-29',
    applicationDate: 'NULL',
    packageCVE: 'CONV/RT/SAT/DRNE/DRNE/00049/12/11',
    cancellationDate: 'NULL',
    universalFolio: 1246757,
    paragraph1:
      '- - - En la Ciudad de Apodaca, siendo las 15:40 horas, del día 28 de Noviembre de 2012, se encuentran presentes en la Bodega ubicada en la calle de Jose Lopez Portillo No. 2000 de esta Ciudad, el C. Roberto Javier Gonzalez Gonzalez  con cargo de Gerente Corporativo de la empresa TDR Transportes S.A de C.V. y el C. Rolando Arciniega Fuantos adscrito a la Delegación regional Noreste del Servicio de Administración y Enajenación de Bienes (SAE), Organismo Descentralizado de la Administración Pública Federal; ambos con el fin de llevar a cabo la validación y conversión de los bienes transferidos al SAE.- - - - - - - - - - - - - - - - - - - - - - - - - - - -\n- - -Interviene como testigo de asistencia el C. Julio Hernandez García - - - - - - - -  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\n-------------------------------------------------- A N T E C E D E N T E S --------------------------------------------------- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\n- - - l. Los bienes fueron transferidos al SAE por el Servicio de Administración Tributaria, con fundamento en los artículos 3 de la LFAEBSP, 12 y 13 del Reglamento de la ley en comento. - - \n- - - II.- Los bienes sujetos ha validación y conversión de unidad, se encuentran en administración del SAE y bajo la custodia de TDR Transportes S.A de C.V. los cuales se incorporan a este procedimiento a efecto de facilitar la ejecución de su destino.- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\n----------------------------------------------------- DECLARACIONES ------------------------------------------------------\n- - - PRIMERA.- El C. Rolando Arciniega Fuantos manifiesta que los bienes que fueron transferidos al SAE se encuentran bajo su custodia y con el fin de dar cumplimento al destino final sugerido por la Entidad Transferente se sujetaran a un procedimiento de validación y conversión en virtud de que fueron puestos a disposición con un tipo de unidad diferente al de kilogramos.- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - \n- - - SEGUNDA.- Que para realizar el proceso de validación y conversión se verifican las amountes físicas, contra las amountes señaladas en los documentos y registros oficiales para posteriormente determinar el valor de conversión a kilogramos. - - - - - - - - - - - - - - - - - - - - - - - - - - \n- - - TERCERA.- La conversión integra un paquete de bienes, que puede estar conformado por uno o varios registros y que son consistentes en las siguientes características: a) Autoridad SAT - COMERCIO EXTERIOR, b) Clasificador del bien ROPA DIVERSA, c) Estatus del bien ADM, d) Etiqueta de destino DONACION, e) La custodia se encuentra a cargo del almacén TDR ALMACEN MONTERREY, y f) La administración de los bienes esta a cargo de la Delegación Regional Noreste.- - - - - - - - - - - - -',
    paragraph2:
      '- - - CUARTA.- Una vez validada la existencia física de los bienes descritos en la declaratoria anterior, se determinó que su valor de conversión a kilogramos corresponde a 248',
    paragraph3:
      '- - - QUINTA.- El valor de conversión a kilogramos determinado en la Cláusula Cuarta es una referencia para ejecutar el destino de Donación de los bienes  que conforman en paquete, por lo que cada registro conserva la referencia de amount y unidad recibidas del transferente - - - - - - - - - - -  -- - - - - - - - - - - - - - - - - - - - - - - - -  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -  - - - - - - - - - - - - - - \n- - - - - - - - - -  - - - - - - - - - - - - -  CIERRE DEL ACTA - - - -  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -  ------Se da por concluida la presente acta, siendo las 15:55 horas del día 28 de Noviembre de 2012, firmando  al margen y al calce por las personas que en ella intervienen, para todos los efectos a que haya lugar. - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\nCUSTODIA, VALIDA Y EJECUTA CONVERSIÓN\n\t\t\t\n         POR EL S.A.E.                                        POR EL ALMACEN TDR MONTERREY\n\nC. Rolando Arciniega Fuantos                 C. Roberto Javier Gonzalez Gonzalez  \n\nTESTIGO DE ASISTENCIA\n\nC. Julio Hernandez García\n\n\nÚltima página del Acta Administrativa de Validación y Conversión de Bienes con Clave CONV/RT/SAT/DRNE/DRNE/00049/12/11 de fecha 28 de Noviembre de 2012, constante de 14 fojas. - - - - - - - - - - - -',
    delegationNumber: 4,
    elaborationUSU: 'RARCINIEGA',
    validationUSU: 'RARCINIEGA',
    authorizationUSU: 'RARCINIEGA',
    closingUSU: 'RARCINIEGA',
    applicationUSU: 'NULL',
    cancellationUSU: 'NULL',
    goodNumberF: 1959658,
    trial785: 'T',
  },
  {
    id: 50,
    description: 'FOLIO: 00030, DELEGACION: DELEGACIÓN REGIONAL NORESTE',
    packageType: 2,
    amount: 184.8,
    elaborationDate: '2012-11-06',
    captureDate: '2012-11-06',
    capturehcDate: '2012-11-06',
    packageStatus: 'C',
    classificationNumber: 781,
    targetNumber: 2,
    unit: 'PAR',
    warehouseNumber: 9651,
    registryNumber: 310698582,
    status: 'ADM',
    tranEmiAutNumber: 120,
    validationDate: '2012-11-29',
    authorizationDate: '2012-11-29',
    closingDate: '2012-11-29',
    applicationDate: 'NULL',
    packageCVE: 'CONV/RT/SAT/DRNE/DRNE/00030/12/11',
    cancellationDate: 'NULL',
    universalFolio: 1238939,
    paragraph1:
      '- - - En la Ciudad de Apodaca, siendo las 11:00 horas, del día 6 de Noviembre de 2012, se encuentran presentes en la Bodega ubicada en la calle de Jose Lopez Portillo No. 2000 de esta Ciudad, el C. Carlos Andrés Gómez-Danés Mejía con cargo de Gerente Regional Monterrey de la, empresa TDR Transportes S.A de C.V. y el C. Rolando Arciniega Fuantos adscrito a la Delegación regional Noreste del Servicio de Administración y Enajenación de Bienes (SAE), Organismo Descentralizado de la Administración Pública Federal; ambos con el fin de llevar a cabo la validación y conversión de los bienes transferidos al SAE.- - - - - - - - - - -Interviene como testigo de asistencia el C.Julio Hernandez García - - - - - - - - - -- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - \n-------------------------------------------------- A N T E C E D E N T E S --------------------------------------------------- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - \n- - - l. Los bienes fueron transferidos al SAE por el Servicio de Administración Tributaria, con fundamento en los artículos 3 de la LFAEBSP, 12 y 13 del Reglamento de la ley en comento. - - \n- - - II.- Los bienes sujetos ha validación y conversión de unidad, se encuentran en administración del SAE y bajo la custodia de TDR Transportes S.A de C.V. los cuales se incorporan a este procedimiento a efecto de facilitar la ejecución de su destino.- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\n----------------------------------------------------- DECLARACIONES ------------------------------------------------------\n- - - PRIMERA.- El C. Rolando Arciniega Fuantos manifiesta que los bienes que fueron transferidos al SAE se encuentran bajo su custodia y con el fin de dar cumplimento al destino final sugerido por la Entidad Transferente se sujetaran a un procedimiento de validación y conversión en virtud de que fueron puestos a disposición con un tipo de unidad diferente al de kilogramos.- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -  - - - - - - - - - - - - - - - - - - - -\n- - - SEGUNDA.- Que para realizar el proceso de validación y conversión se verifican las amountes físicas, contra las amountes señaladas en los documentos y registros oficiales para posteriormente determinar el valor de conversión a kilogramos. - - - - - - - - - - - - - - - - - -- - - - TERCERA.- La conversión integra un paquete de bienes, que puede estar conformado por uno o varios registros y que son consistentes en las siguientes características: a) Autoridad SAT - COMERCIO EXTERIOR, b) Clasificador del bien CALZADO DIVERSO, c) Estatus del bien ADM, d) Etiqueta de destino DONACION, e) La custodia se encuentra a cargo del almacén TDR ALMACEN MONTERREY, y f) La administración de los bienes esta a cargo de la Delegación Regional Noreste.- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -',
    paragraph2:
      '- - - CUARTA.- Una vez validada la existencia física de los bienes descritos en la declaratoria anterior, se determinó que su valor de conversión a kilogramos corresponde a 184.8',
    paragraph3:
      '- - - QUINTA.- El valor de conversión a kilogramos determinado en la Cláusula Cuarta es una referencia para ejecutar el destino de Donación de los bienes  que conforman en paquete, por lo que cada registro conserva la referencia de amount y unidad recibidas del transferente - - - - - - - - - - -  -- - - - - - - - - - - - - - - - - - - - - - - - -  - - - - - - - - - - - - - - - - - - - - - -\n- - - - - - - - - - - - - - - - - - - - - - - - - - -  CIERRE DEL ACTA -------------------------------------------------\nSe da por concluida la presente acta, siendo las 11:30 horas del día 6 de Noviembre de 2012, firmando  al margen y al calce por las personas que en ella intervienen, para todos los efectos a que haya lugar. - - - - - - - - - - - - - - - -\nCUSTODIA, VALIDA Y EJECUTA CONVERSIÓN\n\t\t\t\n      \n   POR EL S.A.E.                                        POR EL ALMACEN TDR MONTERREY\n\nC. Rolando Arciniega Fuantos                 C. Carlos Andres Gomez-Danes Mejia\n\n\nTESTIGO DE ASISTENCIA\n\nC.Julio Hernandez García\n\n\nÚltima página del Acta Administrativa de Validación y Conversión de Bienes con Clave CONV/RT/SAT/DRNE/DRNE/00030/12/11 de fecha 6 de  Noviembre de 2012, constante de 3 fojas. - - - - - - - - - - - -',
    delegationNumber: 4,
    elaborationUSU: 'RARCINIEGA',
    validationUSU: 'RARCINIEGA',
    authorizationUSU: 'RARCINIEGA',
    closingUSU: 'RARCINIEGA',
    applicationUSU: 'NULL',
    cancellationUSU: 'NULL',
    goodNumberF: 1959645,
    trial785: 'T',
  },
  {
    id: 33,
    description: 'FOLIO: 00003, DELEGACION: DELEGACIÓN REGIONAL CENTRO SUR',
    packageType: 2,
    amount: 356.5,
    elaborationDate: '2012-11-01',
    captureDate: '2012-11-01',
    capturehcDate: '2012-11-01',
    packageStatus: 'C',
    classificationNumber: 778,
    targetNumber: 2,
    unit: 'NULL',
    warehouseNumber: 16268,
    registryNumber: 308153506,
    status: 'ADM',
    tranEmiAutNumber: 120,
    validationDate: '2012-11-01',
    authorizationDate: '2012-11-01',
    closingDate: '2012-11-01',
    applicationDate: 'NULL',
    packageCVE: 'CONV/RT/SAT/DRCS/DRCS/00003/12/11',
    cancellationDate: 'NULL',
    universalFolio: 1237575,
    paragraph1:
      '- - - En la Ciudad de Toluca siendo las 18:35 horas, del día 31 de octubre de 2012, se encuentran presentes en la Bodega ubicada en ubicada en Boulevard Aeropuerto Miguel Alemán número 160, Locales 8, 10 y 12, Zona Industrial Lerma, Toluca, Estado de México, C.P. 52000, el C. César Adrián Castañeda López con cargo de Gerente del Almacén Toluca Sur, de la empresa MyMland S.A de C.V, y el C.P. Enrique Adalberto García Calderón, Delegado Regional Centro Sur del Servicio de Administración y Enajenación de Bienes (SAE), Organismo Descentralizado de la Administración Pública Federal; ambos con el fin de llevar a cabo la validación y conversión de los bienes transferidos al SAE.- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - Intervienen como testigos de asistencia los CC. CC. Esteban Ordóñez López y Eduardo López Fuentes Montes de Oca, - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - A N T E C E D E N T E S - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - l. Los bienes objeto de la presente conversión de unidad fueron transferidos a este Servicio de Administración y Enajenación de bienes (SAE) por parte del Servicio de Administración Tributaria, a través de la Administración General de Auditoria Fiscal y la Administración General de Aduanas, lo anterior de conformidad con lo dispuesto en los artículos 3 de la Ley Federal para la Administración y Enajenación de Bienes del Sector Público, 12 y 13 de su Reglamento - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - II.- Los bienes afectos al proceso de validación y conversión de unidad, se encuentran en administración del SAE, en particular de la Delegación Regional Centro Sur, bajo la guardia y custodia de MyMLAND, S.A de C.V. (TLP) los cuales se incorporan a este procedimiento a efecto de agilizar los procedimientos correspondientes a otorgar el destino conveniente.- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -',
    paragraph2:
      '- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - DECLARACIONES - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - PRIMERA.- El C. César Adrián Castañeda López manifiesta que los bienes que fueron transferidos al SAE se encuentran bajo su custodia y con el fin de dar cumplimento al destino final sugerido por la Entidad Transferente se sujetaran a un procedimiento de validación y conversión en virtud de que fueron puestos a disposición con un tipo de unidad diferente al de kilogramos.- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - SEGUNDA.- Que para realizar el proceso de validación y posterior conversión de unidad de medida, se verificaron las amountes y características físicas, contra los datos señalados en las constancias oficiales, para posteriormente determinar el valor de conversión a la unidad de medida "kilogramo".- - - - - - - - - - - - - - - - - - - - - - TERCERA.- La conversión integra un paquete de registros (bienes SIAB) presentan las siguientes características: a) Autoridad SAT - COMERCIO EXTERIOR, b) Clasificador del bien ROPA DIVERSA, c) Estatus del bien ADM, d) Etiqueta de destino DONACION, e) La custodia se encuentra a cargo del almacén "ALMACÉN TOLUCA SUR", y f) La administración de los bienes están a cargo de la Delegación Regional Centro Sur.- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - CUARTA.- Una vez validada la existencia física de los bienes descritos en la declaración anterior, se determinó que el valor de conversión a kilogramos corresponde a 356.5 kilogramos (peso con embalaje). - - - - - - - -  QUINTA.- El valor de conversión a kilogramos determinado en la Cláusula Cuarta es una referencia para ejecutar el destino de Donación de los bienes  que conforman el paquete, por lo que cada registro conserva la referencia de amount y unidad recibidas del transferente - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -',
    paragraph3:
      '- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - CIERRE DEL ACTA- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - Se da por concluida la presente acta, siendo las 19:00  horas del día 31 de octubre del 2012, firmando  al margen y al calce por las personas que en ella intervienen, para todos los efectos a que haya lugar. - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\n\n\n      CUSTODIA, VALIDA Y EJECUTA CONVERSIÓN\t\t\t                                               POR EL S.A.E.\n\n\n\n\n            ___________________________\t                                                      ___________________________\n       C. César Adrián Castañeda López\t   \t\t                                             C.P. Enrique Adalberto García Calderón\t\n\n\nÚltima página del Acta Administrativa de Validación y Conversión de Bienes con Clave CONV/RT/SAT/DRCS/DRCS/00003/12/11 de fecha 31 de octubre del 2012, constante de 13 fojas. - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -',
    delegationNumber: 12,
    elaborationUSU: 'MSOTO',
    validationUSU: 'MSOTO',
    authorizationUSU: 'MSOTO',
    closingUSU: 'MSOTO',
    applicationUSU: 'NULL',
    cancellationUSU: 'NULL',
    goodNumberF: 1946800,
    trial785: 'T',
  },
  {
    id: 6,
    description: 'FOLIO: 00006, DELEGACION: OFICINAS CENTRALES',
    packageType: 2,
    amount: 0,
    elaborationDate: '2012-07-24',
    captureDate: '2012-07-24',
    capturehcDate: '2012-07-24',
    packageStatus: 'X',
    classificationNumber: 778,
    targetNumber: 2,
    unit: 'NULL',
    warehouseNumber: 1710,
    registryNumber: 282012827,
    status: 'PXD',
    tranEmiAutNumber: 120,
    validationDate: '2012-07-24',
    authorizationDate: '2012-07-24',
    closingDate: '2012-07-24',
    applicationDate: 'NULL',
    packageCVE: 'CONV/RT/SAT/DRN/OFICINAS CENTRALES/00006/12/07',
    cancellationDate: '2012-07-24',
    universalFolio: 'NULL',
    paragraph1:
      '- - - En la Ciudad de ______________, siendo las _____ horas, del día ____de ________ de 200__, se encuentran presentes en la Bodega ubicada en la calle de ________________________ de esta Ciudad, el C. _____________________ con cargo de ___________________, de la empresa ______________ y el C. ________________ adscrito a _______________ del Servicio de Administración y Enajenación de Bienes (SAE), Organismo Descentralizado de la Administración Pública Federal; ambos con el fin de llevar a cabo la validación y conversión de los bienes transferidos al SAE.- - - - - - - - - - - - - - - - - - - - - - - - - - - -\n- - -Intervienen como testigos de asistencia los CC. _______________________, y ___________________________, - - - - - - - -  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\n-------------------------------------------------- A N T E C E D E N T E S ------------------------------------------\n- - - l. Los bienes fueron transferidos al SAE por [_____________________________], con fundamento en los artículos 3 de la LFAEBSP, 12 y 13 del Reglamento de la ley en comento. - - \n- - - II.- Los bienes sujetos ha validación y conversión de unidad, se encuentran en administración del SAE y bajo la custodia de _____________________ los cuales se incorporan a este procedimiento a efecto de facilitar la ejecución de su destino.- - - - - - - - - - - - \n----------------------------------------------------- DECLARACIONES ---------------------------------------------\n- - - PRIMERA.- El C. _________________ manifiesta que los bienes que fueron transferidos al SAE se encuentran bajo su custodia y con el fin de dar cumplimento al destino final sugerido por la Entidad Transferente se sujetaran a un procedimiento de validación y conversión en virtud de que fueron puestos a disposición con un tipo de unidad diferente al de kilogramos.- - - \n- - - SEGUNDA.- Que para realizar el proceso de validación y conversión se verifican las amountes físicas, contra las amountes señaladas en los documentos y registros oficiales para posteriormente determinar el valor de conversión a kilogramos. - - - - - - - - - - - - - - - - - - - - - - -\n- - - TERCERA.- La conversión integra un paquete de bienes, que puede estar conformado por uno o varios registros y que son consistentes en las siguientes características: a) Autoridad SAT - COMERCIO EXTERIOR, b) Clasificador del bien ROPA DIVERSA, c) Estatus del bien ADM, d) Etiqueta de destino DONACION, e) La custodia se encuentra a cargo del almacén MYMLAND CIUDAD JUAREZ, y f) La administración de los bienes esta a cargo de la Coordinación (s) Regional (es)_________________________________.- - - - - - - - - - - - -',
    paragraph2:
      '- - - CUARTA.- Una vez validada la existencia física de los bienes descritos en la declaratoria anterior, se determinó que su valor de conversión a kilogramos corresponde a:   450 kilogramos',
    paragraph3:
      '- - - QUINTA.- El valor de conversión a kilogramos determinado en la Cláusula Cuarta es una referencia para ejecutar el destino de Donación de los bienes  que conforman en paquete, por lo que cada registro conserva la referencia de amount y unidad recibidas del transferente - - - - - - - - - - -  -- - - - - - - - - - - - - - - - - - - - - - - - -  - - - - - - - - - - - - - - - - - - - - - -\n- - - - - - - - - - - - - - - - - - - - - - - - - - -  CIERRE DEL ACTA -------------------------------------------------\nSe da por concluida la presente acta, siendo las ____ horas del día ____ de __________ de 200__, firmando  al margen y al calce por las personas que en ella intervienen, para todos los efectos a que haya lugar. - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\n\n\n\n\t\t\tCUSTODIA, VALIDA Y EJECUTA CONVERSIÓN\t\t\tPOR EL S.A E.\n\n\n\n\n\n\t\t\tC. _____________________\t\t\t\t\tC. _____________________\n\n\nUltima página del Acta Administrativa de Validación y Conversión de Bienes con Clave CONV/RT/SAT/DRN/OFICINAS CENTRALES/00006/12/07 de fecha ___ de  _________ de 2008, constante de ____ fojas. - - - - - - - - - - - -',
    delegationNumber: 3,
    elaborationUSU: 'PRODRIGUEZ',
    validationUSU: 'PRODRIGUEZ',
    authorizationUSU: 'PRODRIGUEZ',
    closingUSU: 'PRODRIGUEZ',
    applicationUSU: 'NULL',
    cancellationUSU: 'EGONZALEZ',
    goodNumberF: 'NULL',
    trial785: 'T',
  },
  {
    id: 42,
    description: 'FOLIO: 00025, DELEGACION: DELEGACIÓN REGIONAL NORESTE',
    packageType: 2,
    amount: 228,
    elaborationDate: '2012-11-01',
    captureDate: '2012-11-01',
    capturehcDate: '2012-11-01',
    packageStatus: 'C',
    classificationNumber: 778,
    targetNumber: 2,
    unit: 'PIEZA',
    warehouseNumber: 9651,
    registryNumber: 308160208,
    status: 'ADM',
    tranEmiAutNumber: 120,
    validationDate: '2012-11-01',
    authorizationDate: '2012-11-01',
    closingDate: '2012-11-01',
    applicationDate: 'NULL',
    packageCVE: 'CONV/RT/SAT/DRNE/DRNE/00025/12/11',
    cancellationDate: 'NULL',
    universalFolio: 1237584,
    paragraph1:
      '- - - En la Ciudad de Apodaca, siendo las 15:00 horas, del día 29 de Octubre de 2012, se encuentran presentes en la Bodega ubicada en la calle de Jose Lopez Portillo No. 2000 de esta Ciudad, el C. Carlos Andrés Gómez-Danés Mejía con cargo de Gerente Regional Monterrey de la, empresa TDR Transportes S.A de C.V. y el C. Rolando Arciniega Fuantos adscrito a la Delegación regional Noreste del Servicio de Administración y Enajenación de Bienes (SAE), Organismo Descentralizado de la Administración Pública Federal; ambos con el fin de llevar a cabo la validación y conversión de los bienes transferidos al SAE.- - - - - - - - - - - - - - - - - - - - - - - - - - - -\n- - -Interviene como testigo de asistencia el C.Julio Hernandez García - - - - - - - -  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\n-------------------------------------------------- A N T E C E D E N T E S --------------------------------------------------- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\n- - - l. Los bienes fueron transferidos al SAE por el Servicio de Administración Tributaria, con fundamento en los artículos 3 de la LFAEBSP, 12 y 13 del Reglamento de la ley en comento. - - \n- - - II.- Los bienes sujetos ha validación y conversión de unidad, se encuentran en administración del SAE y bajo la custodia de TDR Transportes S.A de C.V. los cuales se incorporan a este procedimiento a efecto de facilitar la ejecución de su destino.- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\n----------------------------------------------------- DECLARACIONES ------------------------------------------------------\n- - - PRIMERA.- El C. Rolando Arciniega Fuantos manifiesta que los bienes que fueron transferidos al SAE se encuentran bajo su custodia y con el fin de dar cumplimento al destino final sugerido por la Entidad Transferente se sujetaran a un procedimiento de validación y conversión en virtud de que fueron puestos a disposición con un tipo de unidad diferente al de kilogramos.- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - \n- - - SEGUNDA.- Que para realizar el proceso de validación y conversión se verifican las amountes físicas, contra las amountes señaladas en los documentos y registros oficiales para posteriormente determinar el valor de conversión a kilogramos. - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - \n- - - TERCERA.- La conversión integra un paquete de bienes, que puede estar conformado por uno o varios registros y que son consistentes en las siguientes características: a) Autoridad SAT - COMERCIO EXTERIOR, b) Clasificador del bien ROPA DIVERSA, c) Estatus del bien ADM, d) Etiqueta de destino DONACION, e) La custodia se encuentra a cargo del almacén TDR ALMACEN MONTERREY, y f) La administración de los bienes esta a cargo de la la Delegación Regional Noreste.- - - - - - - - - - - - - - - - - - - - - - - - - - -',
    paragraph2:
      '- - - CUARTA.- Una vez validada la existencia física de los bienes descritos en la declaratoria anterior, se determinó que su valor de conversión a kilogramos corresponde a 228',
    paragraph3:
      '- - - QUINTA.- El valor de conversión a kilogramos determinado en la Cláusula Cuarta es una referencia para ejecutar el destino de Donación de los bienes  que conforman en paquete, por lo que cada registro conserva la referencia de amount y unidad recibidas del transferente - - - - - - - - - - -  -- - - - - - - - - - - - - - - - - - - - - - - - -  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -  - - - - - - - - - - - - - - \n- - - - - - - - - -  - - - - - - - - - - - - -  CIERRE DEL ACTA - - - -  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -  ------Se da por concluida la presente acta, siendo las 15:30 horas del día 29 de Octubre de 2012, firmando  al margen y al calce por las personas que en ella intervienen, para todos los efectos a que haya lugar. - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\nCUSTODIA, VALIDA Y EJECUTA CONVERSIÓN\n\t\t\t\n         POR EL S.A.E.                                        POR EL ALMACEN TDR MONTERREY\n\nC. Rolando Arciniega Fuantos                 C. Carlos Andres Gomez-Danes Mejia\n\n\nUltima página del Acta Administrativa de Validación y Conversión de Bienes con Clave CONV/RT/SAT/DRNE/DRNE/00025/12/11 de fecha 29 de  octubre de 2012, constante de 3 fojas. - - - - - - - - - - - -',
    delegationNumber: 4,
    elaborationUSU: 'RARCINIEGA',
    validationUSU: 'RARCINIEGA',
    authorizationUSU: 'RARCINIEGA',
    closingUSU: 'RARCINIEGA',
    applicationUSU: 'NULL',
    cancellationUSU: 'NULL',
    goodNumberF: 1946809,
    trial785: 'T',
  },
  {
    id: 57,
    description: 'FOLIO: 00037, DELEGACION: DELEGACIÓN REGIONAL NORESTE',
    packageType: 2,
    amount: 176.2,
    elaborationDate: '2012-11-13',
    captureDate: '2012-11-13',
    capturehcDate: '2012-11-13',
    packageStatus: 'C',
    classificationNumber: 785,
    targetNumber: 2,
    unit: 'PAR',
    warehouseNumber: 9651,
    registryNumber: 314736890,
    status: 'ADM',
    tranEmiAutNumber: 120,
    validationDate: '2012-11-29',
    authorizationDate: '2012-11-29',
    closingDate: '2012-11-29',
    applicationDate: 'NULL',
    packageCVE: 'CONV/RT/SAT/DRNE/DRNE/00037/12/11',
    cancellationDate: 'NULL',
    universalFolio: 1241456,
    paragraph1:
      '- - - En la Ciudad de Apodaca, siendo las 11:00 horas, del día 13 de Noviembre de 2012, se encuentran presentes en la Bodega ubicada en la calle de Jose Lopez Portillo No. 2000 de esta Ciudad, el C. Roberto Javier Gonzalez Gonzalez   con cargo de Gerente Corporativo de la empresa TDR Transportes S.A de C.V. y el C. Rolando Arciniega Fuantos adscrito a la Delegación regional Noreste del Servicio de Administración y Enajenación de Bienes (SAE), Organismo Descentralizado de la Administración Pública Federal; ambos con el fin de llevar a cabo la validación y conversión de los bienes transferidos al SAE.- - - - - - - - - - - - - - - - - - - - - - - - - - - -\n- - -Interviene como testigo de asistencia el C.Julio Hernandez García - - - - - - - -  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\n-------------------------------------------------- A N T E C E D E N T E S --------------------------------------------------- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\n- - - l. Los bienes fueron transferidos al SAE por el Servicio de Administración Tributaria, con fundamento en los artículos 3 de la LFAEBSP, 12 y 13 del Reglamento de la ley en comento. - - \n- - - II.- Los bienes sujetos ha validación y conversión de unidad, se encuentran en administración del SAE y bajo la custodia de TDR Transportes S.A de C.V. los cuales se incorporan a este procedimiento a efecto de facilitar la ejecución de su destino.- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\n----------------------------------------------------- DECLARACIONES ------------------------------------------------------\n- - - PRIMERA.- El C. Rolando Arciniega Fuantos manifiesta que los bienes que fueron transferidos al SAE se encuentran bajo su custodia y con el fin de dar cumplimento al destino final sugerido por la Entidad Transferente se sujetaran a un procedimiento de validación y conversión en virtud de que fueron puestos a disposición con un tipo de unidad diferente al de kilogramos.- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - \n- - - SEGUNDA.- Que para realizar el proceso de validación y conversión se verifican las amountes físicas, contra las amountes señaladas en los documentos y registros oficiales para posteriormente determinar el valor de conversión a kilogramos. - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - \n- - - TERCERA.- La conversión integra un paquete de bienes, que puede estar conformado por uno o varios registros y que son consistentes en las siguientes características: a) Autoridad SAT - COMERCIO EXTERIOR, b) Clasificador del bien TENIS, c) Estatus del bien ADM, d) Etiqueta de destino DONACION, e) La custodia se encuentra a cargo del almacén TDR ALMACEN MONTERREY, y f) La administración de los bienes esta a cargo de la Delegación Regional Noreste.- - - - - - - - - - - - -',
    paragraph2:
      '- - - CUARTA.- Una vez validada la existencia física de los bienes descritos en la declaratoria anterior, se determinó que su valor de conversión a kilogramos corresponde a 176.2',
    paragraph3:
      '- - - QUINTA.- El valor de conversión a kilogramos determinado en la Cláusula Cuarta es una referencia para ejecutar el destino de Donación de los bienes  que conforman en paquete, por lo que cada registro conserva la referencia de amount y unidad recibidas del transferente - - - - - - - - - - -  -- - - - - - - - - - - - - - - - - - - - - - - - -  - - - - - - - - - - - - - - - - - - - - - -\n- - - - - - - - - - - - - - - - - - - - - - - - - - -  CIERRE DEL ACTA -------------------------------------------------\nSe da por concluida la presente acta, siendo las 11:30 horas del día 13 de Noviembre de 2012, firmando  al margen y al calce por las personas que en ella intervienen, para todos los efectos a que haya lugar. - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\n\n\n\nCUSTODIA, VALIDA Y EJECUTA CONVERSIÓN\n\t\t\t\n      \n   POR EL S.A.E.                                        POR EL ALMACEN TDR MONTERREY\n\nC. Rolando Arciniega Fuantos                 C. Roberto Javier Gonzalez Gonzalez  \n\nTESTIGO DE ASISTENCIA\n\nC.Julio Hernandez García\n\nÚltima página del Acta Administrativa de Validación y Conversión de Bienes con Clave CONV/RT/SAT/DRNE/DRNE/00037/12/11 de fecha 13 de  Noviembre de 2012, constante de 5 fojas. - - - - - - - - - - - -',
    delegationNumber: 4,
    elaborationUSU: 'RARCINIEGA',
    validationUSU: 'RARCINIEGA',
    authorizationUSU: 'RARCINIEGA',
    closingUSU: 'RARCINIEGA',
    applicationUSU: 'NULL',
    cancellationUSU: 'NULL',
    goodNumberF: 1959650,
    trial785: 'T',
  },
];
