export const DATA = [
  {
    fileNumber: 222,
    requestNumber: 1037,
    subject: 'SOLICITUD DE TRANSFERENCIA',
    requestDate: '25-oct-2017',
    receptionDate: '',
    senderName: 'LAURA ALVAREZ',
    senderPosition: 'DIRECTOR',
    senderPhone: '5500000000',
    senderEmail: 'OST12551@SAT.COM',
    regionalDelegation: 'BAJA CALIFORNIA',
    state: 'BAJA CALIFORNIA',
    transferent: 'SAT - COMERCIO EXTERIOR',
    emitter: 'AGAO',
    goods: [
      {
        allocatorAssetName: '',
        taxpayerResult: 'tax',
        origin: 'Invenatarios A.',
        description: 'Candil Decorativo',
        key: '801-69-68-65-2',
        reservedAmount: '20',
        availableAmount: '12',
        destination: 'Admon',
        subInventory: '44',
        proceedingsNumb: 5443,
        transferRequestNumber: 334343,
        managementNumb: 605,
        inventoryNumb: 654,
      },
      {
        allocatorAssetName: '',
        taxpayerResult: 'tax',
        origin: 'Invenatarios B.',
        description: 'Candil Decorativo',
        key: '801-69-68-65-5',
        reservedAmount: '20',
        availableAmount: '12',
        destination: 'Admon',
        subInventory: '44',
        proceedingsNumb: 5443,
        transferRequestNumber: 334343,
        managementNumb: 605,
        inventoryNumb: 654,
      },
      {
        allocatorAssetName: '',
        taxpayerResult: 'tax',
        origin: 'Invenatarios C.',
        description: 'Candil Decorativo',
        key: '801-69-68-65-9',
        reservedAmount: '20',
        availableAmount: '12',
        destination: 'Admon',
        subInventory: '44',
        proceedingsNumb: 5443,
        transferRequestNumber: 334343,
        managementNumb: 605,
        inventoryNumb: 654,
      },
    ],
  },
  {
    fileNumber: 202,
    requestNumber: 968,
    subject: 'SOLICITUD DE TRANSFERENCIA',
    requestDate: '13-oct-2017',
    receptionDate: '',
    senderName: 'PRUEBA EJEMPLO',
    senderPosition: 'CARGO REMITIDO',
    senderPhone: '1111100000',
    senderEmail: 'ANDRES_MENDOZA@SAT.COM',
    regionalDelegation: 'BAJA CALIFORNIA',
    state: 'BAJA CALIFORNIA',
    transferent: 'SAT - COMERCIO EXTERIOR',
    emitter: 'AGAO',
    goods: [
      {
        allocatorAssetName: '',
        taxpayerResult: 'tax',
        origin: 'Invenatarios A.',
        description: 'Candil Decorativo',
        key: '801-69-68-65-2',
        reservedAmount: '20',
        availableAmount: '12',
        destination: 'Admon',
        subInventory: '44',
        proceedingsNumb: 5443,
        transferRequestNumber: 334343,
        managementNumb: 605,
        inventoryNumb: 654,
      },
      {
        allocatorAssetName: '',
        taxpayerResult: 'tax',
        origin: 'Invenatarios B.',
        description: 'Candil Decorativo',
        key: '801-69-68-65-5',
        reservedAmount: '20',
        availableAmount: '12',
        destination: 'Admon',
        subInventory: '44',
        proceedingsNumb: 5443,
        transferRequestNumber: 334343,
        managementNumb: 605,
        inventoryNumb: 654,
      },
      {
        allocatorAssetName: '',
        taxpayerResult: 'tax',
        origin: 'Invenatarios C.',
        description: 'Candil Decorativo',
        key: '801-69-68-65-9',
        reservedAmount: '20',
        availableAmount: '12',
        destination: 'Admon',
        subInventory: '44',
        proceedingsNumb: 5443,
        transferRequestNumber: 334343,
        managementNumb: 605,
        inventoryNumb: 654,
      },
    ],
  },
  {
    fileNumber: 41,
    requestNumber: 1038,
    subject: 'SOLICITUD DE TRANSFERENCIA',
    requestDate: '25-oct-2017',
    receptionDate: '',
    senderName: 'LAURA ALVAREZ',
    senderPosition: 'DIRECTOR',
    senderPhone: '5500000000',
    senderEmail: 'OST12551@SAT.COM',
    regionalDelegation: 'BAJA CALIFORNIA',
    state: 'BAJA CALIFORNIA',
    transferent: 'SAT - COMERCIO EXTERIOR',
    emitter: 'AGAO',
    goods: [
      {
        allocatorAssetName: '',
        taxpayerResult: 'tax',
        origin: 'Invenatarios A.',
        description: 'Candil Decorativo',
        key: '801-69-68-65-2',
        reservedAmount: '20',
        availableAmount: '12',
        destination: 'Admon',
        subInventory: '44',
        proceedingsNumb: 5443,
        transferRequestNumber: 334343,
        managementNumb: 605,
        inventoryNumb: 654,
      },
      {
        allocatorAssetName: '',
        taxpayerResult: 'tax',
        origin: 'Invenatarios B.',
        description: 'Candil Decorativo',
        key: '801-69-68-65-5',
        reservedAmount: '20',
        availableAmount: '12',
        destination: 'Admon',
        subInventory: '44',
        proceedingsNumb: 5443,
        transferRequestNumber: 334343,
        managementNumb: 605,
        inventoryNumb: 654,
      },
      {
        allocatorAssetName: '',
        taxpayerResult: 'tax',
        origin: 'Invenatarios C.',
        description: 'Candil Decorativo',
        key: '801-69-68-65-9',
        reservedAmount: '20',
        availableAmount: '12',
        destination: 'Admon',
        subInventory: '44',
        proceedingsNumb: 5443,
        transferRequestNumber: 334343,
        managementNumb: 605,
        inventoryNumb: 654,
      },
    ],
  },
];
