import { DatePickerComponent } from 'src/app/shared/render-components/date-picker/date-picker.component';

export const columnsKeysProceddings = {
  0: {
    title: 'Tipo',
    sort: false,
    editable: true,
  },
  1: {
    title: 'Prog.',
    sort: false,
  },
  2: {
    title: 'Transferente',
    sort: false,
  },
  3: {
    title: 'Área',
    sort: false,
  },
  4: {
    title: 'Usuario',
    sort: false,
  },
  5: {
    title: 'Folio',
    sort: false,
  },
  6: {
    title: 'Año',
    sort: false,
    type: 'number',
  },
  7: {
    title: 'Mes',
    sort: false,
    type: 'number',
  },
};

export const settingKeysProceedings = {
  selectMode: false,
  attr: {
    class: 'table-bordered',
  },
  pager: {
    display: false,
  },
  actions: {
    columnTitle: 'Acciones',
    position: 'left',
    add: false,
    edit: true,
    delete: false,
  },
  edit: {
    editButtonContent: '<i class="fa fa-pencil-alt text-warning mx-2"></i>',
    saveButtonContent: '<i class="fa fa-solid fa-check text-success mx-2"></i>',
    cancelButtonContent: '<i class="fa fa-solid fa-ban text-danger mx-2"></i>',
    confirmSave: true,
  },
  hideSubHeader: true,
  columns: columnsKeysProceddings,
};
export const columnsGoods = {
  no_bien: {
    title: 'Bien',
    type: 'number',
    sort: false,
    editable: false,
  },
  estatus: {
    title: 'Est',
    type: 'string',
    sort: false,
    editable: false,
  },
  fec_aprobacion_x_admon: {
    title: 'Inicio',
    sort: false,
    editor: {
      type: 'custom',
      component: DatePickerComponent,
    },
  },
  fec_indica_usuario_aprobacion: {
    title: 'Fin',
    sort: false,
    editor: {
      type: 'custom',
      component: DatePickerComponent,
    },
  },
  tipo_bien: {
    title: 'Tipo Bien',
    type: 'string',
    sort: false,
    editable: false,
  },
  descripcion: {
    title: 'Descripción del bien',
    // type: 'custom',
    sort: false,
    editable: false,
    // renderComponent: TextAreaRenderComponent,
  },
  no_expediente: {
    title: 'Expediente',
    type: 'number',
    sort: false,
    editable: false,
  },
  cantidad: {
    title: 'Cantidad',
    type: 'number',
    sort: false,
    editable: false,
  },

  destino: {
    title: 'Indi Dest',
    type: 'string',
    sort: false,
    editable: false,
  },
};
export const settingsGoods = {
  pager: {
    display: false,
  },
  attr: {
    class: 'table-bordered',
  },
  selectedRowIndex: -1,
  sort: false,
  hideSubHeader: true,
  mode: 'inline',
  selectMode: 'multi',
  noDataMessage: 'No se encontrarón registros',
  edit: {
    editButtonContent: '<i class="fa fa-pencil-alt text-warning mx-2"></i>',
    saveButtonContent: '<i class="fa fa-solid fa-check text-success mx-2"></i>',
    cancelButtonContent: '<i class="fa fa-solid fa-ban text-danger mx-2"></i>',
    confirmSave: true,
  },
  actions: {
    columnTitle: 'Acciones',
    position: 'right',
    add: false,
    edit: true,
    delete: true,
  },
  delete: {
    deleteButtonContent: '<i class="fa fa-trash text-danger mx-2"></i>',
    confirmDelete: true,
  },
  columns: {},
};

// export const dataDummy: IGoodsByProceeding[] = [
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30664,
//     estatus: 'CPR',
//     descripcion: 'CUADRO DE MADERA',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30671,
//     estatus: 'CPR',
//     descripcion: 'APARATO PARA EJERCICIOS',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30653,
//     estatus: 'CPR',
//     descripcion: 'VASOS DE VIDRIO',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 27,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30670,
//     estatus: 'CPR',
//     descripcion: 'PORTARRETRATOS METALICO',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 4,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30658,
//     estatus: 'CPR',
//     descripcion: 'MESA DE HIERRO FORJADO',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30669,
//     estatus: 'CPR',
//     descripcion: 'PORTAVELAS DE HIERRO FORJADO',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30668,
//     estatus: 'CPR',
//     descripcion: 'TORRES PORTAVELAS DE CERAMICA',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 3,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30652,
//     estatus: 'CPR',
//     descripcion: 'PLATOS DE PORCELANA DIVERSOS TAMAÑOS',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 70,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30667,
//     estatus: 'CPR',
//     descripcion: 'MACETERO DE HORNATO',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30651,
//     estatus: 'CPR',
//     descripcion: 'TOSTADOR DE PAN',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30661,
//     estatus: 'CPR',
//     descripcion: 'PALMERA DE HORNATO CON MACETERO DE MIMBRE',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30650,
//     estatus: 'CPR',
//     descripcion: 'TOSTADOR ELECTRICO',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30649,
//     estatus: 'CPR',
//     descripcion: 'BATIDORA ELECTRICA',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30666,
//     estatus: 'CPR',
//     descripcion: 'PIEZAS DE COBRE DE DIVERSAS FORMAS Y TAMAÑOS',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 10,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30660,
//     estatus: 'CPR',
//     descripcion: 'PORTAVELAS METALICO DE PARED',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30659,
//     estatus: 'CPR',
//     descripcion: 'CAJA FUERTE',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30654,
//     estatus: 'CPR',
//     descripcion: 'COPAS DE CRISTAL GRABADAS, DIVERSOS UTENSILIOS DE COCINA',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 27,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30665,
//     estatus: 'CPR',
//     descripcion: 'JUEGO DE 3 PIEZAS DE BARRO',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30657,
//     estatus: 'CPR',
//     descripcion: 'PIEZAS DE HORNATO DE HIERRO FORJADO Y BARRO',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 8,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30674,
//     estatus: 'CPR',
//     descripcion: 'PESAS Y 3 DISCOS DE DIVERSOS PESOS',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30675,
//     estatus: 'CPR',
//     descripcion: 'CUADROS AL OLEO',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 2,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30633,
//     estatus: 'CPR',
//     descripcion: 'SECADORA',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30673,
//     estatus: 'CPR',
//     descripcion: 'MANCOERNILLAS PARA EJERCICIOS DE DIVERSOS TAMAÑOS Y PESOS',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 8,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30677,
//     estatus: 'CPR',
//     descripcion: 'COMPUTADORA',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30678,
//     estatus: 'CPR',
//     descripcion: 'IMPRESORA',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30679,
//     estatus: 'CPR',
//     descripcion: 'PAR DE BOCINAS',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30680,
//     estatus: 'CPR',
//     descripcion: 'RECEPTOR DE SATELITE',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30681,
//     estatus: 'CPR',
//     descripcion: 'ESCRITORIO MODULAR PARA COMPUTADORA',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30684,
//     estatus: 'CPR',
//     descripcion: 'PORTAMACETERO METALICO',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30685,
//     estatus: 'CPR',
//     descripcion: 'VAPORIZADORA MULTIUSOS',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30686,
//     estatus: 'CPR',
//     descripcion: 'CUADRO CON LA IMAGEN DE LA VIRGEN DE GUADALUPE',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30701,
//     estatus: 'CPR',
//     descripcion: 'CRISTO DE MADERA Y ACRILICO',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30702,
//     estatus: 'CPR',
//     descripcion: 'FLORERO DE CERAMICA',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30703,
//     estatus: 'CPR',
//     descripcion: 'ALHAJERO DE MADERA',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30704,
//     estatus: 'CPR',
//     descripcion: 'CANDELABRO DE METAL',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30705,
//     estatus: 'CPR',
//     descripcion: 'LAMPARA EN FORMA DE PECERA',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30707,
//     estatus: 'CPR',
//     descripcion: 'BAUL',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30709,
//     estatus: 'CPR',
//     descripcion: 'MUEBLE DE MADERA TIPO COMODA',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30714,
//     estatus: 'CPR',
//     descripcion: 'CRISTO DE MADERA',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30715,
//     estatus: 'CPR',
//     descripcion: 'SILLAS DE PLASTICO',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30720,
//     estatus: 'CPR',
//     descripcion: 'MESAS DE PLASTICO',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 2,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30721,
//     estatus: 'CPR',
//     descripcion: 'SILLAS DE PLASTICO',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 3,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30722,
//     estatus: 'CPR',
//     descripcion: 'BICICLETA FIJA',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30723,
//     estatus: 'CPR',
//     descripcion: 'SILLAS PARA MONTAR TIPO CHARRO',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 4,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30724,
//     estatus: 'CPR',
//     descripcion: 'TRICICLO PARA BEBE',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30725,
//     estatus: 'CPR',
//     descripcion: 'MAQUINA PODADORA MANUAL',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30726,
//     estatus: 'CPR',
//     descripcion: 'PODADORA',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30728,
//     estatus: 'CPR',
//     descripcion: 'PERRERA EN MAL ESTADO Y SUCIA',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30729,
//     estatus: 'CPR',
//     descripcion: 'COLUMPIO EN MAL ESTADO Y DESARMADO',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30730,
//     estatus: 'CPR',
//     descripcion: 'CUATRIMOTO',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30731,
//     estatus: 'CPR',
//     descripcion: 'VEHICULO GOCAR',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121779,
//     estatus: 'CPR',
//     descripcion: 'ARTICULOS DE LIMPIEZA.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121781,
//     estatus: 'CPR',
//     descripcion: 'UN ORGANO MARCA YAMAHA, MODELO PSR-220',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121782,
//     estatus: 'CPR',
//     descripcion: 'PINTURA EN TELA PAISAJE',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121783,
//     estatus: 'CPR',
//     descripcion: 'CUADRO MOTIVO DIVINA CENA EN RELIEVE',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121784,
//     estatus: 'CPR',
//     descripcion: 'PINTURA EN TELA BODEGON',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121661,
//     estatus: 'CPR',
//     descripcion:
//       'INMUEBLE UBICADO EN CALLE FARALLON NUMERO 3071, FRACCIONAMIENTO PLAYAS DE TIJUANA SECCION COSTA HERMOSA,',
//     tipo_bien: 'BIENES INMUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121662,
//     estatus: 'CPR',
//     descripcion:
//       ' LOCAL A-7 DEL CENTRO COMERCIAL "PLACITA CORONADO" UBICADO EN PASEO ESTRELLA DEL MAR, FRACCIONAMIENTO PLAYAS DE TIJUANA SECCION CORONADO',
//     tipo_bien: 'BIENES INMUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 122188,
//     estatus: 'CPR',
//     descripcion:
//       'TRINCHADOR CON BASE EN HIERRO FORJADO CUBIERTA EN CRISTAL BISELADO RECTANGULAR',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 122189,
//     estatus: 'CPR',
//     descripcion: 'BOCINA MARCA YAMAHA',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121668,
//     estatus: 'CPR',
//     descripcion:
//       'INMUEBLE UBICADO EN AVENIDA ABELARDO L. RODRIGUEZ NUMERO 1403, ZONA URBANA, RIO TIJUANA BAJA CALIFORNIA;',
//     tipo_bien: 'BIENES INMUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121670,
//     estatus: 'CPR',
//     descripcion: 'U N SOFA',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121671,
//     estatus: 'CPR',
//     descripcion: 'UN SILLON LOVE SIT',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121672,
//     estatus: 'CPR',
//     descripcion:
//       'DOS SILLONES CON REMATES DE MADERA, TODOS ESTOS TAPIZADOS EN TELA COLOR BEIGE MOTIVOS FLORALES,',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 2,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121673,
//     estatus: 'CPR',
//     descripcion: 'MUEBLE SILLON CON MESA ADAPTADA PARA TELEFONO',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121676,
//     estatus: 'CPR',
//     descripcion:
//       'TRES BANCOS PARA BAR GIRATORIOS CON RESPALDO EN MADERA DE PINO COLOR CAFE',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 3,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121678,
//     estatus: 'CPR',
//     descripcion: 'UN MONITOR MARCA NEC, MUY USADO Y DETERIORADO',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121679,
//     estatus: 'CPR',
//     descripcion:
//       'UNA IMPRESORA DE LA MARCA EPSSON, COLOR BLANCO EN REGULAR ESTADO',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121680,
//     estatus: 'CPR',
//     descripcion: 'DOS MALETAS DE COLOR AZUL',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 2,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121681,
//     estatus: 'CPR',
//     descripcion: 'ROPA DIVERSA',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121682,
//     estatus: 'CPR',
//     descripcion: 'DOS PIEZAS EN TELA COLOR CAFE TIPO ESQUINERO MESA DE CENTRO',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 2,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121683,
//     estatus: 'CPR',
//     descripcion:
//       'DOS MESAS ESQUINERAS BASES EN HIERRO FORJADO HECHURA ESPECIAL Y CUBIERTAS EN CRISTAL BISELADO, TRINCHADOR MISMO ESTILO',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 3,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 122217,
//     estatus: 'CPR',
//     descripcion: 'UN TOCADOR EN MADERA LISTONADA CUBIERTO CON FORMAICA',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 122218,
//     estatus: 'CPR',
//     descripcion: 'UNA TELEVISION DE 29" MARCA SONY TRINITON PANTALLA PLANA',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121684,
//     estatus: 'CPR',
//     descripcion: 'HERRAMIENTAS PARA CHIMENEA EN HIERRO FORJADO',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121685,
//     estatus: 'CPR',
//     descripcion: 'UN CUADRO EN POLIESTER MOTIVO HUMANOS DESNUDOS',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121686,
//     estatus: 'CPR',
//     descripcion: 'UN CUADRO PAISAJE CON PUERTA DE MADERA AL CENTRO',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121687,
//     estatus: 'CPR',
//     descripcion: 'UN ANTE COMEDOR BASE DE MADERA CUBIERTA DE CRISTAL REDONDA',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121690,
//     estatus: 'CPR',
//     descripcion: 'CUATRO SILLAS EN MADERA CUBIERTAS EN TELA COLOR CAFE',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 4,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121691,
//     estatus: 'CPR',
//     descripcion:
//       'REFRIGERADOR MARCA KENMORE DOS PUERTAS CON DESPACHADOR DE AGUA Y HIELOS COLOR BLANCO',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121692,
//     estatus: 'CPR',
//     descripcion: 'HORNO DE MICROONDAS METALICO MARCA SILVANA',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121693,
//     estatus: 'CPR',
//     descripcion: 'EXTRACTOR DE JUGOS MARCA BRENTWOOD',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121694,
//     estatus: 'CPR',
//     descripcion: 'LICUADORA MARCA HAMIL TON BEACH',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121695,
//     estatus: 'CPR',
//     descripcion: 'TELEVISION DE 14" MARCA TOSHIBA',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121696,
//     estatus: 'CPR',
//     descripcion: 'CUADRO EN TELA BODEGON MARCO DE MADERA TALLADA',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121697,
//     estatus: 'CPR',
//     descripcion: 'UTENSILIOS PROPIOS DE COCINA',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121698,
//     estatus: 'CPR',
//     descripcion: 'COLCHON Y BOX CON BASE MATRIMONIAL',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 2,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121699,
//     estatus: 'CPR',
//     descripcion: 'CABECERA TUBULAR CROMADA',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121700,
//     estatus: 'CPR',
//     descripcion:
//       'TELEVISION DE 14" CON VIDEO CASETERA INTEGRADA MARCA TOSHIBA, COLOR NEGRO',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121701,
//     estatus: 'CPR',
//     descripcion: 'TELEVISION DE 21" MARCA GOLOSTAR COLOR NEGRO',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121939,
//     estatus: 'CPR',
//     descripcion: 'UN REPRODUCTOR DE DVD MARCA SANYO',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121940,
//     estatus: 'CPR',
//     descripcion: 'REPRODUCTOR DE VIDEOCASSETES FORMATO VHS',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121941,
//     estatus: 'CPR',
//     descripcion: 'UN MINI COMPONENTE MARCA PHILLIPS',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 122220,
//     estatus: 'CPR',
//     descripcion: 'UN REPRODUCTOR DE DVD DE LA MARCA SANYO',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 122221,
//     estatus: 'CPR',
//     descripcion: 'UNA VIDEO CASETERA FORMATO VHS MARCA JVC',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 122222,
//     estatus: 'CPR',
//     descripcion: 'UN CORRAL PARA NINOS MARCA CENTURY',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 122223,
//     estatus: 'CPR',
//     descripcion: 'COLCHON Y BOX MATRIMONIAL',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 2,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 122224,
//     estatus: 'CPR',
//     descripcion: 'DOS BUROES',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 2,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121703,
//     estatus: 'CPR',
//     descripcion: 'BURRO DE PLANCHAR',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121704,
//     estatus: 'CPR',
//     descripcion: 'ARTICULOS DECORATIVOS DIVERSOS',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121705,
//     estatus: 'CPR',
//     descripcion: 'HERRAMIENTA DIVERSA',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121706,
//     estatus: 'CPR',
//     descripcion: 'ASPIRADORA MARCA EUREKA MODELO WIDE TRAK',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121707,
//     estatus: 'CPR',
//     descripcion: ' ASPIRADORA MARCA SHOP VAC MODELO 210',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121709,
//     estatus: 'CPR',
//     descripcion: 'MINI COMPONENTE MARCA PHILLIPS',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121710,
//     estatus: 'CPR',
//     descripcion: 'MONITOR SIN MARCA VISIBLE',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121711,
//     estatus: 'CPR',
//     descripcion: 'MOUSE Y TECLADO MARCA TOSHIBA',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 2,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121712,
//     estatus: 'CPR',
//     descripcion: 'BOCINAS PARA COMPUTADORA SIN MARCA VISIBLE',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121713,
//     estatus: 'CPR',
//     descripcion:
//       'UNA CAMARA DE VIDEO GRABACION FORMATO VHS MARCA PANASONIC CON SUS ADITAMENTOS Y ESTUCHE',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121714,
//     estatus: 'CPR',
//     descripcion: 'LAMPARA DE PEDESTAL EN COLOR NEGRO',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121715,
//     estatus: 'CPR',
//     descripcion: 'ROPA',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121716,
//     estatus: 'CPR',
//     descripcion: 'JUGUETES DIVERSOS',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121718,
//     estatus: 'CPR',
//     descripcion: 'CABECERA CON REMATES EN HIERRO FORJADO',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121719,
//     estatus: 'CPR',
//     descripcion: 'BUROES DE MADERA BARNIZADOS EN COLOR BEIGE',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 2,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121720,
//     estatus: 'CPR',
//     descripcion: 'MESA DE MADERA CON CUBIERTA REDONDA',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121945,
//     estatus: 'CPR',
//     descripcion: 'JUGUETES DIVERSOS',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121946,
//     estatus: 'CPR',
//     descripcion: 'MINI COMPONENTE SIN MARCA VISIBLE COLOR NEGRO',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121949,
//     estatus: 'CPR',
//     descripcion: 'UNA IMPRESORA MARCA HEWLET PACKARD',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121950,
//     estatus: 'CPR',
//     descripcion: 'UNA TELEVISION 21" MARCA MAGESTIC COLOR NEGRO',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121954,
//     estatus: 'CPR',
//     descripcion: 'UN MINI COMPONENTE MARCA AUDIOVOX',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121955,
//     estatus: 'CPR',
//     descripcion:
//       'TELEVISION 29" MARCA MAGNAVOX, REPRODUCTOR DE VIDEOCASETES FORMATO VHS',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121959,
//     estatus: 'CPR',
//     descripcion:
//       'UN SISTEMA DE TEATRO EN CASA COMPUESTO POR DOS BOCINAS MARCA YAMAHA Y TRES DE LA MARCA MORDAUNT',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 122239,
//     estatus: 'CPR',
//     descripcion: 'UNA TELEVISION DE LA MARCA JVC- 21',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 122240,
//     estatus: 'CPR',
//     descripcion: 'UNA VIDEO CASETERA',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 122241,
//     estatus: 'CPR',
//     descripcion: 'UN MINI COMPONENTE MARCA SANYO',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 122242,
//     estatus: 'CPR',
//     descripcion: 'UN MUEBLE PARA TV',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 122243,
//     estatus: 'CPR',
//     descripcion: 'COLCHON Y BOX MATRIMONIAL',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 2,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 122244,
//     estatus: 'CPR',
//     descripcion: 'UNA CABECERA',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 122245,
//     estatus: 'CPR',
//     descripcion: 'DOS BUROES',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 2,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 122246,
//     estatus: 'CPR',
//     descripcion: 'UN TOCADOR CON LUNA EN MADERA DE PINO',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 2,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 122247,
//     estatus: 'CPR',
//     descripcion: 'UNA TELEVISION MARCA JVC 29",',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 122249,
//     estatus: 'CPR',
//     descripcion: 'UN MONITOR PARA COMPUTADORA PANTALLA PLANA MARCA COMPAQ',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 122250,
//     estatus: 'CPR',
//     descripcion: 'TECLADO',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 122251,
//     estatus: 'CPR',
//     descripcion: 'IMPRESORA MARCA HEWLET PACKARD',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 122252,
//     estatus: 'CPR',
//     descripcion: 'UN PAR DE BOCINAS DE LA MARCA JBL',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 2,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 122253,
//     estatus: 'CPR',
//     descripcion: 'UN REPRODUCTOR DE CDS MARCA PHILLIPS',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 122254,
//     estatus: 'CPR',
//     descripcion: 'ESTANCIA PARA TELEVISION',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121721,
//     estatus: 'CPR',
//     descripcion: 'TOCADOR CON LUNA MISMO ESTILO',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 2,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121722,
//     estatus: 'CPR',
//     descripcion: 'TELEVISION 29" MARCA QUAZAR',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121723,
//     estatus: 'CPR',
//     descripcion: 'VIDEO CASSETERA FORMATO VHS MARCA EMERSON',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121724,
//     estatus: 'CPR',
//     descripcion: 'LAMPARA DE PEDESTAL COLOR BLANCO',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121728,
//     estatus: 'CPR',
//     descripcion: 'TELEVISION 21" MARCA MAGNAVOX',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121730,
//     estatus: 'CPR',
//     descripcion:
//       'RADIO GRABADORA DE LA MARCA LASONIC COLOR NEGRO MODELO RC-975',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121731,
//     estatus: 'CPR',
//     descripcion:
//       'BICICLETAS DE LAS DENOMINADAS DE MONTAÑA CON AMORTIGUADORES EN TIJERA Y CUADRO',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 2,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121732,
//     estatus: 'CPR',
//     descripcion:
//       'COMEDOR NUEVO Y EMBALADO BASE DE MADERA CUBIERTA DE CRISTAL, REDONDA',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121733,
//     estatus: 'CPR',
//     descripcion: 'SILLAS ASIENTOS EN TELA COLOR BEIGE',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 4,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121960,
//     estatus: 'CPR',
//     descripcion: 'UN CENTRO DE CONTROL DE VIDEO DE LA MARCA SONY',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121961,
//     estatus: 'CPR',
//     descripcion:
//       'UNA CONSOLA DE VIDEO JUEGOS MARCA SONY, NOMBRE PLAY STATION 2, CON CONTROLES',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121965,
//     estatus: 'CPR',
//     descripcion:
//       'ESCULTURA DE HOMBRE ESTILO GRIEGO APROXIMADAMENTE DE 90 CENTIMETROS DE ALTURA COLOR NEGRO CON MATICES DORADOS',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121966,
//     estatus: 'CPR',
//     descripcion:
//       'ESCULTURA DE MUJER ESTILO GRIEGO APROXIMADAMENTE DE 60 CENTIMETROS DE ALTURA ,COLOR NEGRO CON MATICES DORADOS',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121967,
//     estatus: 'CPR',
//     descripcion: 'CUATRO CUADROS EN RELIEVE ESTILO ROMANO MARCOS EN MADERA.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 4,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121970,
//     estatus: 'CPR',
//     descripcion: 'CUADRO EN RELIEVE MOTIVOS RELIGIOSOS MARCO EN MADERA',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121971,
//     estatus: 'CPR',
//     descripcion:
//       'TRINCHADOR CON BASE IMITACION PIEDRA COLOR BLANCO CUBIERTA EN CRISTAL BISELADO',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121974,
//     estatus: 'CPR',
//     descripcion:
//       'ANTE COMEDOR REDONDO PARA CUATRO PERSONAS BASE EN HIERRO FORJADO CUBIERTA EN CRISTAL BISELADO',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 122272,
//     estatus: 'CPR',
//     descripcion: 'UNA MESA DE CENTRO CUBIERTA DE CRISTAL COMO BASE UNA MACETA',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121742,
//     estatus: 'CPR',
//     descripcion:
//       'CUADRO MOTIVO MUJER, MARCA EN MADERA BARNIZADA EN COLOR DORADO',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121743,
//     estatus: 'CPR',
//     descripcion:
//       'MESA DE BAR FORMA OCTAGONAL CON TABLERO DE AJEDREZ EN SU BASE',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121745,
//     estatus: 'CPR',
//     descripcion: 'UN REPRODUCTOR DE DISCOS COMPACTOS DE LA MARCA SONY',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121746,
//     estatus: 'CPR',
//     descripcion: 'REPRODUCTOR DE CASSETES PROFESIONAL MARCA PIONEER',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121747,
//     estatus: 'CPR',
//     descripcion: 'UN AMPLIFICADOR MARCA SONG MATE.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121749,
//     estatus: 'CPR',
//     descripcion: 'HORNO DE MICROONDAS COLOR BLANCO MARCA SAMSUNG',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121750,
//     estatus: 'CPR',
//     descripcion: 'UNA LICUADORA MARCA OSTERIZER',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121752,
//     estatus: 'CPR',
//     descripcion: 'UNA IMPRESORA MARCA APOLO',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121755,
//     estatus: 'CPR',
//     descripcion: 'GRABADORA MARCA CLASSIC',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121756,
//     estatus: 'CPR',
//     descripcion: 'UNA TELEVISION DE 14" MARCA TOSHIBA',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121975,
//     estatus: 'CPR',
//     descripcion:
//       'SILLAS EN MADERA CON ASIENTOS EN TELA COLOR BEIGE CON MOTIVOS FLORALES',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121978,
//     estatus: 'CPR',
//     descripcion: 'UN HORNO DE MICROONDAS COLOR BLANCO MARCA EMERSON',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121980,
//     estatus: 'CPR',
//     descripcion: 'UN HORNO ELECTRICO DE LA MARCA TOSTMASTER',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121981,
//     estatus: 'CPR',
//     descripcion: 'UN SERVIDOR DE AGUA DE BOTELLON DE LA MARCA RUBBERMAID',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121986,
//     estatus: 'CPR',
//     descripcion: 'UNA ASPIRADORA DE LA MARCA EUREKA COLOR AZUL',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121987,
//     estatus: 'CPR',
//     descripcion: 'HERRAMIENTA DIVERSA',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 121988,
//     estatus: 'CPR',
//     descripcion: 'ARTICULOS DE JARDINERIA',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 122274,
//     estatus: 'CPR',
//     descripcion: 'UNA TELEVISION DE 29" MARCA JVC',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 122275,
//     estatus: 'CPR',
//     descripcion: 'UNA CONSOLA DE VIDEO JUEGOS MARCA MICROSOFT, NOMBRE X-BOX',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 122276,
//     estatus: 'CPR',
//     descripcion: 'BOCINA MARCA JBL',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 122277,
//     estatus: 'CPR',
//     descripcion: 'DECK REPRODUCTOR DE CASETES, MARCA KENWOOD',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 122278,
//     estatus: 'CPR',
//     descripcion: 'UN REPRODUCTOR DE DVD MULTIREGION MARCA JVC',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 122279,
//     estatus: 'CPR',
//     descripcion: 'UN CONTROLADOR CENTRAL DE VIDEO MARCA SONY',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 122280,
//     estatus: 'CPR',
//     descripcion: 'UN REPRODUCTOR PARA 200 DISCOS COMPACTOS MARCA SONY',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30636,
//     estatus: 'CPR',
//     descripcion: 'MESAS DE PLASTICO',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 2,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30632,
//     estatus: 'CPR',
//     descripcion: 'LAVADORA',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30635,
//     estatus: 'CPR',
//     descripcion: 'MESAS RUSTICAS DE HIERRO FORJADO DIFERENTES TAMAÑOS',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 3,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125536,
//     estatus: 'CPR',
//     descripcion: 'CAMA INDIVIDUAL.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125537,
//     estatus: 'CPR',
//     descripcion: 'BUROE.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125538,
//     estatus: 'CPR',
//     descripcion: 'TOCADOR CON OCHO CAJONES Y LUNA.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 2,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125539,
//     estatus: 'CPR',
//     descripcion: 'CAMA QUEEN SIZE.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125540,
//     estatus: 'CPR',
//     descripcion: 'BUROES.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125541,
//     estatus: 'CPR',
//     descripcion: 'CABECERA.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125542,
//     estatus: 'CPR',
//     descripcion: 'MUEBLE PARA TELEVISION.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125543,
//     estatus: 'CPR',
//     descripcion: 'TELEVISOR MARCA SONY.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125544,
//     estatus: 'CPR',
//     descripcion: 'TELEVISOR MARCA RCA.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125545,
//     estatus: 'CPR',
//     descripcion: 'MODULAR DE LA MARCA SONY, COLOR NEGRO.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125546,
//     estatus: 'CPR',
//     descripcion: 'REPRODUCTOR DE DVD DE LA MARCA SUPERSONIC.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125547,
//     estatus: 'CPR',
//     descripcion: 'MUEBLE TOCADOR CON LUNA.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 2,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125591,
//     estatus: 'CPR',
//     descripcion: 'HORNO DE MICROONDAS DE COLOR NEGRO.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125593,
//     estatus: 'CPR',
//     descripcion: 'CONTADORA TOYOCOM.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125594,
//     estatus: 'CPR',
//     descripcion: 'SUMADORA CASIO.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125595,
//     estatus: 'CPR',
//     descripcion: 'CAJA FUERTE CON TAPADERA EN FORMA CIRCULAR, DE COLOR GRIS.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125600,
//     estatus: 'CPR',
//     descripcion: 'ONZAS DE PLATA.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 11,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125603,
//     estatus: 'CPR',
//     descripcion: '188.83 (CIENTO OCHENTA Y OCHO Y 83/100 GRAMOS DE ORO).',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125750,
//     estatus: 'CPR',
//     descripcion: 'ESCRITORIOS.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 2,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125761,
//     estatus: 'CPR',
//     descripcion: 'COMPUTADORA IBM.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125762,
//     estatus: 'CPR',
//     descripcion: 'IMPRESORA.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125763,
//     estatus: 'CPR',
//     descripcion: 'TELEVISION DE 20", MARCA SHAR (SIC).',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125764,
//     estatus: 'CPR',
//     descripcion: 'MESA MEDIANA.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125765,
//     estatus: 'CPR',
//     descripcion: 'SILLAS.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 4,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125766,
//     estatus: 'CPR',
//     descripcion: 'HORNO DE MICROONDAS.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125767,
//     estatus: 'CPR',
//     descripcion: 'TELEFONOS.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 4,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125768,
//     estatus: 'CPR',
//     descripcion: 'CONTADORA DE DINERO.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125769,
//     estatus: 'CPR',
//     descripcion: 'CAJA FUERTE.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125500,
//     estatus: 'CPR',
//     descripcion: 'REFRIGERADOR DE LA MARCA WHIRLPOL.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125501,
//     estatus: 'CPR',
//     descripcion: 'TELEVISION INCRUSTADA A LA PARED DE LA MARCA DAEWOO.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125502,
//     estatus: 'CPR',
//     descripcion: 'UN HORNO ELECTRICO MARCA HAMILTON BEACH.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125503,
//     estatus: 'CPR',
//     descripcion: 'TOSTADOR PROCTOR SILEX.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125504,
//     estatus: 'CPR',
//     descripcion: 'LICUADORA MARCA HAMILTON BEACH.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125505,
//     estatus: 'CPR',
//     descripcion: 'HORNO DE MICROONDAS MARCA SHARP.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125506,
//     estatus: 'CPR',
//     descripcion: 'SERVIDOR DE AGUA COLOR BLANCO SIN MARCA VISIBLE.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125507,
//     estatus: 'CPR',
//     descripcion: 'DIVERSOS PRODUCTOS DE COCINA.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125508,
//     estatus: 'CPR',
//     descripcion: 'MESA RECTANGULAR COLOR BLANCO CON CUBIERTA DE CRISTAL.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125509,
//     estatus: 'CPR',
//     descripcion: 'SILLAS DEL MISMO COLOR CON ASIENTOS TAPIZADOS DE TELA BEIGE.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 8,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125510,
//     estatus: 'CPR',
//     descripcion: 'TRINCHADOR.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125511,
//     estatus: 'CPR',
//     descripcion: 'BICICLETA AZUL.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125512,
//     estatus: 'CPR',
//     descripcion: 'BICICLETA ROJA.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125513,
//     estatus: 'CPR',
//     descripcion: 'SILLON DE TRES PLAZAS.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125514,
//     estatus: 'CPR',
//     descripcion: 'SILLAS DE PLASTICO.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 2,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125515,
//     estatus: 'CPR',
//     descripcion: 'SALA COMPUESTA DE TRES PIEZAS TAPIZADA EN BEIGE CON AZUL.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 3,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125516,
//     estatus: 'CPR',
//     descripcion: 'MESAS ESQUINERAS CON CUBIERTA DE CRISTAL.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 2,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125517,
//     estatus: 'CPR',
//     descripcion: 'ESTEREO DE LA MARCA SONY.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125518,
//     estatus: 'CPR',
//     descripcion:
//       'BAUL CON FORMA DE MESA DE CENTRO CON CINCO ARCOS CON ENTREPAÑOS Y FIGURAS DECORATIVAS.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125519,
//     estatus: 'CPR',
//     descripcion: 'SOFA DE TRES PLAZAS COLOR BEIGE FLOREADO.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125520,
//     estatus: 'CPR',
//     descripcion: 'SILLON CON BASE DE MADERA.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125521,
//     estatus: 'CPR',
//     descripcion: 'TELEVISION DE LA MARCA SONY DE APROXIMADAMENTE 25".',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125522,
//     estatus: 'CPR',
//     descripcion: 'VIDEOCASETERA MARCA SONY.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125523,
//     estatus: 'CPR',
//     descripcion:
//       'CAJA DE CARTON QUE EN SU INTERIOR CONTIENE UNA TELEVISION MARCA SONY DE 30" APROXIMADAMENTE.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 2,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125524,
//     estatus: 'CPR',
//     descripcion: 'BURO (SIC).',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125525,
//     estatus: 'CPR',
//     descripcion: 'ROPA DIVERSA.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125526,
//     estatus: 'CPR',
//     descripcion: 'CAMA.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125527,
//     estatus: 'CPR',
//     descripcion: 'CABECERA.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125528,
//     estatus: 'CPR',
//     descripcion: 'BUROES.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125529,
//     estatus: 'CPR',
//     descripcion: 'LAVADORA MARCA WHIRLPOL COLOR BEIGE.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125530,
//     estatus: 'CPR',
//     descripcion: 'LAVADORA MARCA HEAVY DUTY.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125531,
//     estatus: 'CPR',
//     descripcion: 'CALENTADOR CAL-O-REX.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125532,
//     estatus: 'CPR',
//     descripcion: 'CAMA INDIVIDUAL.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125533,
//     estatus: 'CPR',
//     descripcion: 'BUROES.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 2,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125534,
//     estatus: 'CPR',
//     descripcion: 'PEQUEÑO TOCADOR.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 125535,
//     estatus: 'CPR',
//     descripcion: 'CAMA INDIVIDUAL.',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30639,
//     estatus: 'CPR',
//     descripcion: 'ESTUFA DIGITAL CON HORNO PANORAMICO',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 5,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30642,
//     estatus: 'CPR',
//     descripcion: 'DESAYUNADOR DE HIERRO FORJADO',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 5,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30641,
//     estatus: 'CPR',
//     descripcion: 'HORNO DE MICRO HONDAS',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 5,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30646,
//     estatus: 'CPR',
//     descripcion: 'EXPRIMIDOR DE JUGOS',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30637,
//     estatus: 'CPR',
//     descripcion: 'ENFRAIDOR Y CALENTADOR DE AGUA',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30647,
//     estatus: 'CPR',
//     descripcion: 'EXTRACTOR DE JUGOS',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30648,
//     estatus: 'CPR',
//     descripcion: 'ABRELATAS ELECTRICO',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30656,
//     estatus: 'CPR',
//     descripcion: 'EXHIBIDOR DE HIERRO FORJADO',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30655,
//     estatus: 'CPR',
//     descripcion: 'COMEDOR CON MESA RECTANGULAR CON 6 SILLAS',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30645,
//     estatus: 'CPR',
//     descripcion: 'APARATO PARA HACER ESQUIMOS',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
//   {
//     ciudad_transferente: 'CIUDAD DE MEXICO',
//     no_bien: 30644,
//     estatus: 'CPR',
//     descripcion: 'LICUADORA',
//     tipo_bien: 'BIENES MUEBLES',
//     no_expediente: 29332,
//     cantidad: 1,
//     fec_aprobacion_x_admon: null,
//     fec_indica_usuario_aprobacion: null,
//     destino: 'RESGUARDO',
//   },
// ];
