export class IModComerOffice {
  id_oficio?: number;
  id_oficio_respuesta?: string;
  cve_oficio?: string;
  id_evento?: number;
  tipo_oficio?: string;
  id_tpsolaval?: string;
  fecha_insert?: string;
  usuario_insert?: string;
  no_usuario_insert?: string;
  num_cv_armada?: string;
  usuario_envia?: string;
  fecha_envia?: string;
  id_oficio_recidencial?: string;
  id_oficio_recidencial2?: string;
  remitente?: string;
  no_remitente?: string;
  no_dep_remitente?: string;
  cve_cargo_remitente?: string;
  destinatario?: string;
  ciudad?: string;
  ciudad2?: string;
  estatus_of?: string;
  texto1?: string;
  texto2?: string;
  texto3?: string;
  nom_destinatario?: string;
  cargo_destinatario?: string;
  nom_remitente?: string;
  cargo_rem?: string;
  nivel1?: string;
  nivel2?: string;
  nivel3?: string;
  nom_ciudades?: string;
  identificador?: string;
  id_programacion?: string;
  constructor() {
    this.id_oficio = null;
    this.id_oficio_respuesta = null;
    this.cve_oficio = null;
    this.id_evento = null;
    this.tipo_oficio = null;
    this.id_tpsolaval = null;
    this.fecha_insert = null;
    this.usuario_insert = null;
    this.no_usuario_insert = null;
    this.num_cv_armada = null;
    this.usuario_envia = null;
    this.fecha_envia = null;
    this.id_oficio_recidencial = null;
    this.id_oficio_recidencial2 = null;
    this.remitente = null;
    this.no_remitente = null;
    this.no_dep_remitente = null;
    this.cve_cargo_remitente = null;
    this.destinatario = null;
    this.ciudad = null;
    this.ciudad2 = null;
    this.estatus_of = null;
    this.texto1 = null;
    this.texto2 = null;
    this.texto3 = null;
    this.nom_destinatario = null;
    this.cargo_destinatario = null;
    this.nom_remitente = null;
    this.cargo_rem = null;
    this.nivel1 = null;
    this.nivel2 = null;
    this.nivel3 = null;
    this.nom_ciudades = null;
    this.identificador = null;
    this.id_programacion = null;
  }
}
