export const dataCrimes = [
  {
    id: 12,
    otcKey: 17,
    description: 'TECNICO ESPECIALIZADO',
    registryNumber: 2710781,
    abbreviation: 'NULL',
  },
  {
    id: 2,
    otcKey: 363,
    description: 'EQUIPARABLE AL CONTRABANDO',
    registryNumber: 2710782,
    abbreviation: 'NULL',
  },
  {
    id: 2,
    otcKey: 356,
    description: 'EQIPARARBLE AL CONTRABANDO',
    registryNumber: 2710783,
    abbreviation: 'NULL',
  },
  {
    id: 2,
    otcKey: 560,
    description: 'PECULADO',
    registryNumber: 2710784,
    abbreviation: 'NULL',
  },
  {
    id: 9,
    otcKey: 2,
    description: 'MENSAJERIA',
    registryNumber: 2710785,
    abbreviation: 'NULL',
  },
  {
    id: 4,
    otcKey: 256,
    description: 'CREMA/CAFE',
    registryNumber: 2710786,
    abbreviation: 'NULL',
  },
  {
    id: 9,
    otcKey: 7,
    description: 'OTROS',
    registryNumber: 2710787,
    abbreviation: 'NULL',
  },
  {
    id: 4,
    otcKey: 257,
    description: 'CROMADO',
    registryNumber: 2710788,
    abbreviation: 'NULL',
  },
  {
    id: 9,
    otcKey: 12,
    description: 'co',
    registryNumber: 2710789,
    abbreviation: 'NULL',
  },
  {
    id: 9,
    otcKey: 14,
    description: 'CORREO CERTIFICADO',
    registryNumber: 2710790,
    abbreviation: 'NULL',
  },
];
