export enum DonationEndPoint {
  donation = 'filters-donation/',
  requets = 'donac-request',
  requestGood = 'donac-request-good/getDonationData/',
  requestGoodPro = 'donac-request-good/get-v-donation-proposal-goods/',
  requestUpdate = 'donac-request-good/update-request-donation-good/',
  eventComDonation = 'event-com-donation',
  DetailEventComDon = 'detail-event-com-don',
  //chm
  DetailProceddingEventComDon = 'detail-event-com-don/proceeding',
  ErrorProceddingEventComDon = 'detail-event-com-don/proceedingerr',
  QuantityProceddingEventComDon = 'detail-event-com-don/eventdonaquantity',
  eventComDonationExcel = 'detail-event-com-don/find-all-detail-event-com-don-excel-export',
  TempDonationGood = 'donate-invent-rel',
  ApproveDonation = 'r-approve-donation',
  fdonacDocumAdm1 = 'fdonacDocumAdm1',
  ApproveDnation = 'r-approve-donation',
  TempDonation = 'tmp-goods-donac',
  GoodsForDonation = 'admon-donation',
  RequestGoodDon = 'donac-request-good/getAllV2',
  DeleteGoodDon = 'donac-request-good',
  Inventary = 'donate-invent-rel/invent-rel',
  CreateInventary = 'donate-invent-rel',
  DetailEventComByID = 'detail-event-com-don/find-one',
}
