export enum DonationEndPoint {
  donation = 'filters-donation/',
  requets = 'donac-request',
  requestGood = 'donac-request-good/getDonationData/',
  requestGoodPro = 'donac-request-good/get-v-donation-proposal-goods/',
  requestUpdate = 'donac-request-good/update-request-donation-good/',
  eventComDonation = 'event-com-donation',
  DetailEventComDon = 'detail-event-com-don',
  eventComDonationExcel = 'detail-event-com-don/find-all-detail-event-com-don-excel-export',
  TempDonationGood = 'donate-invent-rel',
  ApproveDonation = 'r-approve-donation',
  fdonacDocumAdm1 = 'fdonacDocumAdm1',
  ApproveDnation = 'r-approve-donation',
  GoodsForDonation = 'admon-donation',
}
