export enum DepositaryEndPoints {
  Depositary = `depositary`,
  DepositaryAppointment = `depositary-appointment`,
  DepositaryAppointments = `depositary-appointments`,
  DepositaryRequest = `legal-destination-for-property`,
  PersonsModDepositary = `persons-mod-depositary`,
  PaymentRefParamsDep = `payment-ref/params-dep`,
  PaymentRefValidDep = `payment-ref/valid-dep`,
  PaymentRefPrepOI = `payment-ref/prep-oi`,
  RemovePaymentRefRemove = `payment-ref/remove-disper-payments-ref`,
  ValidBlackListAppointment = `valid-black-list/appointment`,
  AplicationcargaCliente1 = 'application/cargaCliente1',
  AplicationcargaCliente2 = 'application/cargaCliente2',
  DepositaryDedPay = 'ded-pay-depositary',
  DepositaryDetrepo = 'detrepo-depositary',
  InfoDepositary = 'info-depositary',
  FactJurRegDestLeg = 'depositary-queries/getFactJurRegDestLegCustom',
}
