export enum DocumentsEndpoints {
  Documents = `documents`,
  DocumentsType = 'documents-types',
  DocumentsSeparator = 'document-separator',
  DocumentsDictuXStateM = 'documents-dictum-x-state-m',
  DocumentsDictuXState = 'documents-dictum-x-state',
  ClarificationDocumentsImpro = 'clarification-documents-impro',
  ClarificationDocumentsGood = 'clarification-goods-documents',
  DocumentRequestPerGood = 'documents-request-per-good',
  DocumentsForDictum = 'documents-for-dictum',
  Count1 = 'application/getCount1',
  CapDigiralizationTmp = 'cap-digitalization-tmp',
  IndicatorRec = 'application/get-data-ind-rec-doc',
  SeqDocument = 'application/getSeqDocument',
  postdocument = 'application/insertDocument',
  postPup = 'application/pupFolEscMas',
  ApplicationGetMaxConsec = 'application/getMaxConsec',
  ComerceDocumentsXmlT = 'comerce-documents-xml-t',
  DocumentRequestPerGoodNew = 'documents-request-per-good',
  ExportExcelcaptura = 'application/get-data-ind-rec-doc-export',
  GetDocument = 'application/getDocument-pag',
}
