export enum DictationEndpoints {
  BasePath = 'dictation',
  Dictation = 'dictation',
  DictationXGood1 = 'dictation-x-good1',
  ValidationGoodAvailable = 'validation-good-available',
  getParamsOfTypeGood = 'additional-queries/get-params-of-v-type-good',
  FindIdsDictationXGood1 = 'dictation-x-good1/find-by-ids',
  OfficialDictation = 'official-dictation',
  FindIdsOfficialDictation = 'official-dictation/find-by-ids',
  DictationXGood = 'dictation-x-good',
  CopiesOfficialOpinion = 'copies-official-opinion',
  FindByIds = 'dictation/find-by-ids',
  CargaMasDesahogob = 'application/cargaMasDesahogob',
  FindGoodDictGood1 = 'additional-queries/find-good-dictxgood1',
  InitFormLegalOpinionOffice = 'application/pupInicializaForma1',
  InitFormLegalOpinionOffice2 = 'application/pupInicializaForma2',
  CopiesOfficeSendDictation = 'application/copiasOficioDictamenEnviar',
  DocumentByDictation = 'r-dictation-doc',
  FindDescriptionOpinion = 'additional-queries/find-description-opinion',
  RTdictaAarusr = 'r-tdicta-aarusr',
  TmpDictation = 'tmp-dictation',
}
