export enum GoodEndpoints {
  Good = `good`,
  GoodGetDat = `good/getData`,
  Domicilies = `domicilies`,
  SearchByExpedient = `good/expedient/search`,
  GoodAndDesc = `good/getGoodAndDesc`,
  StatusAndDesc = `good/getDescAndStatus`,
  GoodsTransAva = 'goods-trans-ava',
  DeleteByExpedient = `good/deleteByExpendient`,
  DiStatusGood = 'status-good/diStatusGood',
  GoodWidthMeasure = 'good/searchGoodNumber',
  GoodGetActAccount = 'good/get-act-count',
  GoodGetStatusAndProcess = 'good/applied-status-final',
  GoodValidMassiveDownload = 'good/validGoodNumber',
  GoodValidSeq = 'good/validSeq',
  GoodValidFlag = 'good/validGoodFlag',
  GoodValidSat = 'good/validSat',
  SearchGoodByFile = 'good/searchGoodByFile',
  SearchGoodByClasif = 'good/searchGoodByClasif',
  GoodsExtensionFields = 'goods-extension-fields',
}
