export enum GoodsQueryEndpoints {
  BasePath = 'goodsquery',
  LigieUnitMeasure = 'goodsquery/ligie-units-measure',
  ZipCode = 'goodsquery/views/catCodesPostalView',
  AttribClassifBood = 'attributes-classification-good',
  ProgrammingGood = 'goodsquery/api/v1/views/goodsAddressView',
  AtributeClassificationGoods = 'goodsquery/api/v1/attributes-classification-good',
  AtributeClassificationGood = 'goodsquery/api/v1/attrib-classif-good',
  AtributesClassificationGood = 'attributes-classification-good',
  MeasureUnitsView = 'goodsquery/api/v1/views/catMeasureUnitsView',
  OpinionDelRegSeq = 'application/opinionDelRegSeq',
  getUnits = 'ligie-units-measure',
  getViewIndRecDoc = 'views/VIndRecDocView',
  UnitsQuery = 'application/units-query',
  indicatorsEntRecep = 'views/get-v-indicators-ent-recep',
  OrderValReq = 'views/orderServiceExpensesGood/ValReqView',
  OrderRecDoc = 'views/orderServiceExpensesGood/RecDocView',
  OrderProg = 'views/orderServiceExpensesGood/ProgView',
  OrderProgEnt = 'views/orderServiceExpensesGood/ProgEntView',
  OrderWarehouse = 'views/orderServiceExpensesGood/AlmView',
  OrderManual = 'views/orderServiceExpensesGood/ManualView',
  OrderReubGood = 'views/orderServiceExpensesGood/ReubicaView',
  CatStoresView2 = 'views/cat-store-view',
}
