export enum GoodprocessEndpoints {
  BasePath = 'goodprocess',
  AplicationValidStatus = 'application/validStatus',
  ApplicationAllFill = 'application/all-fill',
  CountBienEstatusXPantalla = 'application/countBienEstatusXPantalla',
  ExpedientePostQuery = 'application/expedientePostQuery',
  ApplicationDictaminacionesCount = 'application/getDictaminacionesCount',
  ApplicationCuEmisora = 'application/cuEmisora',
  ApplicationCuDelRem = 'application/cuDelRem',
  ApplicationCuDelDest = 'application/cuDelDest',
  ParametersFaStageCreda = 'parameters/fa-stage-creda',
  QueryVtypeGood = 'application/queryVtypeGood',
  ApplicationPupGenMasiv = 'application/pup-gen-masiv',
  GetGoodScreenSend = '/application/get-good-status-screen',
  GetDistinctTypes = 'application/get-distinct-types',
  UpdateGoodStatus = 'update-good-status/updateManagementJob',
  GetGoodProceedings = 'application/get-good-proceedings',
}
