export enum ENDPOINT_INVOICE {
  BasePath = 'invoice',
  straInvoice = 'strategies-invoices',
  ComerInovice = 'comer-invoices',
  ApplicationImpPenalize = 'application/get-obt-imp-penalize',
  ApplicationMaxFolio = 'application/get-id-invoice/',
  DeleteFolio = 'ctrl-invoice/update-folioinvoice',
  UpdateStatusImg = 'application/update-status-invoice-img',
  UpdateByEvemt = 'application/update-by-idevent',
  CopyInvoice = 'ctrl-invoice/copy-invoice',
  ComerHeadboard = 'comer-headboard',
  ComerRectInvoice = 'comer-rectinvoices',
  ComerDetInvoice = 'comer-direct-fac',
  ApplicationSQL = 'application/execute-sql',
  ComerLote = 'ctrl-invoice/reg-lot',
  FactBases = 'procedure-sera/base-invoice-data',
  ComerCoord = 'ctrl-invoice/data-cor-reg',
  ApplicationFolioDispo = 'application/valida-folios-dispo',
  ValidateUser = 'procedure-sera/validate-user',
  ControlProcedure = 'procedure-sera/ctrl-generate-preinvoices',
}
