export enum IDocumentEndpoints {
  Base = `ldocument`,
  fileBrowserSaveFile = 'file-browser/saveFile',
  fileBrowserFiles = 'file-browser/files',
  filePhotos = 'file-photo/photos',
  filePhoto = 'file-photo/photo',
  filePhotoHistoric = 'file-photo/historicalPhoto',
  savePhoto = 'file-photo/savePhoto',
  deletePhoto = 'file-photo/deletePhoto',
  deletePhotoDefinitive = 'file-photo/deletePhotoDefinitive',
  editPhoto = 'file-photo/editPhoto',
  savePhotoZIP = 'file-photo/savePhotoZip',
  massiveSavePhotoZip = 'file-photo/saveFilePhotoZip',
  filePhotosHistoric = 'file-photo/historicalPhotos',
}
