export enum MassiveGoodEndpoints {
  MassiveGood = `massivegood`,
  MassiveChargeGoods = `massive-charge-goods`,
  CountMassiveGood = `massive-charge-goods/countMasiveGood`,
  InsertMassiveGood = `massive-charge-goods/insertMasiveGood`,
  DeleteMassiveGood = `massive-charge-goods/deleteMasiveGood`,
  MassivePropertyExcel = `massive-property-excel`,
  GetFlierNumberMassiveGood = `massive-charge-goods/get-flier-number`,
  GetFileCSV = `application/pupPreviewDatosCSV`,
  FileCSV = 'application/pupPreviewDataCsv',
  chargeGoodByExpedient = 'massive-charge-goods/bRealStateOutputs',
  GetFProRecPag2CSV = `application/get-f-proc-rec-pag2`,
  Massive = `application/massive-load-button`,
  PupCargaCsv = `application/pup-carga-csv`,
  MassiveProgGood = `application/massivegoodload`,
  GoodsShedules = 'application/get-goods-schedules-csv',
  GetAllGoodsMotivesRevExcel = 'application/getAllGoodsMotivesRevExcel',
  PorGoodReasonRev = 'application/por-good-reason-rev',
  ObtnGoodPag = 'application/obtn-good-pag',
}
