export enum NumeraryEndpoints {
  Numerary = `numerary`,
  ValidateCvs = `validate-cvs`,
  RateInt = 'rate-int-numerary',
  NumEnc = 'numerary-enc',
  NumDet = 'numerary-det',
  NumCal = 'numerary-cal',
  ProcessesNume = 'processes-nume',
  RequestEnc = 'requests-nume-enc',
  RequestCal = 'requests-nume-cal',
  RequestDet = 'requests-nume-det',
  RequestEncFilter = 'requests-nume-enc/getAllRequest',
  RequestChangeNumerary = 'm-request-change-numerary',
  RequestSolCamNum = 'd-sol-cam-num',
  RequestDSolCamNum = 'application/del-d-sol-cam-num',
  NumeraryCategories = 'numerary-categories',
  Application = 'application/del-solicitudes-nume-det-por-id-solnum',
  CloseNumerary = 'close-numerary',
  GetSolNumerario = 'application/get-sol-numerario',
  TransReg = 'transfer-numerary-region',
  ComerNumeraryGoods = 'comer-numerary-x-goods',
}
