export enum PrepareEventEndpoints {
  PreparaEvent = 'prepareevent',
  Encrypt = 'util-comer-v1//fbEncrypt',
  ApplicationPufSearchEvent = 'application/pufSearchEvent',
  ComerGoodXLote = 'comer-good-xlot',
  ComerLot = 'comer-lot',
  ComerEvent = 'comer-event',
  PA_Change_Status = 'process-v2/pa-change-status-validate',
  ProcessesTracker = 'util-comer-v1/processesTracker',
  ApplicationDataEvent = 'application/get-data-eat-events',
  ApplicationTpEvent = 'application/get-data-eatevents-tpevents',
  SalePrices = 'util-comer-v1/priceVta',
  getFindAllComerGoodXlotTotal = 'comer-good-xlot/findAllComerGoodXlotTotal',
  FindAllComerGoodXlotTotal = 'comer-good-xlot/findAllComerGoodXlotTotal',
}
