export enum PrepareEventEndpoints {
  PreparaEvent = 'prepareevent',
  DetEvent = 'comer-event/detEvent',
  ResumenAdmvxr = 'comer-event/summaryAdmvxr',
  Encrypt = 'util-comer-v1//fbEncrypt',
  ApplicationPufSearchEvent = 'application/pufSearchEvent',
  ComerGoodXLote = 'comer-good-xlot',
  ComerLot = 'comer-lot',
  ComerEvent = 'comer-event',
  PA_Change_Status = 'process-v2/pa-change-status-validate',
  ProcessesTracker = 'util-comer-v1/processesTracker',
  ApplicationDataEvent = 'application/get-data-eat-events',
  ApplicationTpEvent = 'application/get-data-eatevents-tpevents',
  SalePrices = 'util-comer-v1/priceVta',
  getFindAllComerGoodXlotTotal = 'comer-good-xlot/findAllComerGoodXlotTotal',
  FindAllComerGoodXlotTotal = 'comer-good-xlot/findAllComerGoodXlotTotal',
  ResumenEvento = 'application/eventResume',
  ShowNotification = 'application/pup-show-notification',
  GetProcessPhaseAnt = 'application/get-process-phase-ant',
  UpdatePhase = 'comer-event/update-phase',
  GetProcessPhase3Ant = 'application/get-process-phase3-ant',
  GetValidLiquidation = 'application/get-valid-liquidation',
}
