export enum ParameterGoodEndpoints {
  BasePath = 'parametergood',
  TDescCve = 'tdesccve',
  TDescAtrib = 'tdescatrib',
  GetAttribById = 'tdescatrib/find-by-table',
  Parameters = 'parameters',
  ParameterMaintenace = 'parametergood/parameters',
  FaseEdo = 'parameters/fa-stage-creda',
  CategorzacionAutomNumerario = 'categorzacion-autom-numerario',
  rNomecla = 'r-nomencla',
  FaStageCreda = 'parameters/fa-stage-creda',
  IndicatorsParameter = '/indicators-parameter',
  CategorzacionAutomNumerario_ = 'categorization-autom-numerary',
  PupCalculaDevolucion = 'application/pup-calcula-devolucion',
  GetDelegationGlobal = 'application/getDelegationGlobal',
  CatMotivesrev = 'cat-motivesrev',
  PupArmaClave = 'application/pup-weapon-key',
  RNomencla = 'application/get-r-nomencla',
  ApplicationGetFaUrlwebFac = 'application/get-fa-urlweb-fac',
  EnvioCorreoGenerico = 'application/paEnvioCorreoGenerico',
}
