export enum SecurityEndpoints {
  Security = `security`,
  GenerateIdentifier = 'tracking-access-screens',
  AccessTrackingXArea = 'access-tracking-x-area',
  ScreensAplicationTracking = 'screens-application-tracking',
  TrackingValidScreens = 'tracking-valid-screens',
  TrackingErrorProfileMim = 'tracking-error-profile-mimi',
  TrackingProfile = `tracking-profile`,
  SegProfilesMim = 'seg-profiles-mim',
  TrackingProfileXPant = 'tracking-profile-x-pant',
  TrackingTdictaXProfileMim = 'tracking-tdicta-x-profile-mim',
  UsersTracking = 'users-tracking',
  AplicationLovCitiesRegCity = 'application/lov-cities-reg-cities-city',
  StationClue = 'application/stationClue',
  IdDelegationDelegationForwards = 'application/idDelegationDelegationForwards',
  IdDelegationDelegationAddressee = 'application/idDelegationDelegationAddressee',
  QueryIdenti = 'application/queryIdenti',
  SegEmailUser = 'application/segUserEmail2',
  SegCopyEmail = 'application/getgencopia',
  FaCoordAdmin = 'application/fa-coord-admin',
  FaDelResponsable = 'application/fa-del-responsable',
  User = 'application/facta-db-solcam-nume',
  IniEmail = 'application/pup-ini-correo',
}
