export enum SurvillanceEndpoints {
  Survillance = 'survillance',
  VigProcessPercentages = 'vig-process-percentages',
  VigBinnacle = 'vig-binnacle',
  View_VigDelegations = 'views/v-vig-delegations',

  DeletePeriod = 'surveillance/delete-period',
  RecordRandom = 'surveillance/record-random',
  ValidPeriod = 'surveillance/valid-period',
  Periods = 'surveillance/periods',
  ChangePeriod = 'surveillance/change-period',
  ChangeGoodAle = 'surveillance/change-good-ale',
  Georeferencie = 'georeference-object',
  VigSupervisionDet = 'vig-supervision-det',
  VigSupervisionMae = 'vig-supervision-mae',
  VigSupervisionTMP = 'vig-supervision-tmp',
  DeleteVigSupervisionTMP = 'application/delete-vig-supervision-tmp',
  VCuentaPaqDestion = 'application/get-v-cuenta',
  FCalculaNume = 'application/fCalculateNum',
  PostInsertSupervisionTmp = 'surveillance/insertSupervisionTmp',
  GetTransNumerario = 'application/get-trans-numerario-reg',
  VigAllExcel = 'vig-supervision-det/allExcel',
}
