export enum StrategyEndpoints {
  BasePath = 'strategy',
  StrategyVariableCost = 'strategy-variable-cost',
  StrategyService = 'strategy-service',
  StrategyServiceType = 'strategy-service-type',
  StrategyShift = 'strategy-shift',
  StrategyProcess = 'strategy-process',
  TmpStrategyCost = 'tmp-strategy-cost',
  ZCenterOperationRegional = 'z-center-operation-regional/getAllDescriptionCenterZOperationRegional',
  getStrategy = 'aplication/getStrategy',
  StrategySum = 'aplication/getSumStrategy',
  StrategyAmount = 'strategy-rep-amounts',
  StrategyAdmin = 'strategies-admin',
  getbyStatus = 'aplication/getStrategyStatus',
  postByFilter = 'strategies-admin/idV2',
  strategyInd = 'strategy-ind-strategy',
  strategyIndReports = 'strategy-ind-reports',
  PaEstGood = 'aplication/pa-est-goods-incor',
  FEstFormat = 'aplication/fEstFormat3',
  FestFormat2 = 'aplication/fEstFormat2',
  strategyIndicator = 'strategy-indicator',
  UnitsMedConv = 'aplication/get-units-med-x-conv',
  StrategyType = 'aplication/get-bills-service-type',
  StrategySer = 'aplication/get-bills-service',
  StrategyPro = 'strategy-process',
  StrategyTurn = 'aplication/get-bills-turn',
  StrategyCost = 'aplication/get-bills-variable-bills',
}
