export enum PhotoGoodEndpoints {
  BasePath = 'photogood',
  PhotoGood = 'good-photo',
  FindPhoto = 'find-by-ids',
  GoodPhotoG = 'good-Photo-g',
  ComerPhotoFav = 'comer-Photofav',
  CtrlGoodsPhoto = 'ctrl-goods-photo',
  PhotographsGoods = 'photographs-goods',
  BienesFoto = 'photos-good',
  FotoWeb = 'photoweb',
  TmpGoodPhoto = 'tmp-good-photo',
  TmpGoodsPhoto = 'tmp-goods-photo',
  ContainerPhotosSiab = 'container-photossiab',
  BienFoto = 'good-photo',
  AppPhoto = 'application/pup-list-photos-tracker',
}
