export enum SiabReportEndpoints {
  EXTENSION = '.pdf',
  SIAB = `SIAB`,
  RINDICA = `RINDICA_0001`,
  RCONCOGVOLANTESRE = `RCONCOGVOLANTESRE`,
  FGENADBSITPROCESB = `FGENADBSITPROCESB`,
  FGERADBBOVEDAS = `FGERADBBOVEDAS`,
  FGERADBDEVDECBIEN = `FGERADBDEVDECBIEN`,
  FGERADBFILEAEXCEL = `FGERADBFILEAEXCEL`,
  FGERJURRECDEREV = `RGERJURRECDEREV`,
}
