export interface ITmpNotification {
  wheelNumber: number;
  receiptDate: string | Date;
  captureDate: string | Date;
  officeExternalKey: string;
  externalOfficeDate: string | Date;
  externalRemitter: string;
  protectionKey: string;
  touchPenaltyKey: string;
  circumstantialRecord: string;
  preliminaryInquiry: string;
  criminalCase: string;
  addressee?: string;
  expedientNumber: number;
  crimeKey: string;
  affairKey: string;
  entFedKey: string;
  viaKey: string;
  consecutiveNumber: number;
  observations: string;
  delegationNumber: number;
  subDelegationNumber: number;
  institutionNumber: number;
  indiciadoNumber: number;
  delDestinyNumber: number;
  subDelDestinyNumber: number;
  departamentDestinyNumber: number;
  officeNumber: number;
  minpubNumber: number;
  cityNumber: number;
  courtNumber: number;
  registerNumber?: number;
  dictumKey: string;
  identifier: string;
  observationDictum?: string;
  wheelStatus: string;
  transference: number;
  expedientTransferenceNumber: string;
  priority: string;
  wheelType: string;
  reserved: string;
  entryProcedureDate: string | Date;
  userInsert?: string;
  originNumber: number;
  stationNumber: number;
  autorityNumber: number;
  endTransferNumber: number;
  dailyEviction: number;
  hcCaptureDate: string | Date;
  hcEntryProcedureDate: string | Date;
  desKnowingDate?: string | Date;
  affairSij: number;
}
