export const eventsData = [
  {
    id: 1408,
    typeEventId: 3,
    statusSaleId: 'CONC',
    eventKey: 'ADJ.DIRECTA, GOB. B.C.S',
    observations: 'SI ESTOY ENTRANDO  3 3 I T',
    address: 'I',
    failureDate: '2008-07-18',
    location: 'MEXICO, D.F., A 18 DE JULIO DE 2008',
    eventDate: '2008-07-18',
    text1: 'NULL',
    text2: 'NULL',
    signer: 'NULL',
    positionSigner: 'NULL',
    notes: 'NULL',
    endText3: 'NULL',
    endText4: 'NULL',
    baseCost: 'NULL',
    baseNumberSold: 'NULL',
    user: 'RONOFRE',
    month: 7,
    year: 2008,
    delegationNumber: 0,
    inmuPhase: 2,
    thirdPartyId: 'NULL',
    notificationDate: 'NULL',
    closingDate: 'NULL',
    tpsolavaId: 'NULL',
    aplica_iva: 2,
    trial919: 'T',
  },
  {
    id: 1416,
    typeEventId: 6,
    statusSaleId: 'PREP',
    eventKey: 'CRHMO/DES/ALAF CHIHUAHUA/145/08',
    observations: 'SI ESTOY ENTRANDO  3 6 M T',
    address: 'M',
    failureDate: 'NULL',
    location: 'CHIHUAHUA, CHIH.',
    eventDate: 'NULL',
    text1: 'NULL',
    text2: 'NULL',
    signer: 'NULL',
    positionSigner: 'NULL',
    notes: 'NULL',
    endText3: 'NULL',
    endText4: 'NULL',
    baseCost: 'NULL',
    baseNumberSold: 'NULL',
    user: 'JESANDOVAL',
    month: 7,
    year: 2008,
    delegationNumber: 2,
    inmuPhase: 'NULL',
    thirdPartyId: 'NULL',
    notificationDate: 'NULL',
    closingDate: 'NULL',
    tpsolavaId: 'NULL',
    aplica_iva: 2,
    trial919: 'T',
  },
  {
    id: 1417,
    typeEventId: 6,
    statusSaleId: 'PREP',
    eventKey: 'CRHMO/DES/ADUANA PTO PALOMAS/146/08',
    observations: 'SI ESTOY ENTRANDO  3 6 M T',
    address: 'M',
    failureDate: 'NULL',
    location: 'PTO PALOMAS CHIHUAHUA',
    eventDate: 'NULL',
    text1: 'NULL',
    text2: 'NULL',
    signer: 'NULL',
    positionSigner: 'NULL',
    notes: 'NULL',
    endText3: 'NULL',
    endText4: 'NULL',
    baseCost: 'NULL',
    baseNumberSold: 'NULL',
    user: 'JESANDOVAL',
    month: 7,
    year: 2008,
    delegationNumber: 2,
    inmuPhase: 'NULL',
    thirdPartyId: 'NULL',
    notificationDate: 'NULL',
    closingDate: 'NULL',
    tpsolavaId: 'NULL',
    aplica_iva: 2,
    trial919: 'T',
  },
  {
    id: 1425,
    typeEventId: 6,
    statusSaleId: 'PREP',
    eventKey: 'CRHMO/DES/ADUANA CHIHUAHUA/147/08',
    observations: 'SI ESTOY ENTRANDO  3 6 M T',
    address: 'M',
    failureDate: 'NULL',
    location: 'CHIHUAHUA CHIH',
    eventDate: 'NULL',
    text1: 'NULL',
    text2: 'NULL',
    signer: 'NULL',
    positionSigner: 'NULL',
    notes: 'NULL',
    endText3: 'NULL',
    endText4: 'NULL',
    baseCost: 'NULL',
    baseNumberSold: 'NULL',
    user: 'JESANDOVAL',
    month: 7,
    year: 2008,
    delegationNumber: 2,
    inmuPhase: 'NULL',
    thirdPartyId: 'NULL',
    notificationDate: 'NULL',
    closingDate: 'NULL',
    tpsolavaId: 'NULL',
    aplica_iva: 2,
    trial919: 'T',
  },
  {
    id: 1433,
    typeEventId: 6,
    statusSaleId: 'PREP',
    eventKey: 'CRTIJ/COMDD/032/08',
    observations: 'SI ESTOY ENTRANDO  3 6 M T',
    address: 'M',
    failureDate: 'NULL',
    location: 'TIJUANA BAJA CALIFORNIA',
    eventDate: 'NULL',
    text1: 'NULL',
    text2: 'NULL',
    signer: 'NULL',
    positionSigner: 'NULL',
    notes: 'NULL',
    endText3: 'NULL',
    endText4: 'NULL',
    baseCost: 'NULL',
    baseNumberSold: 'NULL',
    user: 'RMONREAL',
    month: 7,
    year: 2008,
    delegationNumber: 2,
    inmuPhase: 'NULL',
    thirdPartyId: 'NULL',
    notificationDate: 'NULL',
    closingDate: 'NULL',
    tpsolavaId: 'NULL',
    aplica_iva: 2,
    trial919: 'T',
  },
  {
    id: 1434,
    typeEventId: 6,
    statusSaleId: 'PREP',
    eventKey: 'CRTIJ/SEMOVIENTE/07/08',
    observations: 'SI ESTOY ENTRANDO  3 6 M T',
    address: 'M',
    failureDate: 'NULL',
    location: 'TIJUANA BAJA CALIFORNIA',
    eventDate: 'NULL',
    text1: 'NULL',
    text2: 'NULL',
    signer: 'NULL',
    positionSigner: 'NULL',
    notes: 'NULL',
    endText3: 'NULL',
    endText4: 'NULL',
    baseCost: 'NULL',
    baseNumberSold: 'NULL',
    user: 'RMONREAL',
    month: 7,
    year: 2008,
    delegationNumber: 2,
    inmuPhase: 'NULL',
    thirdPartyId: 'NULL',
    notificationDate: 'NULL',
    closingDate: 'NULL',
    tpsolavaId: 'NULL',
    aplica_iva: 2,
    trial919: 'T',
  },
  {
    id: 1448,
    typeEventId: 6,
    statusSaleId: 'PREP',
    eventKey: 'CRTG/COMDD/016/2008',
    observations: 'SI ESTOY ENTRANDO  3 6 M T',
    address: 'M',
    failureDate: 'NULL',
    location: 'TGZ',
    eventDate: 'NULL',
    text1: 'NULL',
    text2: 'NULL',
    signer: 'NULL',
    positionSigner: 'NULL',
    notes: 'NULL',
    endText3: 'NULL',
    endText4: 'NULL',
    baseCost: 'NULL',
    baseNumberSold: 'NULL',
    user: 'JFELIX',
    month: 7,
    year: 2008,
    delegationNumber: 9,
    inmuPhase: 'NULL',
    thirdPartyId: 'NULL',
    notificationDate: 'NULL',
    closingDate: 'NULL',
    tpsolavaId: 'NULL',
    aplica_iva: 2,
    trial919: 'T',
  },
  {
    id: 1449,
    typeEventId: 6,
    statusSaleId: 'PREP',
    eventKey: 'CRTG/COMDD/017/2008',
    observations: 'SI ESTOY ENTRANDO  3 6 M T',
    address: 'M',
    failureDate: 'NULL',
    location: 'TGZ',
    eventDate: 'NULL',
    text1: 'NULL',
    text2: 'NULL',
    signer: 'NULL',
    positionSigner: 'NULL',
    notes: 'NULL',
    endText3: 'NULL',
    endText4: 'NULL',
    baseCost: 'NULL',
    baseNumberSold: 'NULL',
    user: 'JFELIX',
    month: 7,
    year: 2008,
    delegationNumber: 9,
    inmuPhase: 'NULL',
    thirdPartyId: 'NULL',
    notificationDate: 'NULL',
    closingDate: 'NULL',
    tpsolavaId: 'NULL',
    aplica_iva: 2,
    trial919: 'T',
  },
  {
    id: 1450,
    typeEventId: 6,
    statusSaleId: 'PREP',
    eventKey: 'CRTG/COMDD/018/2008',
    observations: 'SI ESTOY ENTRANDO  3 6 M T',
    address: 'M',
    failureDate: 'NULL',
    location: 'TGZ',
    eventDate: 'NULL',
    text1: 'NULL',
    text2: 'NULL',
    signer: 'NULL',
    positionSigner: 'NULL',
    notes: 'NULL',
    endText3: 'NULL',
    endText4: 'NULL',
    baseCost: 'NULL',
    baseNumberSold: 'NULL',
    user: 'JFELIX',
    month: 7,
    year: 2008,
    delegationNumber: 9,
    inmuPhase: 'NULL',
    thirdPartyId: 'NULL',
    notificationDate: 'NULL',
    closingDate: 'NULL',
    tpsolavaId: 'NULL',
    aplica_iva: 2,
    trial919: 'T',
  },
  {
    id: 1453,
    typeEventId: 6,
    statusSaleId: 'PREP',
    eventKey: 'COMER/D.F./JULIO/08',
    observations: 'SI ESTOY ENTRANDO  3 6 M T',
    address: 'M',
    failureDate: 'NULL',
    location: 'EUROPA NO 34 COL.LOS REYES LA PAZ DELEGACION COYOACAN',
    eventDate: 'NULL',
    text1: 'NULL',
    text2: 'NULL',
    signer: 'NULL',
    positionSigner: 'NULL',
    notes: 'NULL',
    endText3: 'NULL',
    endText4: 'NULL',
    baseCost: 'NULL',
    baseNumberSold: 'NULL',
    user: 'JBARBIER',
    month: 7,
    year: 2008,
    delegationNumber: 11,
    inmuPhase: 'NULL',
    thirdPartyId: 'NULL',
    notificationDate: 'NULL',
    closingDate: 'NULL',
    tpsolavaId: 'NULL',
    aplica_iva: 2,
    trial919: 'T',
  },
];
