export const DOCUMENTS_RECEPTION_REGISTER_TRANS = [
  {
    id: 'TRANS',
    description: 'Transferente',
  },
];

export const DOCUMENTS_RECEPTION_REGISTER_DEFAULT_IDENFIFIERS = [
  ...DOCUMENTS_RECEPTION_REGISTER_TRANS,
  {
    id: '4',
    description: 'Trans con numero 4',
  },
  {
    id: 'MIXTO',
    description: 'Transferente mixto',
  },
];

const notifsTestData: any[] = [
  {
    wheelNumber: '1444810',
    receiptDate: '2018-04-20T00:00:00.000Z',
    captureDate: '2018-04-20T00:00:00.000Z',
    officeExternalKey: 'DGAA/109/2018',
    externalOfficeDate: '2018-03-26T00:00:00.000Z',
    externalRemitter: 'LIC. MIGUEL ANGEL ESQUINCA KURI',
    protectionKey: null,
    touchPenaltyKey: null,
    circumstantialRecord: null,
    preliminaryInquiry: null,
    criminalCase: null,
    addressee: null,
    expedientNumber: '748077',
    crimeKey: null,
    affairKey: '32',
    entFedKey: '9',
    viaKey: '2',
    consecutiveNumber: '2',
    observations: 'TRANSFERENCIA DE BIENES',
    delegationNumber: '3',
    subDelegationNumber: '0',
    institutionNumber: {
      id: '200',
      name: 'NUEVO CATALOGO',
      description: 'NUEVO CATALOGO',
      manager: null,
      street: null,
      numInside: null,
      numExterior: null,
      cologne: null,
      zipCode: null,
      delegMunic: null,
      phone: null,
      numClasif: '0',
      numCity: null,
      idCity: null,
      numRegister: '4613335',
      numTransference: null,
    },
    indiciadoNumber: '5',
    delDestinyNumber: '3',
    subDelDestinyNumber: '0',
    departamentDestinyNumber: '952',
    officeNumber: null,
    minpubNumber: null,
    cityNumber: '266',
    courtNumber: null,
    registerNumber: '772000715',
    dictumKey: 'DICTAMEN DE RECEPCION DE BIENES TRANSFERIDOS',
    identifier: 'TRANS',
    observationDictum: null,
    wheelStatus: 'PENDIENTE',
    transference: '522',
    expedientTransferenceNumber: null,
    priority: 'N',
    wheelType: 'T',
    reserved: null,
    entryProcedureDate: '2018-04-19T00:00:00.000Z',
    userInsert: 'OST12926',
    originNumber: '1',
    stationNumber: '1',
    autorityNumber: '1',
    endTransferNumber: '522',
    dailyEviction: '0',
    hcCaptureDate: '2018-04-20T00:00:00.000Z',
    hcEntryProcedureDate: '2018-04-19T00:00:00.000Z',
    desKnowingDate: null,
    addressGeneral: '0',
    affair: {
      id: '32',
      description: 'BIENES TRANSFERIDOS PARA SU VENTA',
      referralNoteType: 'T',
      creationUser: 'system',
      creationDate: '2016-04-06T00:00:00.000Z',
      editionUser: 'system',
      modificationDate: '2016-04-06T00:00:00.000Z',
      versionUser: 'S',
      status: null,
      registerNumber: '2271680',
      version: '1',
      processDetonate: 'RES_NUMERARIO',
      clv: 'S',
    },
    delegation: {
      id: '3',
      etapaEdo: '1',
      stateKey: '6',
      description: 'COORD. REGIONAL CIUDAD JUAREZ',
      addressOffice:
        'Condominio Mayab ubicado en Carlos Villareal 3048 Int. 305 y 306, Col. Margaritas, 32300, Cd. Juárez, Chihuahua\n',
      regionalDelegate: 'LIC. MAURO CESAR LOZANO LOPEZ         ',
      zoneKey: 'Oeste',
      city: 'CD. JUÁREZ',
      status: null,
      iva: '0.16',
      noRegister: '20571',
      zoneContractKey: '1',
      zoneVigilanceKey: null,
      diffHours: '-1',
      version: null,
      creationUser: 'system',
      creationDate: '2016-04-05T00:00:00.000Z',
      editionUser: 'system',
      modificationDate: '2016-04-05T00:00:00.000Z',
      idZoneGeographic: '1',
    },
    subDelegation: {
      id: '0',
      phaseEdo: '1',
      delegationNumber: '3',
      description: 'CIUDAD JUAREZ',
      dailyConNumber: '9',
      dateDailyCon: '2005-08-31T00:00:00.000Z',
      registerNumber: '31442',
    },
    departament: null,
  },
  {
    wheelNumber: '1444809',
    receiptDate: '2018-04-20T00:00:00.000Z',
    captureDate: '2018-04-20T00:00:00.000Z',
    officeExternalKey: '400-12-00-01-00-2018-01019',
    externalOfficeDate: '2018-04-12T00:00:00.000Z',
    externalRemitter: 'C,P, ROBERTO GONZALEZ SALINAS.',
    protectionKey: null,
    touchPenaltyKey: null,
    circumstantialRecord: null,
    preliminaryInquiry: null,
    criminalCase: null,
    addressee: null,
    expedientNumber: '736466',
    crimeKey: null,
    affairKey: '34',
    entFedKey: '2',
    viaKey: '2',
    consecutiveNumber: '12',
    observations: 'SE INFORMA IDENTIFICACIÓN DEL INMUEBLE.',
    delegationNumber: '1',
    subDelegationNumber: '0',
    institutionNumber: {
      id: '200',
      name: 'NUEVO CATALOGO',
      description: 'NUEVO CATALOGO',
      manager: null,
      street: null,
      numInside: null,
      numExterior: null,
      cologne: null,
      zipCode: null,
      delegMunic: null,
      phone: null,
      numClasif: '0',
      numCity: null,
      idCity: null,
      numRegister: '4613335',
      numTransference: null,
    },
    indiciadoNumber: '5',
    delDestinyNumber: '1',
    subDelDestinyNumber: '0',
    departamentDestinyNumber: '952',
    officeNumber: null,
    minpubNumber: null,
    cityNumber: '12',
    courtNumber: null,
    registerNumber: '771993612',
    dictumKey: 'DICTAMEN DE RECEPCION DE BIENES TRANSFERIDOS',
    identifier: 'TRANS',
    observationDictum: null,
    wheelStatus: 'PENDIENTE',
    transference: '752',
    expedientTransferenceNumber: 'H-194658',
    priority: 'N',
    wheelType: 'T',
    reserved: null,
    entryProcedureDate: '2018-04-20T00:00:00.000Z',
    userInsert: 'OST12721',
    originNumber: '109',
    stationNumber: '2',
    autorityNumber: '109',
    endTransferNumber: '752',
    dailyEviction: '0',
    hcCaptureDate: '2018-04-20T00:00:00.000Z',
    hcEntryProcedureDate: '2018-04-20T00:00:00.000Z',
    desKnowingDate: null,
    addressGeneral: '0',
    affair: {
      id: '34',
      description: 'DOCUMENTACIÓN COMPLEMENTARIA DE EXPEDIENTES',
      referralNoteType: 'T',
      creationUser: 'system',
      creationDate: '2016-04-06T00:00:00.000Z',
      editionUser: 'system',
      modificationDate: '2016-04-06T00:00:00.000Z',
      versionUser: 'S',
      status: null,
      registerNumber: '2271682',
      version: '1',
      processDetonate: 'RES_PAGO_ESPECIE',
      clv: 'N',
    },
    delegation: {
      id: '1',
      etapaEdo: '1',
      stateKey: '2',
      description: 'COORD. REGIONAL TIJUANA',
      addressOffice:
        'Edificio Torre Zentrum, calle Dr. Atl # 2084 Oficina 402, Col. Zona Urbana Río Tijuana, 22010, Tijuana, Baja California.\n',
      regionalDelegate: 'LIC. SAUL ALEJANDRO VEGA POMPA',
      zoneKey: 'Oeste',
      city: 'TIJUANA',
      status: null,
      iva: '0.1',
      noRegister: '20569',
      zoneContractKey: '1',
      zoneVigilanceKey: null,
      diffHours: '-2',
      version: '4',
      creationUser: 'system',
      creationDate: '2020-07-06T00:00:00.000Z',
      editionUser: 'eordonez',
      modificationDate: '2020-07-06T00:00:00.000Z',
      idZoneGeographic: '1',
    },
    subDelegation: {
      id: '0',
      phaseEdo: '1',
      delegationNumber: '1',
      description: 'TIJUANA',
      dailyConNumber: '10',
      dateDailyCon: '2005-08-30T00:00:00.000Z',
      registerNumber: '31440',
    },
    departament: null,
  },
  {
    wheelNumber: '1444808',
    receiptDate: '2018-04-20T00:00:00.000Z',
    captureDate: '2018-04-20T00:00:00.000Z',
    officeExternalKey: 'OPD/SINALOA/4004/2018',
    externalOfficeDate: '2018-03-28T00:00:00.000Z',
    externalRemitter: 'DORA GUADALUPE ROSAS SOTO - Enlace',
    protectionKey: null,
    touchPenaltyKey: null,
    circumstantialRecord: null,
    preliminaryInquiry: 'FED/SIN/CLN/0000782/2017',
    criminalCase: null,
    addressee: null,
    expedientNumber: '748076',
    crimeKey: '549',
    affairKey: '1',
    entFedKey: '25',
    viaKey: '16',
    consecutiveNumber: '9',
    observations:
      'PUESTA A DISPOSICION DE BIENES ASEGURADOS A TRAVES DE LA INTERFAZ CON PGR',
    delegationNumber: '5',
    subDelegationNumber: '0',
    institutionNumber: {
      id: '200',
      name: 'NUEVO CATALOGO',
      description: 'NUEVO CATALOGO',
      manager: null,
      street: null,
      numInside: null,
      numExterior: null,
      cologne: null,
      zipCode: null,
      delegMunic: null,
      phone: null,
      numClasif: '0',
      numCity: null,
      idCity: null,
      numRegister: '4613335',
      numTransference: null,
    },
    indiciadoNumber: '5',
    delDestinyNumber: '5',
    subDelDestinyNumber: '5',
    departamentDestinyNumber: '952',
    officeNumber: null,
    minpubNumber: null,
    cityNumber: '1851',
    courtNumber: null,
    registerNumber: '771990309',
    dictumKey: 'DICTAMEN DE RECEPCION FISICA DE BIENES ASEGURADOS',
    identifier: 'ASEG',
    observationDictum: null,
    wheelStatus: 'PENDIENTE',
    transference: '1',
    expedientTransferenceNumber: null,
    priority: 'N',
    wheelType: 'P',
    reserved: null,
    entryProcedureDate: '2018-04-20T00:00:00.000Z',
    userInsert: 'OST13186',
    originNumber: '139',
    stationNumber: '24',
    autorityNumber: '139',
    endTransferNumber: '1',
    dailyEviction: '0',
    hcCaptureDate: '2018-04-20T00:00:00.000Z',
    hcEntryProcedureDate: '2018-04-20T00:00:00.000Z',
    desKnowingDate: null,
    addressGeneral: null,
    affair: {
      id: '1',
      description: 'PUESTA A DISPOSICION DE BIENES ASEGURADOS',
      referralNoteType: 'P',
      creationUser: 'system',
      creationDate: '2016-04-06T00:00:00.000Z',
      editionUser: 'locana_dr',
      modificationDate: '2017-11-23T00:00:00.000Z',
      versionUser: 'S',
      status: null,
      registerNumber: '1371210',
      version: '6',
      processDetonate: 'AMPARO',
      clv: 'S',
    },
    delegation: {
      id: '5',
      etapaEdo: '1',
      stateKey: '25',
      description: 'COORD. REGIONAL CULIACAN',
      addressOffice:
        'Andador José González Hermosillo #1320, Col. Centro Sinaloa,  80101 , Culiacán, Sinaloa (Agosto 2008)\n',
      regionalDelegate: 'LIC. DINORA BÁEZ SAÑUDO',
      zoneKey: 'Oeste',
      city: 'CULIACÁN',
      status: null,
      iva: '0.16',
      noRegister: '20573',
      zoneContractKey: '1',
      zoneVigilanceKey: null,
      diffHours: '-1',
      version: null,
      creationUser: 'system',
      creationDate: '2016-04-05T00:00:00.000Z',
      editionUser: 'system',
      modificationDate: '2016-04-05T00:00:00.000Z',
      idZoneGeographic: '1',
    },
    subDelegation: null,
    departament: null,
  },
  {
    wheelNumber: '1444807',
    receiptDate: '2018-04-20T00:00:00.000Z',
    captureDate: '2018-04-20T00:00:00.000Z',
    officeExternalKey: '800-13-00-02-03-2018-5262',
    externalOfficeDate: '2018-04-17T00:00:00.000Z',
    externalRemitter: 'ANA BEATRIZ BARRERA TORRES',
    protectionKey: null,
    touchPenaltyKey: null,
    circumstantialRecord: null,
    preliminaryInquiry: null,
    criminalCase: null,
    addressee: null,
    expedientNumber: '748075',
    crimeKey: null,
    affairKey: '48',
    entFedKey: '2',
    viaKey: '1',
    consecutiveNumber: '11',
    observations:
      'TRANSFERENCIA ELECTRONICA DE DIVERSOS BIENES PARA SU VENTA, DONACION Y/O DESTRUCCION',
    delegationNumber: '1',
    subDelegationNumber: '0',
    institutionNumber: {
      id: '200',
      name: 'NUEVO CATALOGO',
      description: 'NUEVO CATALOGO',
      manager: null,
      street: null,
      numInside: null,
      numExterior: null,
      cologne: null,
      zipCode: null,
      delegMunic: null,
      phone: null,
      numClasif: '0',
      numCity: null,
      idCity: null,
      numRegister: '4613335',
      numTransference: null,
    },
    indiciadoNumber: '252925',
    delDestinyNumber: '1',
    subDelDestinyNumber: '0',
    departamentDestinyNumber: '952',
    officeNumber: null,
    minpubNumber: null,
    cityNumber: '15',
    courtNumber: null,
    registerNumber: '771990251',
    dictumKey: 'DICTAMEN DE RECEPCION DE BIENES TRANSFERIDOS',
    identifier: 'TRANS',
    observationDictum: null,
    wheelStatus: 'PENDIENTE',
    transference: '120',
    expedientTransferenceNumber: 'AUA400180003',
    priority: 'N',
    wheelType: 'T',
    reserved: null,
    entryProcedureDate: '2018-04-20T00:00:00.000Z',
    userInsert: 'TLPYZAMORANOTDR',
    originNumber: '44',
    stationNumber: '114',
    autorityNumber: '44',
    endTransferNumber: '120',
    dailyEviction: '0',
    hcCaptureDate: '2018-04-20T00:00:00.000Z',
    hcEntryProcedureDate: '2018-04-20T00:00:00.000Z',
    desKnowingDate: null,
    addressGeneral: null,
    affair: {
      id: '48',
      description: 'BIENES TRANSFERIDOS PARA SU VENTA/DON Y/O DEST.',
      referralNoteType: 'T',
      creationUser: null,
      creationDate: '2022-12-28T00:00:00.000Z',
      editionUser: null,
      modificationDate: '2022-12-28T00:00:00.000Z',
      versionUser: 'S',
      status: null,
      registerNumber: '3051508',
      version: null,
      processDetonate: null,
      clv: 'S',
    },
    delegation: {
      id: '1',
      etapaEdo: '1',
      stateKey: '2',
      description: 'COORD. REGIONAL TIJUANA',
      addressOffice:
        'Edificio Torre Zentrum, calle Dr. Atl # 2084 Oficina 402, Col. Zona Urbana Río Tijuana, 22010, Tijuana, Baja California.\n',
      regionalDelegate: 'LIC. SAUL ALEJANDRO VEGA POMPA',
      zoneKey: 'Oeste',
      city: 'TIJUANA',
      status: null,
      iva: '0.1',
      noRegister: '20569',
      zoneContractKey: '1',
      zoneVigilanceKey: null,
      diffHours: '-2',
      version: '4',
      creationUser: 'system',
      creationDate: '2020-07-06T00:00:00.000Z',
      editionUser: 'eordonez',
      modificationDate: '2020-07-06T00:00:00.000Z',
      idZoneGeographic: '1',
    },
    subDelegation: {
      id: '0',
      phaseEdo: '1',
      delegationNumber: '1',
      description: 'TIJUANA',
      dailyConNumber: '10',
      dateDailyCon: '2005-08-30T00:00:00.000Z',
      registerNumber: '31440',
    },
    departament: null,
  },
  {
    wheelNumber: '1444806',
    receiptDate: '2018-04-20T00:00:00.000Z',
    captureDate: '2018-04-20T00:00:00.000Z',
    officeExternalKey: '800-19-00-01-02-2018-7130',
    externalOfficeDate: '2018-04-09T00:00:00.000Z',
    externalRemitter: 'JULIA ELIZABETH MUÑIZ SIERRA',
    protectionKey: null,
    touchPenaltyKey: null,
    circumstantialRecord: null,
    preliminaryInquiry: null,
    criminalCase: null,
    addressee: null,
    expedientNumber: '748074',
    crimeKey: null,
    affairKey: '48',
    entFedKey: '8',
    viaKey: '1',
    consecutiveNumber: '1',
    observations:
      'TRANSFERENCIA ELECTRONICA DE DIVERSOS BIENES PARA SU VENTA, DONACION Y/O DESTRUCCION',
    delegationNumber: '6',
    subDelegationNumber: '0',
    institutionNumber: {
      id: '200',
      name: 'NUEVO CATALOGO',
      description: 'NUEVO CATALOGO',
      manager: null,
      street: null,
      numInside: null,
      numExterior: null,
      cologne: null,
      zipCode: null,
      delegMunic: null,
      phone: null,
      numClasif: '0',
      numCity: null,
      idCity: null,
      numRegister: '4613335',
      numTransference: null,
    },
    indiciadoNumber: '167743',
    delDestinyNumber: '6',
    subDelDestinyNumber: '0',
    departamentDestinyNumber: '952',
    officeNumber: null,
    minpubNumber: null,
    cityNumber: '262',
    courtNumber: null,
    registerNumber: '771990227',
    dictumKey: 'DICTAMEN DE RECEPCION DE BIENES TRANSFERIDOS',
    identifier: 'TRANS',
    observationDictum: null,
    wheelStatus: 'PENDIENTE',
    transference: '120',
    expedientTransferenceNumber: 'EX17/0950, EX17/0949, EX17/0953, EX17/0948',
    priority: 'N',
    wheelType: 'T',
    reserved: null,
    entryProcedureDate: '2018-04-20T00:00:00.000Z',
    userInsert: 'TLPJSANTIAGOTDR',
    originNumber: '22',
    stationNumber: '114',
    autorityNumber: '22',
    endTransferNumber: '120',
    dailyEviction: '0',
    hcCaptureDate: '2018-04-20T00:00:00.000Z',
    hcEntryProcedureDate: '2018-04-20T00:00:00.000Z',
    desKnowingDate: null,
    addressGeneral: null,
    affair: {
      id: '48',
      description: 'BIENES TRANSFERIDOS PARA SU VENTA/DON Y/O DEST.',
      referralNoteType: 'T',
      creationUser: null,
      creationDate: '2022-12-28T00:00:00.000Z',
      editionUser: null,
      modificationDate: '2022-12-28T00:00:00.000Z',
      versionUser: 'S',
      status: null,
      registerNumber: '3051508',
      version: null,
      processDetonate: null,
      clv: 'S',
    },
    delegation: {
      id: '6',
      etapaEdo: '1',
      stateKey: '15',
      description: 'COORD. REGIONAL GUADALAJARA',
      addressOffice:
        'Avenida Rubén Darío número 1109, cuarto piso, colonia Providencia, municipio de Guadalajara, Jalisco, C.P. 44630',
      regionalDelegate: 'ING. GUSTAVO ADOLFO IZAGUIRRE NAVARRO ',
      zoneKey: 'Oeste',
      city: 'GUADALAJARA',
      status: null,
      iva: '0.16',
      noRegister: '20574',
      zoneContractKey: '2',
      zoneVigilanceKey: null,
      diffHours: '0',
      version: null,
      creationUser: 'system',
      creationDate: '2016-04-05T00:00:00.000Z',
      editionUser: 'system',
      modificationDate: '2016-04-05T00:00:00.000Z',
      idZoneGeographic: '1',
    },
    subDelegation: {
      id: '0',
      phaseEdo: '1',
      delegationNumber: '6',
      description: 'GUADALAJARA',
      dailyConNumber: '9',
      dateDailyCon: '2005-09-05T00:00:00.000Z',
      registerNumber: '31445',
    },
    departament: null,
  },
  {
    wheelNumber: '1444805',
    receiptDate: '2018-04-20T00:00:00.000Z',
    captureDate: '2018-04-20T00:00:00.000Z',
    officeExternalKey: '400-12-00-01-00-2018-00862',
    externalOfficeDate: '2018-04-03T00:00:00.000Z',
    externalRemitter: 'ROBERTO GONZALEZ SALINAS',
    protectionKey: null,
    touchPenaltyKey: null,
    circumstantialRecord: null,
    preliminaryInquiry: null,
    criminalCase: null,
    addressee: null,
    expedientNumber: '742593',
    crimeKey: null,
    affairKey: '34',
    entFedKey: '2',
    viaKey: '2',
    consecutiveNumber: '10',
    observations: 'SE INFORMA CAMBIO DE SITUACIÓN OCUPACIONAL.',
    delegationNumber: '1',
    subDelegationNumber: '0',
    institutionNumber: {
      id: '200',
      name: 'NUEVO CATALOGO',
      description: 'NUEVO CATALOGO',
      manager: null,
      street: null,
      numInside: null,
      numExterior: null,
      cologne: null,
      zipCode: null,
      delegMunic: null,
      phone: null,
      numClasif: '0',
      numCity: null,
      idCity: null,
      numRegister: '4613335',
      numTransference: null,
    },
    indiciadoNumber: '5',
    delDestinyNumber: '1',
    subDelDestinyNumber: '0',
    departamentDestinyNumber: '1',
    officeNumber: null,
    minpubNumber: null,
    cityNumber: null,
    courtNumber: null,
    registerNumber: '771989695',
    dictumKey: null,
    identifier: 'TRANS',
    observationDictum: null,
    wheelStatus: 'PENDIENTE',
    transference: '752',
    expedientTransferenceNumber: '199760',
    priority: 'N',
    wheelType: 'T',
    reserved: null,
    entryProcedureDate: '2018-04-20T00:00:00.000Z',
    userInsert: 'OST12721',
    originNumber: '123',
    stationNumber: '2',
    autorityNumber: '123',
    endTransferNumber: '752',
    dailyEviction: '0',
    hcCaptureDate: '2018-04-20T00:00:00.000Z',
    hcEntryProcedureDate: '2018-04-20T00:00:00.000Z',
    desKnowingDate: null,
    addressGeneral: '0',
    affair: {
      id: '34',
      description: 'DOCUMENTACIÓN COMPLEMENTARIA DE EXPEDIENTES',
      referralNoteType: 'T',
      creationUser: 'system',
      creationDate: '2016-04-06T00:00:00.000Z',
      editionUser: 'system',
      modificationDate: '2016-04-06T00:00:00.000Z',
      versionUser: 'S',
      status: null,
      registerNumber: '2271682',
      version: '1',
      processDetonate: 'RES_PAGO_ESPECIE',
      clv: 'N',
    },
    delegation: {
      id: '1',
      etapaEdo: '1',
      stateKey: '2',
      description: 'COORD. REGIONAL TIJUANA',
      addressOffice:
        'Edificio Torre Zentrum, calle Dr. Atl # 2084 Oficina 402, Col. Zona Urbana Río Tijuana, 22010, Tijuana, Baja California.\n',
      regionalDelegate: 'LIC. SAUL ALEJANDRO VEGA POMPA',
      zoneKey: 'Oeste',
      city: 'TIJUANA',
      status: null,
      iva: '0.1',
      noRegister: '20569',
      zoneContractKey: '1',
      zoneVigilanceKey: null,
      diffHours: '-2',
      version: '4',
      creationUser: 'system',
      creationDate: '2020-07-06T00:00:00.000Z',
      editionUser: 'eordonez',
      modificationDate: '2020-07-06T00:00:00.000Z',
      idZoneGeographic: '1',
    },
    subDelegation: {
      id: '0',
      phaseEdo: '1',
      delegationNumber: '1',
      description: 'TIJUANA',
      dailyConNumber: '10',
      dateDailyCon: '2005-08-30T00:00:00.000Z',
      registerNumber: '31440',
    },
    departament: {
      id: '1',
      numDelegation: '8',
      numSubDelegation: '0',
      phaseEdo: '2',
      dsarea: 'JUR',
      description: 'JURIDICO',
      lastOffice: '7',
      numRegister: '61779656',
      level: '5',
      depend: '8',
      depDelegation: '8',
    },
  },
  {
    wheelNumber: '1444804',
    receiptDate: '2018-04-20T00:00:00.000Z',
    captureDate: '2018-04-20T00:00:00.000Z',
    officeExternalKey: 'OPD/SINALOA/5616/2018',
    externalOfficeDate: '2018-03-27T00:00:00.000Z',
    externalRemitter: 'DORA GUADALUPE ROSAS SOTO - Enlace',
    protectionKey: null,
    touchPenaltyKey: null,
    circumstantialRecord: null,
    preliminaryInquiry: 'FED/SIN/CLN/0000152/2018',
    criminalCase: null,
    addressee: null,
    expedientNumber: '748073',
    crimeKey: '549',
    affairKey: '1',
    entFedKey: '25',
    viaKey: '16',
    consecutiveNumber: '8',
    observations:
      'PUESTA A DISPOSICION DE BIENES ASEGURADOS A TRAVES DE LA INTERFAZ CON PGR',
    delegationNumber: '5',
    subDelegationNumber: '0',
    institutionNumber: {
      id: '200',
      name: 'NUEVO CATALOGO',
      description: 'NUEVO CATALOGO',
      manager: null,
      street: null,
      numInside: null,
      numExterior: null,
      cologne: null,
      zipCode: null,
      delegMunic: null,
      phone: null,
      numClasif: '0',
      numCity: null,
      idCity: null,
      numRegister: '4613335',
      numTransference: null,
    },
    indiciadoNumber: '5',
    delDestinyNumber: '5',
    subDelDestinyNumber: '5',
    departamentDestinyNumber: '952',
    officeNumber: null,
    minpubNumber: null,
    cityNumber: '1851',
    courtNumber: null,
    registerNumber: '771989681',
    dictumKey: 'DICTAMEN DE RECEPCION FISICA DE BIENES ASEGURADOS',
    identifier: 'ASEG',
    observationDictum: null,
    wheelStatus: 'PENDIENTE',
    transference: '1',
    expedientTransferenceNumber: null,
    priority: 'N',
    wheelType: 'P',
    reserved: null,
    entryProcedureDate: '2018-04-20T00:00:00.000Z',
    userInsert: 'OST13186',
    originNumber: '139',
    stationNumber: '24',
    autorityNumber: '139',
    endTransferNumber: '1',
    dailyEviction: '0',
    hcCaptureDate: '2018-04-20T00:00:00.000Z',
    hcEntryProcedureDate: '2018-04-20T00:00:00.000Z',
    desKnowingDate: null,
    addressGeneral: null,
    affair: {
      id: '1',
      description: 'PUESTA A DISPOSICION DE BIENES ASEGURADOS',
      referralNoteType: 'P',
      creationUser: 'system',
      creationDate: '2016-04-06T00:00:00.000Z',
      editionUser: 'locana_dr',
      modificationDate: '2017-11-23T00:00:00.000Z',
      versionUser: 'S',
      status: null,
      registerNumber: '1371210',
      version: '6',
      processDetonate: 'AMPARO',
      clv: 'S',
    },
    delegation: {
      id: '5',
      etapaEdo: '1',
      stateKey: '25',
      description: 'COORD. REGIONAL CULIACAN',
      addressOffice:
        'Andador José González Hermosillo #1320, Col. Centro Sinaloa,  80101 , Culiacán, Sinaloa (Agosto 2008)\n',
      regionalDelegate: 'LIC. DINORA BÁEZ SAÑUDO',
      zoneKey: 'Oeste',
      city: 'CULIACÁN',
      status: null,
      iva: '0.16',
      noRegister: '20573',
      zoneContractKey: '1',
      zoneVigilanceKey: null,
      diffHours: '-1',
      version: null,
      creationUser: 'system',
      creationDate: '2016-04-05T00:00:00.000Z',
      editionUser: 'system',
      modificationDate: '2016-04-05T00:00:00.000Z',
      idZoneGeographic: '1',
    },
    subDelegation: null,
    departament: null,
  },
  {
    wheelNumber: '1444803',
    receiptDate: '2018-04-20T00:00:00.000Z',
    captureDate: '2018-04-20T00:00:00.000Z',
    officeExternalKey: 'DGAAR/043/2018',
    externalOfficeDate: '2018-01-22T00:00:00.000Z',
    externalRemitter: 'CESAR AUGUSTO GOMEZ MORALES',
    protectionKey: null,
    touchPenaltyKey: null,
    circumstantialRecord: null,
    preliminaryInquiry: null,
    criminalCase: null,
    addressee: null,
    expedientNumber: '654883',
    crimeKey: null,
    affairKey: '34',
    entFedKey: '9',
    viaKey: '14',
    consecutiveNumber: '1',
    observations: 'DUPLICADO',
    delegationNumber: '4',
    subDelegationNumber: '0',
    institutionNumber: {
      id: '200',
      name: 'NUEVO CATALOGO',
      description: 'NUEVO CATALOGO',
      manager: null,
      street: null,
      numInside: null,
      numExterior: null,
      cologne: null,
      zipCode: null,
      delegMunic: null,
      phone: null,
      numClasif: '0',
      numCity: null,
      idCity: null,
      numRegister: '4613335',
      numTransference: null,
    },
    indiciadoNumber: '5',
    delDestinyNumber: '4',
    subDelDestinyNumber: '0',
    departamentDestinyNumber: '952',
    officeNumber: null,
    minpubNumber: null,
    cityNumber: '266',
    courtNumber: null,
    registerNumber: '771989236',
    dictumKey: 'DICTAMEN DE RECEPCION DE BIENES TRANSFERIDOS',
    identifier: 'TRANS',
    observationDictum: null,
    wheelStatus: 'PENDIENTE',
    transference: '300',
    expedientTransferenceNumber: 'S/N',
    priority: 'N',
    wheelType: 'T',
    reserved: null,
    entryProcedureDate: '2018-04-20T00:00:00.000Z',
    userInsert: 'OST12495',
    originNumber: '1',
    stationNumber: '112',
    autorityNumber: '1',
    endTransferNumber: '300',
    dailyEviction: '0',
    hcCaptureDate: '2018-04-20T00:00:00.000Z',
    hcEntryProcedureDate: '2018-04-20T00:00:00.000Z',
    desKnowingDate: null,
    addressGeneral: '0',
    affair: {
      id: '34',
      description: 'DOCUMENTACIÓN COMPLEMENTARIA DE EXPEDIENTES',
      referralNoteType: 'T',
      creationUser: 'system',
      creationDate: '2016-04-06T00:00:00.000Z',
      editionUser: 'system',
      modificationDate: '2016-04-06T00:00:00.000Z',
      versionUser: 'S',
      status: null,
      registerNumber: '2271682',
      version: '1',
      processDetonate: 'RES_PAGO_ESPECIE',
      clv: 'N',
    },
    delegation: {
      id: '4',
      etapaEdo: '1',
      stateKey: '19',
      description: 'COORD. REGIONAL MONTERREY',
      addressOffice:
        'Lázaro Cárdenas No. 1010 Piso 7, Residencial San Agustín, CP. 66260, San Pedro Garza García, Nuevo León',
      regionalDelegate: 'LIC. ALEJANDRO RABAGO  HERNANDEZ',
      zoneKey: 'Este',
      city: 'GENERAL ESCOBEDO',
      status: null,
      iva: '0.16',
      noRegister: '20572',
      zoneContractKey: '1',
      zoneVigilanceKey: null,
      diffHours: '0',
      version: null,
      creationUser: 'system',
      creationDate: '2016-04-05T00:00:00.000Z',
      editionUser: 'system',
      modificationDate: '2016-04-05T00:00:00.000Z',
      idZoneGeographic: '2',
    },
    subDelegation: {
      id: '0',
      phaseEdo: '1',
      delegationNumber: '4',
      description: 'MONTERREY',
      dailyConNumber: '11',
      dateDailyCon: '2005-09-01T00:00:00.000Z',
      registerNumber: '31443',
    },
    departament: null,
  },
  {
    wheelNumber: '1444802',
    receiptDate: '2018-04-20T00:00:00.000Z',
    captureDate: '2018-04-20T00:00:00.000Z',
    officeExternalKey: 'OPD/SINALOA/5497/2018',
    externalOfficeDate: '2018-03-27T00:00:00.000Z',
    externalRemitter: 'DORA GUADALUPE ROSAS SOTO - Enlace',
    protectionKey: null,
    touchPenaltyKey: null,
    circumstantialRecord: null,
    preliminaryInquiry: 'FED/SIN/CLN/0002668/2017',
    criminalCase: null,
    addressee: null,
    expedientNumber: '748072',
    crimeKey: '549',
    affairKey: '1',
    entFedKey: '25',
    viaKey: '16',
    consecutiveNumber: '7',
    observations:
      'PUESTA A DISPOSICION DE BIENES ASEGURADOS A TRAVES DE LA INTERFAZ CON PGR',
    delegationNumber: '5',
    subDelegationNumber: '0',
    institutionNumber: {
      id: '200',
      name: 'NUEVO CATALOGO',
      description: 'NUEVO CATALOGO',
      manager: null,
      street: null,
      numInside: null,
      numExterior: null,
      cologne: null,
      zipCode: null,
      delegMunic: null,
      phone: null,
      numClasif: '0',
      numCity: null,
      idCity: null,
      numRegister: '4613335',
      numTransference: null,
    },
    indiciadoNumber: '5',
    delDestinyNumber: '5',
    subDelDestinyNumber: '5',
    departamentDestinyNumber: '952',
    officeNumber: null,
    minpubNumber: null,
    cityNumber: '1851',
    courtNumber: null,
    registerNumber: '771979065',
    dictumKey: 'ACLARACION DE INFORMACION A AUTORIDADES EXTERNAS',
    identifier: 'ASEG',
    observationDictum: null,
    wheelStatus: 'PENDIENTE',
    transference: '1',
    expedientTransferenceNumber: null,
    priority: 'N',
    wheelType: 'P',
    reserved: null,
    entryProcedureDate: '2018-04-20T00:00:00.000Z',
    userInsert: 'OST13186',
    originNumber: '139',
    stationNumber: '24',
    autorityNumber: '139',
    endTransferNumber: '1',
    dailyEviction: '0',
    hcCaptureDate: '2018-04-20T00:00:00.000Z',
    hcEntryProcedureDate: '2018-04-20T00:00:00.000Z',
    desKnowingDate: null,
    addressGeneral: null,
    affair: {
      id: '1',
      description: 'PUESTA A DISPOSICION DE BIENES ASEGURADOS',
      referralNoteType: 'P',
      creationUser: 'system',
      creationDate: '2016-04-06T00:00:00.000Z',
      editionUser: 'locana_dr',
      modificationDate: '2017-11-23T00:00:00.000Z',
      versionUser: 'S',
      status: null,
      registerNumber: '1371210',
      version: '6',
      processDetonate: 'AMPARO',
      clv: 'S',
    },
    delegation: {
      id: '5',
      etapaEdo: '1',
      stateKey: '25',
      description: 'COORD. REGIONAL CULIACAN',
      addressOffice:
        'Andador José González Hermosillo #1320, Col. Centro Sinaloa,  80101 , Culiacán, Sinaloa (Agosto 2008)\n',
      regionalDelegate: 'LIC. DINORA BÁEZ SAÑUDO',
      zoneKey: 'Oeste',
      city: 'CULIACÁN',
      status: null,
      iva: '0.16',
      noRegister: '20573',
      zoneContractKey: '1',
      zoneVigilanceKey: null,
      diffHours: '-1',
      version: null,
      creationUser: 'system',
      creationDate: '2016-04-05T00:00:00.000Z',
      editionUser: 'system',
      modificationDate: '2016-04-05T00:00:00.000Z',
      idZoneGeographic: '1',
    },
    subDelegation: null,
    departament: null,
  },
  {
    wheelNumber: '1444801',
    receiptDate: '2018-04-20T00:00:00.000Z',
    captureDate: '2018-04-20T00:00:00.000Z',
    officeExternalKey: '400-12-00-01-00-2018-00843',
    externalOfficeDate: '2018-04-02T00:00:00.000Z',
    externalRemitter: 'C.P. ROBERTO GONZALEZ SALINAS',
    protectionKey: null,
    touchPenaltyKey: null,
    circumstantialRecord: null,
    preliminaryInquiry: null,
    criminalCase: null,
    addressee: null,
    expedientNumber: '742593',
    crimeKey: null,
    affairKey: '34',
    entFedKey: '2',
    viaKey: '2',
    consecutiveNumber: '9',
    observations: 'SEINFORMA PERSONAL DESIGNADO PARA LA ENTREGA RECEPCIÓN.',
    delegationNumber: '1',
    subDelegationNumber: '0',
    institutionNumber: {
      id: '200',
      name: 'NUEVO CATALOGO',
      description: 'NUEVO CATALOGO',
      manager: null,
      street: null,
      numInside: null,
      numExterior: null,
      cologne: null,
      zipCode: null,
      delegMunic: null,
      phone: null,
      numClasif: '0',
      numCity: null,
      idCity: null,
      numRegister: '4613335',
      numTransference: null,
    },
    indiciadoNumber: '5',
    delDestinyNumber: '1',
    subDelDestinyNumber: '0',
    departamentDestinyNumber: '952',
    officeNumber: null,
    minpubNumber: null,
    cityNumber: '12',
    courtNumber: null,
    registerNumber: '771978710',
    dictumKey: 'CONOCIMIENTO',
    identifier: 'TRANS',
    observationDictum: null,
    wheelStatus: 'PENDIENTE',
    transference: '752',
    expedientTransferenceNumber: '199760',
    priority: 'N',
    wheelType: 'T',
    reserved:
      '20-04-2018  12:49 (Usuario: OST12721). DE CONOCIMIENTO PARA EL SAE',
    entryProcedureDate: '2018-04-20T00:00:00.000Z',
    userInsert: 'OST12721',
    originNumber: '109',
    stationNumber: '2',
    autorityNumber: '109',
    endTransferNumber: '752',
    dailyEviction: '0',
    hcCaptureDate: '2018-04-20T00:00:00.000Z',
    hcEntryProcedureDate: '2018-04-20T00:00:00.000Z',
    desKnowingDate: '2018-04-20T00:00:00.000Z',
    addressGeneral: '0',
    affair: {
      id: '34',
      description: 'DOCUMENTACIÓN COMPLEMENTARIA DE EXPEDIENTES',
      referralNoteType: 'T',
      creationUser: 'system',
      creationDate: '2016-04-06T00:00:00.000Z',
      editionUser: 'system',
      modificationDate: '2016-04-06T00:00:00.000Z',
      versionUser: 'S',
      status: null,
      registerNumber: '2271682',
      version: '1',
      processDetonate: 'RES_PAGO_ESPECIE',
      clv: 'N',
    },
    delegation: {
      id: '1',
      etapaEdo: '1',
      stateKey: '2',
      description: 'COORD. REGIONAL TIJUANA',
      addressOffice:
        'Edificio Torre Zentrum, calle Dr. Atl # 2084 Oficina 402, Col. Zona Urbana Río Tijuana, 22010, Tijuana, Baja California.\n',
      regionalDelegate: 'LIC. SAUL ALEJANDRO VEGA POMPA',
      zoneKey: 'Oeste',
      city: 'TIJUANA',
      status: null,
      iva: '0.1',
      noRegister: '20569',
      zoneContractKey: '1',
      zoneVigilanceKey: null,
      diffHours: '-2',
      version: '4',
      creationUser: 'system',
      creationDate: '2020-07-06T00:00:00.000Z',
      editionUser: 'eordonez',
      modificationDate: '2020-07-06T00:00:00.000Z',
      idZoneGeographic: '1',
    },
    subDelegation: {
      id: '0',
      phaseEdo: '1',
      delegationNumber: '1',
      description: 'TIJUANA',
      dailyConNumber: '10',
      dateDailyCon: '2005-08-30T00:00:00.000Z',
      registerNumber: '31440',
    },
    departament: null,
  },
];

export const DOCUMENTS_RECEPTION_TRACK_RECORDS_TEST_DATA = notifsTestData;
