export const unitsData = [
  {
    id: 1,
    unit: 'UNIDAD',
    decimals: 'N',
    registryNumber: 3421208,
    description: 'Unidades',
    unitNumber: 7,
    trial476: 'T',
  },
  {
    id: 2,
    unit: 'LITRO',
    decimals: 'S',
    registryNumber: 3421209,
    description: 'Litros',
    unitNumber: 3,
    trial476: 'T',
  },
  {
    id: 3,
    unit: 'METRO',
    decimals: 'S',
    registryNumber: 3421210,
    description: 'Metros',
    unitNumber: 4,
    trial476: 'T',
  },
  {
    id: 4,
    unit: 'PAR',
    decimals: 'N',
    registryNumber: 3421211,
    description: 'Pares',
    unitNumber: 5,
    trial476: 'T',
  },
  {
    id: 5,
    unit: 'PIEZA',
    decimals: 'N',
    registryNumber: 3421212,
    description: 'Piezas',
    unitNumber: 6,
    trial476: 'T',
  },
  {
    id: 6,
    unit: 'JUEGO',
    decimals: 'N',
    registryNumber: 3421213,
    description: 'Juegos',
    unitNumber: 1,
    trial476: 'T',
  },
  {
    id: 7,
    unit: 'CAJAS',
    decimals: 'N',
    registryNumber: 4250023,
    description: 'cajas',
    unitNumber: 8,
    trial476: 'T',
  },
  {
    id: 8,
    unit: 'M3',
    decimals: 'S',
    registryNumber: 5527999,
    description: 'Metros cubicos',
    unitNumber: 9,
    trial476: 'T',
  },
  {
    id: 9,
    unit: 'KILOGRAMO',
    decimals: 'S',
    registryNumber: 3421216,
    description: 'Kilos',
    unitNumber: 2,
    trial476: 'T',
  },
];
