export const dataCustomers = [
  {
    customerId: 1469,
    customerName: 'RODOLFO SILVEYRA IBARRA',
    rfc: 'SIIR480502JA1',
    id_vendedor: 'NULL',
    calle: 'AVE FRANCISCO I MAD PTE 1701',
    ciudad: 'LOS MOCHIS',
    colonia: 'CUAUHTEMOC',
    delegacion: 'LOS MOCHIS',
    cp: 81249,
    pais: 'MÉXICO',
    fax: 'NULL',
    telefono: 'NULL',
    correoweb: 'silveyra@hotmail.com',
    estado: 'SINALOA',
    curp: 'NULL',
    lista_negra: 'N',
    apellido_paterno: '',
    apellido_materno: '',
    muni_id: 'NULL',
    esta_id: 25,
    fecha_lista_negra: 'NULL',
    fecha_liberacion: '2020-01-08',
    id_penalizacion: 1,
    tipo_persona: 'F',
    rfc_homologado: 'NULL',
    usu_libera: 'SERA',
    fec_libera: 'NULL',
    no_registro: 685806294,
    cve_act_economica: 'NULL',
    tipo_identificacion: 'NULL',
    num_identificacion: 'NULL',
    id_representante: 'NULL',
    no_exterior: 'NULL',
    no_interior: 'NULL',
    contrasena: 'NULL',
    usuario: 'NULL',
    clabe_interbancaria: 'NULL',
    banco: 'NULL',
    sucursal: 'NULL',
    cuenta_cheques: 'NULL',
    fec_ini_penalizacion: 'NULL',
    fec_fin_penalizacion: 'NULL',
    usu_penaliza: 'ADABDOUB',
  },
  {
    customerId: 1441,
    customerName: 'ALCANTARA REYES MIGUEL ANGEL',
    rfc: 'ALRM750802',
    id_vendedor: 'NULL',
    calle: 'Cuautitlan #144 mz 213 lt.28 #144',
    ciudad: 'ECATEPEC',
    colonia: 'CD.AZTECA',
    delegacion: 'ECATEPEC',
    cp: 55120,
    pais: 'MÉXICO',
    fax: 'NULL',
    telefono: 26461945,
    correoweb: 'NULL',
    estado: 'MEXICO, D.F.',
    curp: 'NULL',
    lista_negra: 'N',
    apellido_paterno: '',
    apellido_materno: '',
    muni_id: 'NULL',
    esta_id: 9,
    fecha_lista_negra: 'NULL',
    fecha_liberacion: 'NULL',
    id_penalizacion: 'NULL',
    tipo_persona: 'F',
    rfc_homologado: 'NULL',
    usu_libera: 'NULL',
    fec_libera: 'NULL',
    no_registro: 667418740,
    cve_act_economica: 'NULL',
    tipo_identificacion: 'NULL',
    num_identificacion: 'NULL',
    id_representante: 'NULL',
    no_exterior: 'NULL',
    no_interior: 'NULL',
    contrasena: 'NULL',
    usuario: 'NULL',
    clabe_interbancaria: 'NULL',
    banco: 'NULL',
    sucursal: 'NULL',
    cuenta_cheques: 'NULL',
    fec_ini_penalizacion: 'NULL',
    fec_fin_penalizacion: 'NULL',
    usu_penaliza: 'NULL',
  },
  {
    customerId: 1442,
    customerName: 'PEREZ TEXTLE JOSE AARON',
    rfc: 'PETJ700101',
    id_vendedor: 'NULL',
    calle: 'Tenochtitlan #2',
    ciudad: 'ZACATELCO',
    colonia: 'SECCION CUARTA',
    delegacion: 'ZACATELCO',
    cp: 90750,
    pais: 'MÉXICO',
    fax: 'NULL',
    telefono: 'NULL',
    correoweb: 'NULL',
    estado: 'MÉXICO, D.F.',
    curp: 'NULL',
    lista_negra: 'N',
    apellido_paterno: '',
    apellido_materno: '',
    muni_id: 'NULL',
    esta_id: 9,
    fecha_lista_negra: 'NULL',
    fecha_liberacion: 'NULL',
    id_penalizacion: 'NULL',
    tipo_persona: 'F',
    rfc_homologado: 'NULL',
    usu_libera: 'NULL',
    fec_libera: 'NULL',
    no_registro: 680471879,
    cve_act_economica: 'NULL',
    tipo_identificacion: 'NULL',
    num_identificacion: 'NULL',
    id_representante: 'NULL',
    no_exterior: 'NULL',
    no_interior: 'NULL',
    contrasena: 'NULL',
    usuario: 'NULL',
    clabe_interbancaria: 'NULL',
    banco: 'NULL',
    sucursal: 'NULL',
    cuenta_cheques: 'NULL',
    fec_ini_penalizacion: 'NULL',
    fec_fin_penalizacion: 'NULL',
    usu_penaliza: 'NULL',
  },
  {
    customerId: 1471,
    customerName: 'SANTDRA MARIBEL PARRA CORONA',
    rfc: 'PACS8001089N4',
    id_vendedor: 'NULL',
    calle: 'PRL MARIANO ARISTA 4452',
    ciudad: 'VERACRUZ',
    colonia: 'DOS CAMINOS',
    delegacion: 'VERACRUZ',
    cp: 91726,
    pais: 'MÉXICO',
    fax: 'NULL',
    telefono: 12299206274,
    correoweb: 'vicda_sanchez@hotmail.com',
    estado: 'VERACRUZ',
    curp: 'NULL',
    lista_negra: 'N',
    apellido_paterno: '',
    apellido_materno: '',
    muni_id: 'NULL',
    esta_id: 30,
    fecha_lista_negra: 'NULL',
    fecha_liberacion: 'NULL',
    id_penalizacion: 'NULL',
    tipo_persona: 'F',
    rfc_homologado: 'NULL',
    usu_libera: 'NULL',
    fec_libera: 'NULL',
    no_registro: 685805771,
    cve_act_economica: 'NULL',
    tipo_identificacion: 'NULL',
    num_identificacion: 'NULL',
    id_representante: 'NULL',
    no_exterior: 'NULL',
    no_interior: 'NULL',
    contrasena: 'NULL',
    usuario: 'NULL',
    clabe_interbancaria: 'NULL',
    banco: 'NULL',
    sucursal: 'NULL',
    cuenta_cheques: 'NULL',
    fec_ini_penalizacion: 'NULL',
    fec_fin_penalizacion: 'NULL',
    usu_penaliza: 'NULL',
  },
  {
    customerId: 1472,
    customerName: 'ADOLFO ALFONSO CARDENAS FRANCO',
    rfc: 'CAFA631017',
    id_vendedor: 'NULL',
    calle: 'CZA de Guadalupe casa 502 Modulo 3',
    ciudad: 'COYOACAN',
    colonia: 'JARDINES DE COAPA',
    delegacion: 'COYOACAN',
    cp: 'NULL',
    pais: 'MÉXICO',
    fax: 'NULL',
    telefono: 'NULL',
    correoweb: 'adolcarfra@yahoo.com.mx',
    estado: 'DISTRITO FEDERAL',
    curp: 'NULL',
    lista_negra: 'N',
    apellido_paterno: '',
    apellido_materno: '',
    muni_id: 'NULL',
    esta_id: 9,
    fecha_lista_negra: 'NULL',
    fecha_liberacion: 'NULL',
    id_penalizacion: 'NULL',
    tipo_persona: 'F',
    rfc_homologado: 'NULL',
    usu_libera: 'NULL',
    fec_libera: 'NULL',
    no_registro: 680471880,
    cve_act_economica: 'NULL',
    tipo_identificacion: 'NULL',
    num_identificacion: 'NULL',
    id_representante: 'NULL',
    no_exterior: 'NULL',
    no_interior: 'NULL',
    contrasena: 'NULL',
    usuario: 'NULL',
    clabe_interbancaria: 'NULL',
    banco: 'NULL',
    sucursal: 'NULL',
    cuenta_cheques: 'NULL',
    fec_ini_penalizacion: 'NULL',
    fec_fin_penalizacion: 'NULL',
    usu_penaliza: 'NULL',
  },
  {
    customerId: 1473,
    customerName: 'AGUSTIN AGUILAR CRUZ',
    rfc: 'AUCA740306I15',
    id_vendedor: 'NULL',
    calle: 'TORTOLAS 5',
    ciudad: 'NICOLAS ROMERO',
    colonia: 'GRANADAS DE GUADALUPE',
    delegacion: 'NICOLAS ROMERO',
    cp: 54474,
    pais: 'MÉXICO',
    fax: 'NULL',
    telefono: 58273425,
    correoweb: 'agustinici@prodigy.net.mx',
    estado: 'ESTADO DE MEXICO',
    curp: 'NULL',
    lista_negra: 'N',
    apellido_paterno: '',
    apellido_materno: '',
    muni_id: 'NULL',
    esta_id: 15,
    fecha_lista_negra: 'NULL',
    fecha_liberacion: 'NULL',
    id_penalizacion: 'NULL',
    tipo_persona: 'F',
    rfc_homologado: 'NULL',
    usu_libera: 'NULL',
    fec_libera: 'NULL',
    no_registro: 685823971,
    cve_act_economica: 'NULL',
    tipo_identificacion: 'NULL',
    num_identificacion: 'NULL',
    id_representante: 'NULL',
    no_exterior: 'NULL',
    no_interior: 'NULL',
    contrasena: 'NULL',
    usuario: 'NULL',
    clabe_interbancaria: 'NULL',
    banco: 'NULL',
    sucursal: 'NULL',
    cuenta_cheques: 'NULL',
    fec_ini_penalizacion: 'NULL',
    fec_fin_penalizacion: 'NULL',
    usu_penaliza: 'NULL',
  },
  {
    customerId: 1474,
    customerName: 'ALEJANDRO MUÑOZ LOREDO',
    rfc: 'MULA750405',
    id_vendedor: 'NULL',
    calle: 'CAROLINA 125 DEP 14',
    ciudad: 'BENITO JUAREZ',
    colonia: 'NOCHEBUENA',
    delegacion: 'BENITO JUAREZ',
    cp: '03720',
    pais: 'MÉXICO',
    fax: 'NULL',
    telefono: 54484000,
    correoweb: 'amunozl@sky.com.mx',
    estado: 'DISTRITO FEDERAL',
    curp: 'NULL',
    lista_negra: 'N',
    apellido_paterno: '',
    apellido_materno: '',
    muni_id: 'NULL',
    esta_id: 9,
    fecha_lista_negra: 'NULL',
    fecha_liberacion: 'NULL',
    id_penalizacion: 'NULL',
    tipo_persona: 'F',
    rfc_homologado: 'NULL',
    usu_libera: 'NULL',
    fec_libera: 'NULL',
    no_registro: 680471881,
    cve_act_economica: 'NULL',
    tipo_identificacion: 'NULL',
    num_identificacion: 'NULL',
    id_representante: 'NULL',
    no_exterior: 'NULL',
    no_interior: 'NULL',
    contrasena: 'NULL',
    usuario: 'NULL',
    clabe_interbancaria: 'NULL',
    banco: 'NULL',
    sucursal: 'NULL',
    cuenta_cheques: 'NULL',
    fec_ini_penalizacion: 'NULL',
    fec_fin_penalizacion: 'NULL',
    usu_penaliza: 'NULL',
  },
  {
    customerId: 1475,
    customerName: 'ARTURO',
    rfc: 'HECA740303FQ2',
    id_vendedor: 'NULL',
    calle: '2A NORTE ORIENTE # 720',
    ciudad: 'TUXTLA GUTIERREZ',
    colonia: 'TERAN',
    delegacion: 'TUXTLA GUTIERREZ',
    cp: 29050,
    pais: 'MÉXICO',
    fax: 'NULL',
    telefono: 9616637569,
    correoweb: 'arturohc1974@gmail.com',
    estado: 'CHIAPAS',
    curp: 'HECA740303HPLRSR00',
    lista_negra: 'N',
    apellido_paterno: 'HERRERA',
    apellido_materno: 'CASTILLO',
    muni_id: 'NULL',
    esta_id: 7,
    fecha_lista_negra: 'NULL',
    fecha_liberacion: 'NULL',
    id_penalizacion: 'NULL',
    tipo_persona: 'F',
    rfc_homologado: 'NULL',
    usu_libera: 'NULL',
    fec_libera: 'NULL',
    no_registro: 685822572,
    cve_act_economica: 'NULL',
    tipo_identificacion: 'NULL',
    num_identificacion: 'NULL',
    id_representante: 'NULL',
    no_exterior: 'NULL',
    no_interior: 'NULL',
    contrasena: 'rUQPxVSQ/1nSIOCULSEDtQ==',
    usuario: 'camaro2016',
    clabe_interbancaria: '021100040185478108',
    banco: '021',
    sucursal: '00853',
    cuenta_cheques: 4018547810,
    fec_ini_penalizacion: 'NULL',
    fec_fin_penalizacion: 'NULL',
    usu_penaliza: 'NULL',
  },
  {
    customerId: 1476,
    customerName: 'BENJAMIN CARRILLO CAMEZ',
    rfc: 'CACB741011K12',
    id_vendedor: 'NULL',
    calle: 'NACIONES UNIDAS 6301',
    ciudad: 'ZAPOPAN',
    colonia: 'PARQUE DE LA CASTELLANA',
    delegacion: 'ZAPOPAN',
    cp: 'NULL',
    pais: 'MÉXICO',
    fax: 'NULL',
    telefono: 3336739857,
    correoweb: 'BENJALM@YAHOO.COM',
    estado: 'JALISCO',
    curp: 'NULL',
    lista_negra: 'N',
    apellido_paterno: '',
    apellido_materno: '',
    muni_id: 'NULL',
    esta_id: 14,
    fecha_lista_negra: 'NULL',
    fecha_liberacion: 'NULL',
    id_penalizacion: 'NULL',
    tipo_persona: 'F',
    rfc_homologado: 'NULL',
    usu_libera: 'NULL',
    fec_libera: 'NULL',
    no_registro: 685822372,
    cve_act_economica: 'NULL',
    tipo_identificacion: 'NULL',
    num_identificacion: 'NULL',
    id_representante: 'NULL',
    no_exterior: 'NULL',
    no_interior: 'NULL',
    contrasena: 'NULL',
    usuario: 'NULL',
    clabe_interbancaria: 'NULL',
    banco: 'NULL',
    sucursal: 'NULL',
    cuenta_cheques: 'NULL',
    fec_ini_penalizacion: 'NULL',
    fec_fin_penalizacion: 'NULL',
    usu_penaliza: 'NULL',
  },
  {
    customerId: 1477,
    customerName: 'BENJAMIN FLORES',
    rfc: 'FOXB630212',
    id_vendedor: 'NULL',
    calle: 'ANDADOR DEL MONTE 138',
    ciudad: 'AGUASCALIENTES',
    colonia: 'UND POTREROS DEL OESTE',
    delegacion: 'AGUASCALIENTES',
    cp: 20280,
    pais: 'MÉXICO',
    fax: 'NULL',
    telefono: 'NULL',
    correoweb: 'benjas1963@hotmail.com',
    estado: 'AGUASCALIENTES',
    curp: 'NULL',
    lista_negra: 'N',
    apellido_paterno: '',
    apellido_materno: '',
    muni_id: 'NULL',
    esta_id: 1,
    fecha_lista_negra: 'NULL',
    fecha_liberacion: 'NULL',
    id_penalizacion: 'NULL',
    tipo_persona: 'F',
    rfc_homologado: 'NULL',
    usu_libera: 'NULL',
    fec_libera: 'NULL',
    no_registro: 680471882,
    cve_act_economica: 'NULL',
    tipo_identificacion: 'NULL',
    num_identificacion: 'NULL',
    id_representante: 'NULL',
    no_exterior: 'NULL',
    no_interior: 'NULL',
    contrasena: 'NULL',
    usuario: 'NULL',
    clabe_interbancaria: 'NULL',
    banco: 'NULL',
    sucursal: 'NULL',
    cuenta_cheques: 'NULL',
    fec_ini_penalizacion: 'NULL',
    fec_fin_penalizacion: 'NULL',
    usu_penaliza: 'NULL',
  },
];
