export const data = [
  {
    id_tpevento: 1,
    descripcion: 'SUBASTA',
    desc_recibo: 'SUBASTA PUBLICA',
    uso: '3',
    id_tipo_disp: 11,
    id_tipo_fallo: 11,
  },
  {
    id_tpevento: 2,
    descripcion: 'LICITACION',
    desc_recibo: 'LICITACION PUBLICA',
    uso: '3',
    id_tipo_disp: 12,
    id_tipo_fallo: 22,
  },
  {
    id_tpevento: 3,
    descripcion: 'ADJUDICACIÖN DIRECTA',
    desc_recibo: 'ADJUDICACIÖN DIRECTA',
    uso: '3',
    id_tipo_disp: 33,
    id_tipo_fallo: 22,
  },
  {
    id_tpevento: 4,
    descripcion: 'SUBASTA ELECTRONICA',
    desc_recibo: 'SUBASTA ELECTRONICA',
    uso: '3',
    id_tipo_disp: 22,
    id_tipo_fallo: 11,
  },
  {
    id_tpevento: 6,
    descripcion: 'REMESA',
    desc_recibo: null,
    uso: '1',
    id_tipo_disp: null,
    id_tipo_fallo: null,
  },
  {
    id_tpevento: 7,
    descripcion: 'REMESA AUTOMATICA',
    desc_recibo: null,
    uso: '1',
    id_tipo_disp: null,
    id_tipo_fallo: null,
  },
  {
    id_tpevento: 5,
    descripcion: 'INTERCAMBIO DE FACTURAS',
    desc_recibo: 'VTAS CHATARRA',
    uso: '3',
    id_tipo_disp: 22,
    id_tipo_fallo: 55,
  },
  {
    id_tpevento: 8,
    descripcion: 'GASTOS',
    desc_recibo: 'GASTOS ADMIN',
    uso: null,
    id_tipo_disp: null,
    id_tipo_fallo: null,
  },
  {
    id_tpevento: 9,
    descripcion: 'INCONSISTENCIAS',
    desc_recibo: 'BIENES NO COMERCIALIZABLES',
    uso: null,
    id_tipo_disp: null,
    id_tipo_fallo: null,
  },
  {
    id_tpevento: 10,
    descripcion: 'PREPARACION',
    desc_recibo: 'BIENES EN PREPARACION COMERCIA',
    uso: '2',
    id_tipo_disp: null,
    id_tipo_fallo: null,
  },
  {
    id_tpevento: 11,
    descripcion: 'VENTA DE BASES',
    desc_recibo: 'VENTA DE BASES',
    uso: null,
    id_tipo_disp: null,
    id_tipo_fallo: null,
  },
  {
    id_tpevento: 12,
    descripcion: 'REMATES',
    desc_recibo: 'REMATES',
    uso: '3',
    id_tipo_disp: null,
    id_tipo_fallo: null,
  },
  {
    id_tpevento: 13,
    descripcion: 'SUBASTA A.F.E.',
    desc_recibo: 'SUBASTA ACTIVOS FINANCIEROS',
    uso: '3',
    id_tipo_disp: 11,
    id_tipo_fallo: 11,
  },
  {
    id_tpevento: 14,
    descripcion: 'SORTEO',
    desc_recibo: 'SORTEO',
    uso: '3',
    id_tipo_disp: 33,
    id_tipo_fallo: 22,
  },
];
