import { FormControl, Validators } from '@angular/forms';
import { onlyNumbers } from 'src/app/common/validations/numeric.validators';
import { STRING_PATTERN } from 'src/app/core/shared/patterns';

export const GOOD_CAPTURE_FORM = {
  noPartida: new FormControl<string>(null, [
    Validators.required,
    Validators.minLength(8),
    Validators.maxLength(8),
    onlyNumbers(),
  ]),
  valorAvaluo: new FormControl('', [Validators.required]),
  capitulo: new FormControl('', [Validators.required]),
  partida: new FormControl('', [Validators.required]),
  subpartida: new FormControl('', [Validators.required]),
  ssubpartida: new FormControl('', [Validators.required]),
  noClasifBien: new FormControl<number>(null, [Validators.required]),
  type: new FormControl<string | number>(null, [Validators.required]),
  subtype: new FormControl<string | number>('', [Validators.required]),
  ssubtype: new FormControl<string | number>('', [Validators.required]),
  sssubtype: new FormControl<string | number>('', [Validators.required]),
  unidadLigie: new FormControl('', [Validators.required]),
  unidadMedida: new FormControl(null, [
    Validators.required,
    Validators.pattern(STRING_PATTERN),
  ]),
  cantidad: new FormControl<number>(null, [
    Validators.required,
    Validators.min(1),
  ]),
  destino: new FormControl(null, [Validators.required]),
  estadoConservacion: new FormControl(null, [Validators.required]),
  noBien: new FormControl({ value: null, disabled: true }, [
    Validators.required,
  ]),
  valRef: new FormControl(null, [
    Validators.required,
    Validators.pattern(STRING_PATTERN),
  ]),
  identifica: new FormControl(null, [
    Validators.required,
    Validators.pattern(STRING_PATTERN),
  ]),
  descripcion: new FormControl(null, [
    Validators.required,
    Validators.pattern(STRING_PATTERN),
  ]),
  fichaNumerario: new FormControl(null, [Validators.required]),
  captura: new FormControl('', [Validators.required]),
  cambioValor: new FormControl('', [Validators.required]),
  requery: new FormControl(null, [Validators.required]),
  satTipoExpediente: new FormControl(null, [Validators.required]),
  satIndicator: new FormControl(null, [Validators.required]),
  validFrac: new FormControl(null, [Validators.required]),
  almacen: new FormControl(false, [Validators.required]),
  entFed: new FormControl(null, [Validators.required]),
  municipio: new FormControl(null, [Validators.required]),
  ciudad: new FormControl(null, [Validators.required]),
  localidad: new FormControl(null, [Validators.required]),
  flyerNumber: new FormControl<string | number>(null),
  observaciones: new FormControl<string | number>(null),
  esEmpresa: new FormControl<boolean>(null),
  noExpediente: new FormControl<number>(null),
};

export const GOOD_FORM = {
  val1: new FormControl<string | number>(null),
  val2: new FormControl<string | number>(null),
  val3: new FormControl<string | number>(null),
  val4: new FormControl<string | number>(null),
  val5: new FormControl<string | number>(null),
  val6: new FormControl<string | number>(null),
  val7: new FormControl<string | number>(null),
  val8: new FormControl<string | number>(null),
  val9: new FormControl<string | number>(null),
  val10: new FormControl<string | number>(null),
  val11: new FormControl<string | number>(null),
  val12: new FormControl<string | number>(null),
  val13: new FormControl<string | number>(null),
  val14: new FormControl<string | number>(null),
  val15: new FormControl<string | number>(null),
  val16: new FormControl<string | number>(null),
  val17: new FormControl<string | number>(null),
  val18: new FormControl<string | number>(null),
  val19: new FormControl<string | number>(null),
  val20: new FormControl<string | number>(null),
  val21: new FormControl<string | number>(null),
  val22: new FormControl<string | number>(null),
  val23: new FormControl<string | number>(null),
  val24: new FormControl<string | number>(null),
  val25: new FormControl<string | number>(null),
  val26: new FormControl<string | number>(null),
  val27: new FormControl<string | number>(null),
  val28: new FormControl<string | number>(null),
  val29: new FormControl<string | number>(null),
  val30: new FormControl<string | number>(null),
  val31: new FormControl<string | number>(null),
  val32: new FormControl<string | number>(null),
  val33: new FormControl<string | number>(null),
  val34: new FormControl<string | number>(null),
  val35: new FormControl<string | number>(null),
  val36: new FormControl<string | number>(null),
  val37: new FormControl<string | number>(null),
  val38: new FormControl<string | number>(null),
  val39: new FormControl<string | number>(null),
  val40: new FormControl<string | number>(null),
  val41: new FormControl<string | number>(null),
  val42: new FormControl<string | number>(null),
  val43: new FormControl<string | number>(null),
  val44: new FormControl<string | number>(null),
  val45: new FormControl<string | number>(null),
  val46: new FormControl<string | number>(null),
  val47: new FormControl<string | number>(null),
  val48: new FormControl<string | number>(null),
  val49: new FormControl<string | number>(null),
  val50: new FormControl<string | number>(null),
  val51: new FormControl<string | number>(null),
  val52: new FormControl<string | number>(null),
  val53: new FormControl<string | number>(null),
  val54: new FormControl<string | number>(null),
  val55: new FormControl<string | number>(null),
  val56: new FormControl<string | number>(null),
  val57: new FormControl<string | number>(null),
  val58: new FormControl<string | number>(null),
  val59: new FormControl<string | number>(null),
  val60: new FormControl<string | number>(null),
  val61: new FormControl<string | number>(null),
  val62: new FormControl<string | number>(null),
  val63: new FormControl<string | number>(null),
  val64: new FormControl<string | number>(null),
  val65: new FormControl<string | number>(null),
  val66: new FormControl<string | number>(null),
  val67: new FormControl<string | number>(null),
  val68: new FormControl<string | number>(null),
  val69: new FormControl<string | number>(null),
  val70: new FormControl<string | number>(null),
  val71: new FormControl<string | number>(null),
  val72: new FormControl<string | number>(null),
  val73: new FormControl<string | number>(null),
  val74: new FormControl<string | number>(null),
  val75: new FormControl<string | number>(null),
  val76: new FormControl<string | number>(null),
  val77: new FormControl<string | number>(null),
  val78: new FormControl<string | number>(null),
  val79: new FormControl<string | number>(null),
  val80: new FormControl<string | number>(null),
  val81: new FormControl<string | number>(null),
  val82: new FormControl<string | number>(null),
  val83: new FormControl<string | number>(null),
  val84: new FormControl<string | number>(null),
  val85: new FormControl<string | number>(null),
  val86: new FormControl<string | number>(null),
  val87: new FormControl<string | number>(null),
  val88: new FormControl<string | number>(null),
  val89: new FormControl<string | number>(null),
  val90: new FormControl<string | number>(null),
  val91: new FormControl<string | number>(null),
  val92: new FormControl<string | number>(null),
  val93: new FormControl<string | number>(null),
  val94: new FormControl<string | number>(null),
  val95: new FormControl<string | number>(null),
  val96: new FormControl<string | number>(null),
  val97: new FormControl<string | number>(null),
  val98: new FormControl<string | number>(null),
  val99: new FormControl<string | number>(null),
  val100: new FormControl<string | number>(null),
  val101: new FormControl<string | number>(null),
  val102: new FormControl<string | number>(null),
  val103: new FormControl<string | number>(null),
  val104: new FormControl<string | number>(null),
  val105: new FormControl<string | number>(null),
  val106: new FormControl<string | number>(null),
  val107: new FormControl<string | number>(null),
  val108: new FormControl<string | number>(null),
  val109: new FormControl<string | number>(null),
  val110: new FormControl<string | number>(null),
  val111: new FormControl<string | number>(null),
  val112: new FormControl<string | number>(null),
  val113: new FormControl<string | number>(null),
  val114: new FormControl<string | number>(null),
  val115: new FormControl<string | number>(null),
  val116: new FormControl<string | number>(null),
  val117: new FormControl<string | number>(null),
  val118: new FormControl<string | number>(null),
  val119: new FormControl<string | number>(null),
  val120: new FormControl<string | number>(null),
};
