export interface IProccedingsDeliveryReception {
  id?: number;
  keysProceedings?: string;
  elaborationDate?: string | number;
  datePhysicalReception?: string;
  address?: string;
  statusProceedings?: string;
  elaborate?: string;
  numFile?: number;
  witness1?: string;
  witness2?: string;
  typeProceedings?: string;
  dateElaborationReceipt?: Date | string;
  dateDeliveryGood?: Date | string;
  responsible?: string;
  destructionMethod?: string;
  observations?: string;
  approvedXAdmon?: string;
  approvalDateXAdmon?: Date | string;
  approvalUserXAdmon?: string;
  numRegister?: number;
  captureDate?: string;
  numDelegation1?: number | string;
  numDelegation2?: number | string;
  identifier?: string;
  label?: string;
  universalFolio?: number;
  numeraryFolio?: number;
  numTransfer?: number;
  idTypeProceedings?: string;
  receiptKey?: string;
  comptrollerWitness?: string;
  numRequest?: number;
  closeDate?: Date | string;
  maxDate?: Date | string;
  indFulfilled?: number;
  dateCaptureHc?: Date | string;
  dateCloseHc?: Date | string;
  dateMaxHc?: Date | string;
  receiveBy?: string;
  affair?: string;
}
