export const cabmsData = [
  {
    cabms: 'keycabms1',
    category: 'Category 231',
    itemDescription: 'Articulo Description',
    partId: 'cvepart156',
    opcode: 'OperCod5664',
    opDescription: 'OperCod5664 Description',
  },
  {
    cabms: 'keycabms2',
    category: 'Category 1231',
    itemDescription: 'Articulo Description',
    partId: 'cvepart342',
    opcode: 'OperCod423424',
    opDescription: 'OperCod5664 Description',
  },
  {
    cabms: 'keycabms3',
    category: 'Category 231',
    itemDescription: 'Articulo Description',
    partId: 'cvepart156',
    opcode: 'OperCod5664',
    opDescription: 'OperCod5664 Description',
  },
  {
    cabms: 'keycabms4',
    category: 'Category 231',
    itemDescription: 'Articulo Description',
    partId: 'cvepart156',
    opcode: 'OperCod5664',
    opDescription: 'OperCod5664 Description',
  },
  {
    cabms: 'keycabms5',
    category: 'Category 231',
    itemDescription: 'Articulo Description',
    partId: 'cvepart156',
    opcode: 'OperCod5664',
    opDescription: 'OperCod5664 Description',
  },
  {
    cabms: 'keycabms6',
    category: 'Category 2dsad31',
    itemDescription: 'Articulo Description',
    partId: 'cvepart156',
    opcode: 'OperCod5664',
    opDescription: 'OperCod5664 Description',
  },
];
