name: Docker Image CI

on:
  push:
    branches: [ "docker-qa" ]



jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Obtener nombre del repositorio
      id: obtener-nombre-repo
      run: |
        echo "::set-output name=repo_name::$(echo sigebi-appqa)"
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm install --legacy-peer-deps
    - name: Build application
      run: npm run build
    - name: Build the Docker image
      run: |
        docker login acrindep.azurecr.io --username ${{ secrets.USER }} -p ${{ secrets.PASSWORD }}
        docker build -t acrindep.azurecr.io/ns-sb-0001-sigebi/${{ steps.obtener-nombre-repo.outputs.repo_name }}:${{ github.sha }} ./nginx.dockerfile .
        docker push acrindep.azurecr.io/ns-sb-0001-sigebi/${{ steps.obtener-nombre-repo.outputs.repo_name }}:${{ github.sha }}

    - name: Install cURL
      run: sudo apt-get install -y curl

    - name: Call API
      run: |
          # Aquí puedes realizar la llamada a la API utilizando cURL o cualquier otra herramienta de tu elección
          body='{"ms":"${{ steps.obtener-nombre-repo.outputs.repo_name }}","hash":"${{ github.sha }}"}'
          
          # Realizar la llamada a la API con el cuerpo de la solicitud
          curl -X POST -H "Content-Type: application/json" -d "$body" "https://us-central1-joyeria-isabel-sucre.cloudfunctions.net/aks"
