export const COLUMNS = {
  moveId: {
    title: 'No. Movto.',
    width: '15%',
    type: 'string',
    sort: false,
  },
  date: {
    title: 'Fecha',
    width: '15%',
    type: 'string',
    sort: false,
  },
  move: {
    title: 'Movimiento',
    width: '15%',
    type: 'string',
    sort: false,
  },
  account: {
    title: 'Cuenta',
    width: '15%',
    type: 'string',
    sort: false,
  },
  reference: {
    title: 'Referencia',
    width: '15%',
    type: 'string',
    sort: false,
  },
  entryOrder: {
    title: 'Ref.Orden Ing.',
    width: '15%',
    type: 'string',
    sort: false,
  },
  bank: {
    title: 'Banco',
    width: '15%',
    type: 'string',
    sort: false,
  },
  office: {
    title: 'Sucursal',
    width: '15%',
    type: 'string',
    sort: false,
  },
  amount: {
    title: 'Monto',
    width: '15%',
    type: 'string',
    sort: false,
  },
  result: {
    title: 'Resultado',
    width: '15%',
    type: 'string',
    sort: false,
  },
  valid: {
    title: 'Valido',
    width: '15%',
    type: 'string',
    sort: false,
  },
  paymentId: {
    title: 'Id.Pago',
    width: '15%',
    type: 'string',
    sort: false,
  },
  batch: {
    title: 'Lote Pub.',
    width: '15%',
    type: 'string',
    sort: false,
  },
  event: {
    title: 'Evento',
    width: '15%',
    type: 'string',
    sort: false,
  },
  entry: {
    title: 'Orden Ing.',
    width: '15%',
    type: 'string',
    sort: false,
  },
  date2: {
    title: 'Fecha',
    width: '15%',
    type: 'string',
    sort: false,
  },
  descriptionSATpayment: {
    title: 'Desc. Pago SAT',
    width: '15%',
    type: 'string',
    sort: false,
  },
};
